### ISSUE TITLE
verbiage change in  “your range use plan has been sent to other agreement holders for confirmation” screen 

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#108]
Change last sentence in screen to "This submission will be reviewed by the range staff before it is forwarded to the decision maker."

**Comment by micheal-w-wells** [comment]
in test

**Comment by micheal-w-wells** [comment]
closing as this appears to be done

**Comment by calebissharp** [comment]
@micheal-w-wells Is there a PR you can attach to this issue?

**Comment by micheal-w-wells** [comment]
Not sure when it was addressed I didn't fix it this round @calebissharp
