### ISSUE TITLE
Refactor main RUP form to use formik instead of redux and add CRUD capabilities

### ISSUE THREAD

**Issue by twostoryrobotrange** [bcgov/range-web#115]
Formik is a state container and handles a lot of the state updating on it's own. It will essentially remove the need for redux to handle the form data. 

The RUP also needs CRUD capabilities; we want the plan to be editable on the web the same way it is on the iPad. Because of the way Formik works this is a relatively easy thing to add in at the same time as the form refactoring.

**Comment by twostoryrobotrange** [comment]
Partially addressed by #114.

**Comment by calebissharp** [comment]
This has since been resolved by subsequent PRs after #114.
