### ISSUE TITLE
The Plan End Date on the RUPs is displaying the wrong date

### ISSUE THREAD

**Issue by twostoryrobotrange** [bcgov/range-web#121]
When a user submits a date way in the future (many years) through the api on a create, it renders in web as a much earlier date.

![image](https://user-images.githubusercontent.com/50648653/64464898-a9a46e00-d0be-11e9-9340-f17e85f36ac6.png)

It's displaying as the last day of the `Agreement Date` so there is mostly like a check on the component that restricts it to only allow the date to be as late as the end of `Agreement Date`.

**Comment by micheal-w-wells** [comment]
While the date is now the correct one, the formatting should match the agreement date formatting:

![image](https://user-images.githubusercontent.com/955467/66064885-22022180-e4fb-11e9-8710-d55fd50cdc69.png)
