### ISSUE TITLE
still unable to load plans in test after refactor

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#126]
Steps to reproduce (was done in Range (test) openshift project):

1. Login as range officer
2. Click on an existing RUP
3. Plan fails to load.  See below error:

![image](https://user-images.githubusercontent.com/955467/65906895-281bc500-e378-11e9-9056-5d5e32981050.png)

@calebissharp message if you need a plan that looks like the one having an issue or if you need any assistance/access testing in the env it gets deployed to.

**Comment by calebissharp** [comment]
@micheal-w-wells Yeah, it would be helpful to have access to the env so I can try and see what the error is. The plan would be nice to have also. Is it just this one plan that throws an error? Or are they all failing to load?

**Comment by micheal-w-wells** [comment]
Different plans.  The one i sent last time also throws this error for me, Lisa would be looking at other plans and has same result.  DM me your preferred email and I'll sort out your access.

**Comment by micheal-w-wells** [comment]
this one is resolved, thanks @calebissharp !
