### ISSUE TITLE
Pasture | Add pasture did not prompt for a pasture name

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#133]
Used "Add Pasture" button. New pasture added but did not prompt me for a pasture name. I then added a name in the blank field that had been generated by the "Pasture:" label. Should always prompt for a new pasture name and show that name beside the pasture label.

**Comment by LisaMoore1** [comment]
@calebissharp Also noted that the default name "pasture" that is being entered when "Add Pasture" is selected is not an acceptable name for the pasture. It should be REQUIRED that a new pasture name be added. This might be the right time for the popup screen model so they MUST enter. They could then edit by typing into the field as shown now. 

On that side of things I do wonder if it is preferred to have an "edit" option that is selected to make things editable so there isn't an accidental overwrite mistake scenario. The user would have to show intent to edit by selecting edit. It is an extra step but I do worry about accidents. Ideas?

**Comment by calebissharp** [comment]
@LisaMoore1 Yeah, I'll add a dialog. I'm also not super keen on the title turning into a text field on select. I think an edit button that opens the same dialog as when creating a pasture could work well.

**Comment by LisaMoore1** [comment]
@calebissharp we're both on the same page. Thx
