### ISSUE TITLE
range readiness date does not include year and neither should calendar -- error generates

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#137]
Date format is month and day only --> calendar (and resulting data entry) should not include the year.
Should  align with iPad and AH-web formatting 

**REQUIREMENTS**
- [x] range readiness date includes a calendar
- [ ] opened calendar shows months only (no year)
- [ ] when selection made only the month and day are recorded in the field

**Comment by LisaMoore1** [comment]
@calebissharp calendar is still showing a year (ex. "October 2019"). Needs to just have the month in calendar heading (ex. "October").

**Comment by LisaMoore1** [comment]
@calebissharp realized that it would be more helpful if I left the "ready to test" label on but just left them in the pipleline so you can easily see which ones you labelled. I'll add a comment for each on why I haven't moved them to done. If there is something you think might work better let me know.

**Comment by calebissharp** [comment]
@LisaMoore1 I think that's a good idea. Then, once an issue has been resolved, we can close it.

**Comment by LisaMoore1** [comment]
Only issue I just noticed with that is that when I look back through the list I can’t tell which ones you might really now have ready for test vs. those that still haven’t had a second list.  How about a “revisit” label or something else like that so both of us can identify them?

**Comment by calebissharp** [comment]
@LisaMoore1 I like the idea of a "revisit" label (or maybe "unresolved", that's a bit more specific). Then you'll know if it's something you've tested already and I'll know it's something I need to fix.

**Comment by LisaMoore1** [comment]
I like “unresolved”. I can’t seem to make labels so if you make it, I’ll start using it.

**Comment by calebissharp** [comment]
@LisaMoore1, ok should be ready to use now.
