### ISSUE TITLE
No option to delete an existing pasture

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#148]
# Requirements
- [x] delete option visible
- [x] reminder popup that delete is permanent
- [x] reminder popup that all related plant communities, monitoring areas and criteria will also be deleted
- [x] reminder popup that schedule rows with that pasture will be impacted
- [x] pasture (including associated plant communities, monitoring areas and criteria) is deleted
- [x] schedule rows having that pasture are deleted

#Definition of Done
- [x] pasture and related content  deletes and no errors arise in schedule

**Comment by LisaMoore1** [comment]
@calebissharp Staff should be prevented from submitting a RUP to AH (either to 1-C, to 5-R, 19-RFS or to 10-NF) if there are no pastures included in the plan. 

I generated a fun set of errors by deleting all of the pastures out of a RUP that had schedule entries and then submitting it back to the AH. Took me awhile to figure out how to get out of the error loop.

**Comment by calebissharp** [comment]
@LisaMoore1 Is there an issue for that? If not, I'll create one since that is unrelated to this issue.

**Comment by LisaMoore1** [comment]
@calebissharp It is #413

**Comment by calebissharp** [comment]
Thank you!
