### ISSUE TITLE
Pastures | On create pasture, Private Land Deduction default is not setting

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#151]
Default is 0
The default is required or it generates an error that prevent saving the plan

**Comment by LisaMoore1** [comment]
@calebissharp Definitely setting default to 0. I am curious though...if the field is blank (like say I had a value there and then I deleted it) does that = 0 for the purposes of the schedule calculation? I just want to confirm that if that field is blank it doesn't create an error when doing schedule AUM calculation math. Thinking you're probably all over that and handling it with some sort of IF statement that captures the "" value and uses a 0 in the math. 
Can your confirm that no error will be generated by a blank field here? I can create a new issue if needed. 
Thx

**Comment by calebissharp** [comment]
@LisaMoore1 Yep, it looks like it handles blank values as 0. I did notice that the grazing schedule wasn't actually updating its calculations when the pld value was changes, so I pushed a fix for that.
