### ISSUE TITLE
Required Fields in additional requirements not easily identifiable

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#153]
Does not support smooth data entry

**Comment by LisaMoore1** [comment]
@mccullochk @calebissharp "This is on my think it's a quick win -- pull from it if you're looking for something" list.

**Comment by mccullochk** [comment]
@LisaMoore1, I assume this is one of the ones you were referring to?

**Comment by LisaMoore1** [comment]
@mccullochk Yes. I'll look for the list as soon as I can.

**Comment by mccullochk** [comment]
Required Fields:
- [ ] `Category`
- [ ] `Name`
- [ ] `Description`

**Comment by mccullochk** [comment]
Addressed in #390

**Comment by LisaMoore1** [comment]
@mccullochk Same sizing request for this one then I'll close it.
