### ISSUE TITLE
Required fields in plant community not clearly identified

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#165]
Required fields (action and details) must be easily identifiable without having to enter into the field. Must work for red/green colour blind.

**Comment by LisaMoore1** [comment]
@calebissharp The criteria and monitoring areas are embedded in the plant community section. I should have been more clear in the issue description. Sorry. Here's the full list:  
- Plant Communities | plant community description
- Plant Community Actions | Action, Details
- Monitoring Areas | Name, location, rangeland health, purpose
- Criteria | none (looks like readiness date is right now but shouldn't be)

**Comment by calebissharp** [comment]
@LisaMoore1 Does the monitoring area location include latitude and longitude?

**Comment by LisaMoore1** [comment]
Not as required info.  Just the text field is required.

**Comment by calebissharp** [comment]
@LisaMoore1 Sounds good. The PR has been merged so in about 15 minutes the changes should be live.

**Comment by LisaMoore1** [comment]
@calebissharp Realized that the "required field" concept in these nested things has another aspect that is probably self-apparent but thought I'd mention. Fields in a nested section say monitoring area are only required IF you include a monitoring area.
