### ISSUE TITLE
Calendar for no graze window for plant community action includes a year but the field is only mm and dd

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#166]
**REQUIREMENTS**
- [x] calendar label is month only ex. "October"
- [ ] only month and day are captured in field

**Comment by calebissharp** [comment]
Related to #137

**Comment by LisaMoore1** [comment]
@calebissharp Noticed today that the no-graze window field is showing year, month, day and time.  Just want month and day for these two fields.  See requirements above.  Looked good before (or I didn’t notice it) so not sure what happened.
