### ISSUE TITLE
Stubble height value is accepting values with decimal points but should be whole numbers only (or rounded to such)

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#174]

**Comment by calebissharp** [comment]
@LisaMoore1 I'm a bit confused with this one, could I get some clarification? In #178 it says the default value for stubble height should be to one decimal, while this issue states they should be whole numbers only. I'm just wondering if I'm misinterpreting something, or missing some other information.

**Comment by LisaMoore1** [comment]
Readiness and stubble height should both have one decimal. This one can probably go. Not sure what I was thinking...  Should pull the default values in to one decimal. Thanks for catching this.

**Comment by calebissharp** [comment]
@LisaMoore1 Sounds good, thanks for clarifying.
