### ISSUE TITLE
Selecting the "other" option for indicator plant in readiness and stubble height is not opening a prompt to enter a value for other.

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#177]
**REQUIREMENTS**
- [x] other option is an option on drop down
- [ ] selecting other opens popup
- [ ] popup allows data entry to define what the other species is
- [ ] the text entered in the popup is displayed in the “Indicator Species” field

**Comment by LisaMoore1** [comment]
@calebissharp Should I be seeing this in test now? Might take a time or two for me to figure out when things are actually ready.  Thx

**Comment by calebissharp** [comment]
@LisaMoore1 Yes, I think so.

**Comment by LisaMoore1** [comment]
@calebissharp The user needs a predictable way to interact with dropdowns and "other" options.  The pop up model (like for adding a Plant Community) is our standard.  Is it possible to make the indicator plant lists and actions function in the same way? It would mean having the custom value appear in the same space that would otherwise house the selected option from the ref table (at least I think where that value is coming from). Is that doable?

**Related** -- I thought I captured this in another issue somewhere but I can't find it now so thought I'd better capture it while it is on my mind. 

Dropdown list for both readiness and stubble height should only show those species that aren't shrubs. Alder is an example of a shrub -- anything that falls in the same category (I think it is the boolean value for [ref_plant_species].[is_shrub_use] that identifies them) should not be included in readiness/stubble height.

**Comment by calebissharp** [comment]
Yes, I could change it to that. I did it this way because I felt like it provides better indication to a user that it is an "other" type, as they are handled slightly differently on the backend. However if you want to handle it transparently with the dialog, I can do that as well. I could also make it so the user can enter a custom value right into the dropdown, so it would behave sort of like a combination dropdown and text box ([Here's](https://react.semantic-ui.com/modules/dropdown/#usage-allow-additions) an example if that doesn't make sense).


That's the same bug as described in #239, correct? I should get around to it next week.

**Comment by calebissharp** [comment]
@LisaMoore1 Just pinging you in case you missed this. Would appreciate your thoughts.

**Comment by LisaMoore1** [comment]
Thanks. Did miss it. Our users think of any entry as all the same (that there is a back end doing anything is kind of foreign to them). If we do the entry into the dropdown it will introduce something other than what has been standard...but that would give them a chance to try something else and maybe like it better. I'm good with whichever is easier for you of the two options you propose.

On a separate note -- if you're working on this now we should assign it to the 0.5 milestone, give it some points and stick it in the sprint pipeline.  I'll let you do that for this (any anything else in Lisa's playground) you are working on between now and end of day. Thx

**Comment by calebissharp** [comment]
Ok, I'll do the direct entry in the dropdown then!

I think this way may also provide a more streamlined workflow. For example, a user can type the plant they want into a field, and will immediately know if it already exists or if they should add it. The search functionality we'll have is a good idea for such a large list anyway. With the dialog option, they'd have to scroll through the entire dropdown and if they can't find what they're looking for, know to click "Other". There could also be cases where they don't see a plant that is pre-populated, and then end up adding it themselves.

As with any user interaction change, it will take time for users to get used to it. On the positive side, we haven't actually had this type of data entry on web yet, just the iOS app, so they may implicitly expect different types of interaction anyway.

I didn't actually see that we had a milestone, but I'll be sure to add any issues.

**Comment by LisaMoore1** [comment]
@calebissharp Same behaviour (and preference) as #169

**Comment by LisaMoore1** [comment]
@calebissharp Please update so that "ENTER" also advances cursor to next field (as TAB currently behaves)
