### ISSUE TITLE
Hitting "submit" on monitoring area name leads to plain white screen I cannot back out of -- can't test further

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#179]

**Comment by calebissharp** [comment]
@LisaMoore1 Is it alright if we close this in favour of #150? They appear to be referencing the same bug.

**Comment by LisaMoore1** [comment]
For sure. I made sure they both have same user stories for context. Go ahead and close it.

Thanks for working on these by the way. :)

Lisa Moore, P.Ag.
Rangeland Policy Specialist
Range Branch - FLNRORD
iPad




On Oct 8, 2019, at 3:33 PM, Caleb Sharp <notifications@github.com> wrote:

﻿

@LisaMoore1<https://github.com/LisaMoore1> Is it alright if we close this in favour of #150<https://github.com/bcgov/range-web/issues/150>? They appear to be referencing the same bug.

**Comment by calebissharp** [comment]
Sounds good, thanks.

Thanks for putting together all the issues to work on!

**Comment by calebissharp** [comment]
Closing in favour of #150.
