### ISSUE TITLE
When creating or editing Issue name there is no option to name an issue if "other" selected from Issue Type list

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#192]
# Requirements
- [ ] prompt is visible on screen
- [ ] text entered in prompt appears in the Issue Type label

**Comment by calebissharp** [comment]
@LisaMoore1 Is this like #337/#338?

**Comment by LisaMoore1** [comment]
@calebissharp Yes. Same but I think #337 and #338 might be more descriptive.
