### ISSUE TITLE
Required fields not clearly identifiable for Minister's Issues

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#193]

**Comment by LisaMoore1** [comment]
@mccullochk @calebissharp "This is on my think it's a quick win -- pull from it if you're looking for something" list.

**Comment by mccullochk** [comment]
@LisaMoore1, I assume this is one of the ones you were referring to?

**Comment by mccullochk** [comment]
Required Fields:
- [ ] `Type`
- [ ] `Details`
- [ ] `Objective`

**Comment by mccullochk** [comment]
Addressed in #390

**Comment by LisaMoore1** [comment]
@mccullochk What size was this?  I'll close it once I update that.
