### ISSUE TITLE
Option to copy an existing additional requirement not available

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#201]

**Comment by LisaMoore1** [comment]
@mccullochk Not sure why this one is in Sprint backlog. Relatively low priority for now. If there was a specific reason you moved it over can you let me know?

**Comment by mccullochk** [comment]
I thought it might makes sense to tackle along side https://github.com/bcgov/range-web/issues/299. If there are more important things to handle then I will un-assign myself from this and pick up something else.
