### ISSUE TITLE
CRUD - As a staff person I want to update all existing pasture content in a RUP on WEB so that I can quickly enter data

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#220]
First CRUD story I'd like to release on. When we have test this we release this bit. 
Includes the sub-components (plant communities, monitoring areas, criteria)

**Comment by LisaMoore1** [comment]
@calebissharp How are you feeling about getting this user story done in next sprint? I'm sure you  already knew this, but I'm finding it helpful looking at the summary above to see which issues are remaining in this story and what's been accomplished.
 
I'm not sure how available you are to us for the next sprint (ends Oct 30) but am wondering if you can check in with @micheal-w-wells re. helping him with a couple issues left over from sprint 0.5 after this user story is done and/or working on user story #226.

**Comment by calebissharp** [comment]
@LisaMoore1 The implementation for #169 and #177 is already finished and is being deployed to test right now. I think most of the future CRUD updates are going to rely a lot on updating the backend with new features, such as versioning. This relates particularly to #247, which is going to need a backend update unless I'm misunderstanding it.

I'm hoping to focus on range for the next couple of weeks.  I imagine I'll spend some time on the PDF generation, but we're still working out the best way to do that.
