### ISSUE TITLE
Private Land Deduction (in pasture) showing percent as a decimal but should be showing (allowing entry) as a percent (i.e. 10 rather than 0.1)

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#221]

**Comment by LisaMoore1** [comment]
@calebissharp RAN099953 (a record in test) is showing 10% when created in the iPad but displaying as 0.1 in web. I wonder if what happens right now is:
- staff enter something like 10 in the field on the iPad
- it being recorded as 0.1 in the table
I'm not able to check that.  Regardless of what is being recorded in the table, we want the field to be a whole number.

**Comment by LisaMoore1** [comment]
@calebissharp I just checked the agreement holder web version and it is also incorrectly displaying the private land deduction as a decimal rather whole number percentage (ex. 0.1 instead of 10). I think the decimal is needed because we use it in math for the schedule to calculate crown AUMs but staff need to be able to enter and see it as whole number.  Staff should never see or enter a value with a decimal here but that is what will be recorded in the table. Make sense?

**Comment by calebissharp** [comment]
@LisaMoore1 Yep, that clears up some stuff.

**Comment by LisaMoore1** [comment]
@calebissharp When something is back to being ready for me to test can you pull the "unresolved" label off? I think we talked about that workflow before but can't remember.

**Comment by calebissharp** [comment]
@LisaMoore1 Yep, that's the plan. Sorry, I've been a bit busy today with another project. Next week I'm going to resolve a bunch of these issues.

**Comment by LisaMoore1** [comment]
@calebissharp Thanks for fixing to show %. Can we have it to whole numbers only please (i.e. no decimal points)?  Thanks
