### ISSUE TITLE
Make a single page containing all content needed to print a PDF

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#234]
We have beyond wonky PDF generating code right now.  We need the server to actually serve up a PDF, so that we have one available for both iOS and web, and later via email automation.  

The approach we will take will be to create a single view RUP page containing all content, with @media-print css, and PDF generated using headless chrome via a https://www.browserless.io/ container running in openshift and serve it up via web or the API.  The browserless container itself has an api around headless chrome so its probably ok if we just call that API from the button in web. 

This issue is for the task to create the single view rup page with the right content, there will be another for styling with @media-print css where necessary, and another for the browserless setup, and one more to wire the button up and write the api call.

**Comment by micheal-w-wells** [comment]
this one is done based on recent refactorings

**Comment by calebissharp** [comment]
Resolved by #269
