### ISSUE TITLE
Style PDF print page with @media-print css

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#235]
see #234

**Comment by micheal-w-wells** [comment]
this is the critical issue needed for a good PDF from chrome, can tackle the API version of it later

**Comment by calebissharp** [comment]
@micheal-w-wells I think this may be easier with a dedicated set of components/a page for printing, instead of trying to manipulate the existing ones to fit a print layout. I get the feeling the structure of the page will be fundamentally different since we don't care about having things editable, and a lot of the elements would be discarded in a print view. Because we only have to read the data for a print page, it would be pretty simple to manage state.

**Comment by micheal-w-wells** [comment]
I'd wondered about that.  No worries, often times things are more clear once you dig in to it.  Reopening  #234

**Comment by micheal-w-wells** [comment]
@LisaMoore1 @calebissharp asked what is most important to do next, I mentioned stuff around pastures but I think you guys are done that, so I think this would be next.   You also mentioned you had a behaviour in test that we don't have in prod, can you create an issue for that so we can nail that one down and get ready to deploy?

**Comment by LisaMoore1** [comment]
@calebissharp works on Chrome on my desktop but on both Chrome and Safari on my iPad (where lots of ranchers and staff are doing this) when I select "Download PDF" a webpage opens with a very pretty first page of a RUP but it isn't actually letting me see the other 9 pages or generating a PDF. Any idea why?

**Comment by LisaMoore1** [comment]
@calebissharp This seems to be working correctly for me now? Do we need to leave "unresolved" on or can I close it?

**Comment by LisaMoore1** [comment]
@calebissharp Another thought. How complex is it to force this to open in a separate tab? Thinking here about reducing risk of lost data. If it opens is there risk of downloading PDF before saving, closing the PDF when done and consequently losing the data that was entered in that session?

**Comment by calebissharp** [comment]
@LisaMoore1 You shouldn't have to worry about unsaved data, at least on a desktop. When you close the PDF modal, the data should still be there. On iOS though, does opening the actual PDF open it in the same tab?

You can also remove the unresolved label and close this issue if you don't have any other further concerns.

**Comment by LisaMoore1** [comment]
@calebissharp in iOS it opens the PDF in the same tab as myrangebc = close the tab the PDF is on = close the myrangebc tab.

**Comment by LisaMoore1** [comment]
@calebissharp Thoughts on this? Is there an issue with it opening in same tab or am I good to go closing this?

**Comment by calebissharp** [comment]
@LisaMoore1 I've actually figured out a way to open the PDFs in a new tab on iOS. I'll remove the "unresolved" label once it gets deployed, and if it works for you, you can go ahead and close the issue.

**Comment by calebissharp** [comment]
@LisaMoore1 Changes should be deployed now. Let me know if it works for you.
