### ISSUE TITLE
Plant Community name cannot be edited

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#247]
**REQUIREMENTS**
- [ ] existing plant community name can be selected
- [ ] selection dropdown list visible showing plant communities and "other"
- [ ] new plant community can be selected
- [ ] if "other" is selected popup to enter name for other
- [ ] entry for "other" displays in the "Plant Community: X" label for X

**Comment by LisaMoore1** [comment]
@calebissharp can you estimate a size on this issue?

**Comment by calebissharp** [comment]
@LisaMoore1 This one might be tricky, since it isn't implemented on the backend either. Not sure if it would be better to wait for versioning or not.

**Comment by LisaMoore1** [comment]
@mccullochk @calebissharp @micheal-w-wells If anyone is looking for a quick one I think one probably qualifies.

**Comment by calebissharp** [comment]
@LisaMoore1 I'm fairly certain this will depend on an endpoint added with the versioning changes (https://github.com/bcgov/range-api/pull/77)

**Comment by LisaMoore1** [comment]
@calebissharp Even taking the approach that a plan is a draft all the way until it is approved? Until then it is just a pencil and eraser sort of exercise. I'm not too up on the endpoint side of things though so definitely will rely on your expertise on this one.

**Comment by calebissharp** [comment]
@LisaMoore1 Even though the plan may be a draft, there doesn't currently exist an endpoint that allows the plant community to be updated. That endpoint just happened to be added with the versioning changes, but it isn't actually directly related to versioning.

It would be possible to add a client-side only update that allows you to change the name before the plant community is persisted, but I would *not* recommend this as it could be confusing to users who have no way of knowing if a plant community is persisted or not, therefore causing the name editing to appear as buggy or erratic behaviour.

**Comment by LisaMoore1** [comment]
@calebissharp all good. We can save this one until later.
