### ISSUE TITLE
usage (web only)

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#271]
Extend usage to end of plan date, base it on last year of agreement usage.

**Comment by LisaMoore1** [comment]
@micheal-w-wells Do I need to do something to trigger the update to usage? If I have a plan & agreement ending in 2023 I see usage to 2023. When I change the plan end date to 2027 the usage table is not increasing to show to 2027. Is that expected?

**Comment by micheal-w-wells** [comment]
@LisaMoore1 did you try refreshing the page?  This is web right (and in test)?  If that doesn't work, can you send me (email, slack, rocket) the RAN?

**Comment by LisaMoore1** [comment]
@micheal-w-wells Part of my problem was not selecting "Save Draft".  When I do that I get **one** year of usage data past the end date but not for all of the years of the plan. 
Example: RAN099952 expires Dec 31, 2023 -- Plan dates set for 2023-2027
After "Save Draft" Usage shows for 2023 and 2024. 

If I move the start date back to 2022 it immediately adds the 2022 usage data (no save draft required)

**Comment by micheal-w-wells** [comment]
Interesting.  I also was just messing with the same RAN by total coincidence.  When i view it on web I get a new year of usage for every year I expect, but i just updated the date directly in the database.

**Comment by micheal-w-wells** [comment]
I take that back, its a couple years shy for some reason, but still into the 40's.  I'll dig in to it.  I'll try and figure out why you are getting the behaviour you have seen also.

**Comment by micheal-w-wells** [comment]
can you confirm @LisaMoore1 that https://web-range-myra-test.pathfinder.gov.bc.ca/range-use-plan/27 there are usage years up to 2041?  I see the reason it doesn't go to 2047, still figuring out why you have the behaviour you do though.

**Comment by micheal-w-wells** [comment]
@LisaMoore1  Ready to test again.  Won't fall short on years after saving.  If i hammer the date picker repeatedly, once in a blue moon it won't update the usage preview prior to saving, still tinkering there.  Let me know if you experience anything different.

**Comment by LisaMoore1** [comment]
@micheal-w-wells
It added the years when I saved! Do we need to add a note to that effect (maybe to the right of plan end date) before releasing this?  

“Usage data for plan years beyond agreement expiry are copied from the final year of the agreement. Select “save draft” at top right to update usage after changing plan date.”

Staff are going to wonder about being able to update that data (to address non-use or temporary increase) but we can note that as a future enhancement in release update information I provide to staff.  Thoughts?

**Comment by LisaMoore1** [comment]
@micheal-w-wells Thoughts on my comment above? I haven't labelled "unresolved" as we could release like this -- it just may need some instruction. I could provide that in separate documentation but wonder about the effort associated with adding this in app instruction. Thoughts? Ideally it would show up as an info popup if you change the plan end date to past the agreement expiry rather than on screen all the time. Where do you think this sits in priorities/effort? If worth doing is it something Caleb can do if you are working with Mike's team?

**Comment by micheal-w-wells** [comment]
@LisaMoore1 I like the in app instruction idea.  I'll look at it this afternoon and loop in @calebissharp about a general approach to help tips/pop ups in the web app.

**Comment by micheal-w-wells** [comment]
made in app help but isn't deployed yet, working through a quirk, but tomorrow morning sometime it will be there to test.

**Comment by LisaMoore1** [comment]
Didn't see the "help" but noticed that it is now updating usage as soon as the plan years change so marked as closed.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 the help will be there in 20 minutes-ish.  I tested the usage stuff a whole bunch, sometimes it doesn't update before a save, but it does 99% of the time for me.   Always works after a save, so I mention saving in the help note.
