### ISSUE TITLE
The OTHER option for "Add Plant Community" is inconsistent and not formatted clearly. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#272]
Some sort of weird behaviour -- See user story #163 
First time: I typed "other" then selected "other" from the list and was prompted to give it a name
Second time: I typed "other" and it did not prompt me for a name nor did it save it as "other" (i.e. no plant community created)
All the time: if I don't type anything but select "other" from the list I am prompted to provide a name and everything works correctly. 

Also, when I first tried this it wasn't clear where the cursor was and that I could type and then select. It is possible to put the "filter" function either at the top of the list with placeholder text something like "enter filter text here" or create some shading or some other visual where the cursor is with the same placeholder text option? Is it worth considering now what that would look like if you were going to edit the name of the plant community?

**Comment by calebissharp** [comment]
@LisaMoore1 The "other" bug should be easy enough to fix I think.

Also, I just noticed that filter option! To be totally honest I didn't know that existed until you pointed it out. Definitely isn't good UI haha. I'll try and make it work better.
