### ISSUE TITLE
Calendar fields easily disrupted to unreasonable year and hard to get back to reasonable

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#273]
@calebissharp 

**STEPS TO CREATE PROBLEM**
Select "Plan End Date" field
Cursor is in field
Press backspace a couple of times because you think you can type into the field
Year gets significantly smaller for each backspace 
Select month YYYY at top of the calendar
Small numbers (not years) showing up in list
Select it again to get a broader range of years to select from
No easy way to get back the 2000s
Select one of them then month date etc and the date shows an unreasonable number (ex. December 31, 0044)

**OPTIONS**
- [ ] don't allow cursor entry into the field, just open the calendar --> prevent the problem with year
- [x] allow cursor entry but prevent date from changing without calendar selection (keystrokes do nothing)
- [ ] allow cursor entry and allow manual entry of date into the field (preferred but might need to be a separate issue/enhancement -- I'm OK with that we just can't release while it is doing this weird thing to the year)

**Comment by LisaMoore1** [comment]
@calebissharp I think this is fairly critical before we move data entry on web to PROD.

**Comment by calebissharp** [comment]
@LisaMoore1 I'm just to prevent the user from typing in the field, like the 2nd option you presented, at least for now. The other solutions might require us to find a different date picker component to use, which I agree, can probably wait if it becomes necessary.

**Comment by LisaMoore1** [comment]
@calebissharp OK. Works for me. I selected that one above.

**Comment by calebissharp** [comment]
@LisaMoore1 were there any other issues that related to the datepicker?

**Comment by LisaMoore1** [comment]
@calebissharp  I don't think so. Once you're in the right range of year it is easy enough to navigate to different dates. My only complaint would be that if your existing date is say December 31, 2023 and you select the year to 2027 it defaults the picker back to January and you have to then select December 31st again. Relatively small thing but a little irritating when you just want to change the year element.

**Comment by calebissharp** [comment]
@LisaMoore1 I'm not sure I follow. To change the year I click the header (where it says "December 2023" or whatever) and then use the arrows the select a year. Then you can select the month again for that year. You can also click the header again from the month selection to pick a year from a list if you want.

**Comment by LisaMoore1** [comment]
@calebissharp  Here's the long workflow and what is a little irritating. 

1. touch date and year at top of calendar (ex, December 2026)
2. touch the year at the top (ex. 2026)
3. select a new year (ex. 2027)
4. Select a month (ex. December)
5. Select a date (ex. 31)
6. select somewhere outside of calendar

It is just annoying that I have to do steps 4 and 5 when all i wanted to change was year, In my dreams I'd do step 3 and then exit the calendar (not do 4-5) and it would hold on to December 31. Not worth spending energy on just irritating when you're playing with date a bunch of times in a row. All good if we can prevent the backspace problem.
