### ISSUE TITLE
There is no warning that data may be lost if you exit a RUP without saving the draft. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#274]
**REQUIREMENTS**
- [ ] when you try to navigate (in any way) away from a RUP that is being edited a warning message is visible indicating something like: "This draft has not been saved and changes will be lost."  Options to exit without saving or return to draft. Or perhaps a save and exit option. 
  - navigate away with browser
  - submit to AH
  - create PDF
- [ ] options behave as expected

**Comment by LisaMoore1** [comment]
@calebissharp Is this message designed to show only if there are unsaved changes or any time you navigate away from current page? 
If any time, the message should be changed to "This RUP may have unsaved changes..."
If only when unsaved changes exist the behaviour is unexpected because as soon as I open a RUP then immediately navigate away I get the message.

**Comment by LisaMoore1** [comment]
@calebissharp Immediately after a "save draft" action, selecting the back arrow to the left of the RAN does not result in navigation or message. Select it again immediately and it returns to work queue without providing message. 
If focus goes elsewhere in plan (ex. Range Name) after the "save draft" action selecting the back arrow results in warning message.

**Comment by calebissharp** [comment]
@LisaMoore1 The behaviour is to show the message if there are unsaved changes. 

I can't reproduce this:
> If only when unsaved changes exist the behaviour is unexpected because as soon as I open a RUP then immediately navigate away I get the message.

or this:

> If focus goes elsewhere in plan (ex. Range Name) after the "save draft" action selecting the back arrow results in warning message.

But the issue you had with the back button should be fixed

**Comment by LisaMoore1** [comment]
On chrome (iPad only) I’m getting this: ![IMG_7449.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/429915a7-6e94-4309-9324-0d6e830f9ed4)
Would that be a setting I have in chrome?

**Comment by calebissharp** [comment]
@LisaMoore1 This is a browser behaviour thing outside of our control. It's there to prevent websites from spamming people with popups by giving them an escape hatch to disable them.

**Comment by LisaMoore1** [comment]
@calebissharp Sorry...I keep wondering other little things. 
The text on the box says: This RUP has unsaved changes that will be lost if you leave this page. Are you sure you want to continue?
The answers are OK and cancel. 
Those aren’t actual answers to this question. Yes (I want to continue) and No (I do not want to continue) would be more appropriate options. 
This has caught me several times where I either pick the wrong one or have to stop and think which I want when I’m blasting through these screens testing. Is standard OK/Cancel messaging or can we change to Yes/No?

**Comment by calebissharp** [comment]
@LisaMoore1 Sorry, also something that's based on the browser that we can't change. Perhaps changing the wording of the message would help though?

**Comment by LisaMoore1** [comment]
@calebissharp Sorry...I keep wondering other little things. 
The text on the box says: This RUP has unsaved changes that will be lost if you leave this page. Are you sure you want to continue?
The answers are OK and cancel. 
Those aren’t actual answers to this question. Yes (I want to continue) and No (I do not want to continue) would be more appropriate options. 
This has caught me several times where I either pick the wrong one or have to stop and think which I want when I’m blasting through these screens testing. Is standard OK/Cancel messaging or can we change to Yes/No?

**Comment by LisaMoore1** [comment]
@calebissharp I think OK and Cancel are responses to a statement not a question. 

How does rewording to this seem to you? WARNING: This RUP has unsaved changes that will be lost if you leave this page. 

In that way the answers make more sense: OK (I read it and I get it) Cancel (Cancel this thing I just started)

**Comment by LisaMoore1** [comment]
@calebissharp Works for me

**Comment by LisaMoore1** [comment]
This still gave me a brain stutter but I can’t think of really great language that would accommodate OK/Cancel options. Maybe something like: 
“This RUP has unsaved changed that will be lost if you select OK here.”

I’m closing this one recognizing that there might be some complaints about his dialog.
