### ISSUE TITLE
single AH RUP does not record confirmation when no changes are requested.

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#289]
@LisaMoore1 this is the one we worked on earlier today

**Comment by mccullochk** [comment]
@micheal-w-wells, if you have already fixed this I'm going to assign it to you and put it in `In Progress` if that's okay?

**Comment by LisaMoore1** [comment]
@mccullochk @micheal-e-wells I think this one is ready I just couldn’t test it because of the behaviors in TEST were preventing me from submitting an agreement for approval. As soon as the schedule issues or done I will be able to test this one.

**Comment by LisaMoore1** [comment]
@micheal-w-wells See issues #309 #310 for why this is still at "ready to test"
