### ISSUE TITLE
AH should not be able to “add action” for a plant community

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#293]
Remove this option. AH cannot make any changes in any pasture/plant community fields.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 i'll look at this one

**Comment by micheal-w-wells** [comment]
give it 20 min and you can test

**Comment by LisaMoore1** [comment]
@micheal-w-wells Are you able to try this on Safari on an iPad? It works on chrome for me but is behaving exactly as though there hasn’t been an update on Safari on my iPad. I am having same problem with #295 that @mccullochk worked on. I am now suspecting it might be something on my end but I cannot figure out what the issue is. Have checked for popup blockers (none) have logged out, closed all windows and completely closed out of Safari...  Not sure what else to try. Ideas?

**Comment by LisaMoore1** [comment]
@micheal-w-wells @mccullochk I managed to open it on my phone (where I’ve never had it opened before) and both this issue and #295 work fine on Safari. Not sure if that helps with troubleshooting at all.

**Comment by LisaMoore1** [comment]
@micheal-w-wells @mccullochk Cleared cache and tried over (thanks for the email) and working now. Will close this and #295
