### ISSUE TITLE
Save draft/submit issues with RAN099952 that I can't figure out. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#309]
@micheal-w-wells @calebissharp Tagged you so you could take a look. Not sure if a critical thing or not so leaving in "New Issues" for now. 

Content fairly complete I think (no obvious things missing/wrong).  

- Save Draft (error saving draft) -- last time I didn't have that but got an error submitting. 
- scrolled around a bit more (don't think I changed anything but must have) tried save draft and got "could not submit due to invalid fields"
- went to Invasive Plants and selected "other" -- field appeared -- I typed "Thing2" (I think) --> Save Draft worked but now "other" is selected but my text is not displaying. 

...so now I have a saved draft...
- touch "submit" --> it goes white but doesn't do anything

Weirdness.

**Comment by calebissharp** [comment]
@LisaMoore1 I've pushed a fix for the "invalid fields" error. There weren't actually any errors, it was just a bug in the validation when the form hadn't been touched yet. The other problems in this issue aren't related to that.

**Comment by LisaMoore1** [comment]
@caleb. I’m getting a save error (not sure if it is the same one) if I add a management consideration and then try to save.  See video on Slack.  On the video I also made a change to invasives — but I tried it later with just invasives and it saved (but hid the “other” details) but if I tried to save after adding a management consideration I got the error.  RAN099952

**Comment by LisaMoore1** [comment]
@calebissharp @mccullock — I was able to add and delete a management consideration though. Yay!!
