### ISSUE TITLE
Submit issue "an unexpected error occurred. (undefined is not an object (evaluating'e.id'))" for RAN099953 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#310]
@micheal-w-wells @calebissharp Tried to test #289 and got this and #309

- submit option active
- 1. Ready to Submit popup --> as expected 
- 2. Ready to Submit? Choose Submission Type -- I selected "submit for final decision" --> as expected
- 3. Confirm our submission and eSignature -- I checked box/selected Submit Initial RUP
- got "an unexpected error occurred. (undefined is not an object (evaluating'e.id'))" message

Same message occurs is I try to submit for feedback.

**Comment by calebissharp** [comment]
@LisaMoore1 I don't know if we've changed anything related to the submit workflow. Is this bug present in prod I wonder?

**Comment by LisaMoore1** [comment]
@calebissharp Not an issue in PROD.

**Comment by calebissharp** [comment]
@LisaMoore1 Alright, I'll investigate.

**Comment by LisaMoore1** [comment]
@calebissharp @micheal-w-wells Save function is now working throughout but:
RAN099952 — submit option goes white and doesn’t initiate submit workflow
RAN099953 — submit option initiates submit workflow but at end it generates the error “Internal server error occurred, please contact the administrator (MyRangeBC@gov.bc.ca).
