### ISSUE TITLE
Staff draft in web —> add pasture then save generates an error...but the save has happened  

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#321]
Actual function is OK but need to fix the error to avoid confusion. 

In staff draft:
- [x] pasture is added
- [x] save selected
- [ ] no error generated
- [x] content is saved

**Comment by LisaMoore1** [comment]
@micheal-w-wells @calebissharp Wondering if this is something like what we were having happen in agreement holder side earlier.

**Comment by calebissharp** [comment]
@LisaMoore1 It's slightly different. I know what's causing it though, since I fixed it when implementing versioning. I forgot to also fix it in `dev` though.
