### ISSUE TITLE
Staff person provides feedback including updating some fields —> submits as change requested or ready for submission —> goes back to AH but changes not saved

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#322]
Allows staff person to update many fields but there is no “save draft” option and if you push back to AH using “request changes” or “ready for submission” the changes aren’t being saved.

**Comment by LisaMoore1** [comment]
@micheal-w-wells @calebissharp Not sure if this is a quick thing in terms of triggering save when the status is updated (in sprint backlog) or needs to be an issue that requires more action and we need to reprioritize and handle with communication or something else. Initial thoughts?

**Comment by micheal-w-wells** [comment]
@LisaMoore1 I could see how this one is a big problem but shouldn't be too huge to fix.  I'll see what I can figure out and bug @calebissharp if I hit a wall.

**Comment by micheal-w-wells** [comment]
![image](https://user-images.githubusercontent.com/955467/69449824-99d91500-0d10-11ea-982b-4846b9e4194f.png)
How to reproduce the 'no option to save draft' @LisaMoore1 ?  I'm missing something sorry

**Comment by calebissharp** [comment]
Related to #326 I think.

**Comment by LisaMoore1** [comment]
@micheal-w-wells in status 13 the save option is great but we don’t want a **Submit** option as we need the staff person to select from the plan actions .

**Comment by LisaMoore1** [comment]
@micheal-w-wells @calebissharp this is working now EXCEPT that the "submit" button is still visible.  Is getting rid of that something that can happen easily right now or should we just deploy as is?  There are potential workflow issues by having staff "submit" from here.  I haven't tested them but will if I need to -- it just isn't a needed for here when we want them to use plan actions.

**Comment by micheal-w-wells** [comment]
fixed in #355
