### ISSUE TITLE
AH person selecting “amend” for approved plan results in series of errors

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#334]

**Comment by LisaMoore1** [comment]
@calebissharp I’m not sure if this is related to the versioning side of things.  If that is the case I think that we can remove ability to do amendments for this sprint/maybe next (make a note in the yellow on home page maybe?) and have sorted after that. Do you think this belongs with your work on versioning this sprint or next?

**Comment by calebissharp** [comment]
@LisaMoore1 What's the purpose of amendments again?

**Comment by LisaMoore1** [comment]
@calebissharp Once an approved version has been reached the plan may become out of date (ex. the minister decides there needs to be a new issue or more commonly an AH changes their schedule). The amendment workflows involve a new version (starts as a copy of the currently approved plan), edits being made, type of amendment being identified (there are two types with different workflows) and subsequent recommendations and decision (if necessary). Mandatory amendments are basically exactly like the current workflow. Minor amendments have some interesting nuances. Mandatory amendments can be initiated by either AH or staff; minor amendments initiated by AH only.

**Comment by mccullochk** [comment]
@LisaMoore1, are you wanting that whole workflow built out or for the errors to fixed?

**Comment by calebissharp** [comment]
@LisaMoore1 Did any of this workflow exist before in web? Or would this be new?

**Comment by LisaMoore1** [comment]
@calebissharp @mccullochk All of the workflow for AH to initiate amend worked on web.

**Comment by LisaMoore1** [comment]
@calebissharp @mccullochk in your opinions is this something we can make progress on now or would it be better to not do anything with this until we can implement some versioning components in test? If now not ideal timing I've got a couple of other XS tasks that need being done if @mccullochk want to switch.

**Comment by calebissharp** [comment]
I'm not sure. I'm a bit fuzzy on what the amendments are and how they're implemented. I also don't know how it relates to versioning.

**Comment by LisaMoore1** [comment]
@mccullochk Let's make this card about dealing with the errors. A good chunk of the workflow exists but with the errors I can't test it to see what else needs attention/completion.  That seem reasonable?

**Comment by LisaMoore1** [comment]
@calebissharp comment from two days ago tries to explain.  At the most basic level the workflow goes something like:
There is an approved plan
AH or staff need to change it and get it re-sign for some reason
User (AH or staff) select "amend" which should trigger a new version (copy) of the plan so that the approved one stays exactly like it was when it was signed
Changes are made to the copy (including back and forth with staff just like when creating an original RUP)
Amendment is signed by AH and goes to staff to make recommendation to decision maker (as per original RUP)
Once the amendment is identified as "approved" (status selection by staff until decision making is digital) the previous version becomes historic (but still visible) and the amendment becomes the current legal approved version.
Future amendments are built on the most recent approved version

Since all RUPs get amended over time eventually every RUP will have more than one "approved" RUP, one identified as current legal version (the most recently approved) and one (but never more than one) amendment in progress (all those things that happen between creation and approval)

**Comment by mccullochk** [comment]
Okay. Let's stick to fixing the errors. Which I have a PR for. I'll submit that to test now and then we can go from there. Thanks @LisaMoore1.

**Comment by calebissharp** [comment]
@LisaMoore1 Thanks, I think with that and after looking at the code, I'm starting to understand now.

**Comment by LisaMoore1** [comment]
@mccullochk Initial error issue gone but if I select "confirm" on the popup that comes up immediately I get two internal server errors.

**Comment by mccullochk** [comment]
Can you provide a screen shot of the errors please?

**Comment by LisaMoore1** [comment]
@mccullochk![AFC308C2-B8B5-4A56-A05F-3992E697B6AD.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/c80a5bb5-9c88-47e5-9efe-3d3cbc0fa9f0)

**Comment by LisaMoore1** [comment]
@mccullochk I’ll try. I’m on my iPad so might take me a bit.

**Comment by LisaMoore1** [comment]
Errors no longer generating. Other issues need to be created for the amendment work flow:
Once the amendment is created:
- "amend plan" option no longer available anywhere (can only have one amendment)
- amended version should be opened rather than staying on the approved version
