### ISSUE TITLE
RUP view is not updating properly after additional signatories confirm (sign) 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#335]
If I am not the first person confirming (signing) a plan, after I work thru the confirmation screens that I have signed is updated in the backend but the screen still looks like I need to sign until I go back out to the queue and then re-enter the RUP

**Comment by calebissharp** [comment]
@LisaMoore1 Are there any other workflows where the page needs to be refreshed?

**Comment by LisaMoore1** [comment]
@calebissharp If there are I can't think of any right now.

**Comment by LisaMoore1** [comment]
@calebissharp Not sure if this is related but another thing slow to update relates to pasture/plant community. If you are missing required fields in plant community it makes the heading for plant community and the related pasture enter "warning visuals". After you've fixed missing required fields in a plant community the plant community will lose "warning" signs but the pasture doesn't update at the same time. Haven't completely explored the details there but it just came to mind. Will make a separate issue for that one (low priority right now) soon.

**Comment by LisaMoore1** [comment]
@calebissharp Everything works as expected for plans created on web. 

Created on iPad (ex RAN099932)
Tom Haverford signed and submitted for decision which initiated the awaiting signatures workflow but the signature status screens are not indicating that he signed (they should since he __must__ sign in order to trigger the awaiting signatures workflow)
Chris Traeger (the other signatory) gets to “confirm your submission choice” screen, selects send for decision, checks the legal submission box and clicks OK —> goes into permanent spinning wheel on the OK button.

**Comment by calebissharp** [comment]
@micheal-w-wells Does the plan for RAN099932 have associated `plan_confirmation` records for each user?

**Comment by calebissharp** [comment]
I think this needs to be solved by a database migration. All plans should have corresponding `plan_confirmation` records. @micheal-w-wells Can you check if there are any plans in prod without any `plan_confirmation` rows?

**Comment by micheal-w-wells** [comment]
@LisaMoore1 do you know very approx when he/you signed it?  Trying to figure out if there's an issue or if this is one we manually mucked with.

**Comment by LisaMoore1** [comment]
@micheal-w-wells I did it yesterday.

**Comment by LisaMoore1** [comment]
@micheal-w-wells @calebissharp Can finally log in to test.  099932 still not showing confirmations.  Tried workflow with RAn099914 and getting this error when try to have first person confirm.  Note that it is saving any notes I record in history but is not starting gather signatures workflow.  ![IMG_7414.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/bce0fd2a-5143-42ee-a207-a519e117ad26)

**Comment by calebissharp** [comment]
@micheal-w-wells It looks like we're still waiting for you to create those `plan_confirmation` records on the latest version of the plan. Any estimate on when you can get that done?

**Comment by LisaMoore1** [comment]
@calebissharp @micheal-w-wells RAN099914 (error generated above) has never been submitted for signatures until this morning so I would not expect there to be existing confirmation records for it. The error generated while trying to confirm.

**Comment by calebissharp** [comment]
@LisaMoore1 There are supposed to be confirmation records created whenever a plan is created, just set to false. The reason there aren't for some plans in test is because of a bug that was fixed a while ago. (https://github.com/bcgov/range-api/commit/0087ac24a0fed5e93d6d3cdb4f434dea4de7e1d2#diff-167bfbeadf588b6a0205da9e4567b230 was the fix). It's related to versioning, so the broken code never made it to prod and didn't mess up the data there.

**Comment by LisaMoore1** [comment]
@calebissharp @micheal-w-wells So do we **know** that there are no outstanding problems related to this issue (ready to close) or do we still need to do something then test?

**Comment by micheal-w-wells** [comment]
RAN099914 has plan confirmation records already and I haven't touch any today @calebissharp

**Comment by micheal-w-wells** [comment]
I deleted the extra two we created for 99932

**Comment by micheal-w-wells** [comment]
It had two to begin with.

**Comment by LisaMoore1** [comment]
This is what 099914 is looking like for me now (it is now showing it is awaiting signatures but still no confirmation records). Note that it looks to have moved to status 18 but didn’t record Leslie’s confirmation. Also note that the top drop down menu includes a “Sign submission” option even though in theory Leslie’s signature is what triggered this status. 

I also have video from this morning when I did the initial signature by Leslie showing the error if you want that. 

 ![IMG_7417.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/87038b9b-f68f-45c9-a986-4861c05752fb)

**Comment by micheal-w-wells** [comment]
Other clues: DB shows that the plan confirmation records were created on 2019-12-04  and updated on 2020-01-09 but are still false.

**Comment by micheal-w-wells** [comment]
myra=# select * from plan_confirmation where plan_id in (select id from plan where agreement_id = 'RAN099932');
 id | plan_id | confirmed |         created_at         |         updated_at         | client_id
----+---------+-----------+----------------------------+----------------------------+-----------
 65 |      37 | f         | 2019-08-28 20:33:26.319+00 | 2020-01-09 15:25:46.072+00 |      1544
 64 |      37 | f         | 2019-08-28 20:33:26.224+00 | 2020-01-09 15:25:46.072+00 |      1538
(2 rows)

myra=# select * from plan_version where plan_id in (select id from plan where agreement_id = 'RAN099932');
 version | canonical_id | plan_id |         created_at         |         updated_at
---------+--------------+---------+----------------------------+----------------------------
       1 |           37 |      37 | 2019-12-17 21:35:28.853+00 | 2019-12-17 21:35:28.853+00
       3 |           37 |      80 | 2019-12-17 22:32:13.547+00 | 2019-12-17 22:32:13.547+00
       4 |           37 |      82 | 2019-12-17 22:32:59.956+00 | 2019-12-17 22:32:59.956+00
      10 |           37 |      83 | 2019-12-18 21:03:01.648+00 | 2019-12-18 21:03:01.648+00
      23 |           37 |     105 | 2019-12-18 22:14:27.612+00 | 2019-12-18 22:14:27.612+00
      30 |           37 |     118 | 2019-12-19 00:16:57.723+00 | 2019-12-19 00:16:57.723+00
      35 |           37 |     125 | 2020-01-21 22:57:53.225+00 | 2020-01-21 22:57:53.225+00
      -1 |           37 |     148 | 2019-12-12 00:29:40.473+00 | 2020-01-21 22:57:53.239+00
(8 rows)

myra=# select * from plan_confirmation where plan_id in (select id from plan where agreement_id = 'RAN099914');

 id  | plan_id | confirmed |         created_at         |         updated_at         | client_id
-----+---------+-----------+----------------------------+----------------------------+-----------
 117 |      73 | f         | 2019-12-04 23:08:09.773+00 | 2020-01-09 15:25:46.072+00 |      1541
 116 |      73 | f         | 2019-12-04 23:08:09.678+00 | 2020-01-09 15:25:46.072+00 |      1545
(2 rows)

myra=# select * from plan_version where plan_id in (select id from plan where agreement_id = 'RAN099914');
 version | canonical_id | plan_id |         created_at         |         updated_at
---------+--------------+---------+----------------------------+----------------------------
       9 |           73 |      73 | 2019-12-18 21:02:49.433+00 | 2019-12-18 21:02:49.433+00
      24 |           73 |     104 | 2019-12-18 23:32:10.226+00 | 2019-12-18 23:32:10.226+00
      25 |           73 |     119 | 2019-12-18 23:32:22.901+00 | 2019-12-18 23:32:22.901+00
      26 |           73 |     120 | 2019-12-18 23:32:58.398+00 | 2019-12-18 23:32:58.398+00
      27 |           73 |     121 | 2019-12-18 23:33:33.102+00 | 2019-12-18 23:33:33.102+00
      28 |           73 |     122 | 2019-12-18 23:34:43.93+00  | 2019-12-18 23:34:43.93+00
      29 |           73 |     123 | 2019-12-18 23:35:36.811+00 | 2019-12-18 23:35:36.811+00
      -1 |           73 |     124 | 2019-12-12 00:29:40.473+00 | 2019-12-18 23:35:36.899+00
(8 rows)

**Comment by calebissharp** [comment]
@micheal-w-wells We're missing `plan_confirmation` records for the latest version of the plan (plan id: 124). The two existing records were for the initial version of the plan when it was created. The bug that was fixed was plan_confirmations weren't being duplicated when a new version was created (as you can see here).

**Comment by micheal-w-wells** [comment]
Do we add that to the migrations then? Won't all plans in prod be like this?

**Comment by calebissharp** [comment]
@micheal-w-wells No. Again, the reason the data in test is "corrupted" is because of a bug that was introduced **to test** after our last deploy to prod. That bug has been fixed, so never will have been and will never be present in prod.
