### ISSUE TITLE
When starting to enter text into description when adding a plant community an error appears under the field. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#336]
![0C718BB7-2609-4CB7-97D9-5FE64B28DCBD.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/18c8f625-3d94-4dfd-beb8-ae7a42cfd1c8)

**Comment by calebissharp** [comment]
Should just be a matter of making the error prettier (ie. "Required field"). We don't really have a way to _not_ have the error show up when you start typing though.

**Comment by LisaMoore1** [comment]
@calebissharp "required field" works for me.

**Comment by mccullochk** [comment]
@calebissharp if you've fix this can you assign yourself and move it to `In Progress` please?
