### ISSUE TITLE
If last selection from list was “other”, selecting other again does not trigger the prompt to add the name for other (Minister’s Issue).

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#337]

**Comment by LisaMoore1** [comment]
@calebissharp This might not be an issue once we deal with #338 but can we just make sure that we can enter two “other” issues in a row here?

**Comment by mccullochk** [comment]
@calebissharp was this fixed by #34w? If yes, can you assign yourself and move it to `In Progress` please?
