### ISSUE TITLE
“Other” text entered by staff for Minister’s Issue is not displaying

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#338]

**Comment by LisaMoore1** [comment]
@calebissharp I’m being prompted to enter text but it isn’t displaying — I can’t tell if it is saving or not.  Can you check RAN099952 and see if it has saved text for a couple of “other” options?

**Comment by calebissharp** [comment]
@LisaMoore1 It looks like minister issues don't actually have an "other" row in the database: http://schema-spy-range-myra-dev.pathfinder.gov.bc.ca/tables/minister_issue.html

**Comment by LisaMoore1** [comment]
@calebissharp — so lets just drop the sequence that prompts for text for Minister’s Issue. Any major risks with that do you think?

**Comment by calebissharp** [comment]
@LisaMoore1 Nope, I'm alright with that.

**Comment by mccullochk** [comment]
@calebissharp if you've fix this can you assign yourself and move it to `In Progress` please?
