### ISSUE TITLE
AH entering an action for an issue if they select “other” a box is showing for the text they enter but it isn’t displaying. They can manually enter into that field.

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#340]
I noticed that later when I went back to the field (after manually entering “5-add issue”) the field had this: 
{"id":6,"active":true,"placeholder":"Describe the action to be taken including what, where and when.","name":"5-add issue"}

![A4EBCD3E-A051-4555-94CD-705D2634A486.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/562c3a5e-a20c-467d-8703-fc7a7e19e740)

**Comment by LisaMoore1** [comment]
@calebissharp I think we might have done something with this last round and I’ve somehow missed this anomaly. Oops.

**Comment by LisaMoore1** [comment]
@calebissharp I'm moving this to sprint backlog because I think if we leave it like this it is only a matter of time before it creates confusion and data entry weirdness.  Not sure if it might be part of fix for anything else or not but moving it over will also help make sure I don't lose track of it.

**Comment by calebissharp** [comment]
@LisaMoore1 Is this still an issue? Should've been resolved by #342. Forgot to add the label though.

**Comment by LisaMoore1** [comment]
@calebissharp Resolved. If you put time into it please add a size and I'll close.
