### ISSUE TITLE
EDIT: Flush out process/logic for cleaning up stale client records

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#349]

**Comment by calebissharp** [comment]
@micheal-w-wells Should these FTA issues be in the range-api repo?

**Comment by micheal-w-wells** [comment]
@calebissharp there's an API and web component to this one.  Hoping to have RO's have an 'x' next to AH listed so they can exclude people if they shouldn't be there until I have collected enough rubber stamps for the FTA fix to go in. Want to tag team this today?  I don't have much else going on.

**Comment by calebissharp** [comment]
I think we'll want to wait until we merge the versioning changes in so we don't end up with two diverging features branches, especially on the API repo. 

For the API changes, do we just have to update the [client_agreement](http://schema-spy-range-myra-dev.pathfinder.gov.bc.ca/tables/client_agreement.html) table to have an `excluded` column?

**Comment by micheal-w-wells** [comment]
@calebissharp pretty much

**Comment by micheal-w-wells** [comment]
issue seems to be more the client agreement table,  sent csv for review to see if logic is sound for clearing them out

**Comment by micheal-w-wells** [comment]
After reviewing data in FTA we've landed on we can't clear out records in plan confirmation or client agreement until we have location code and status in them as well, which we've got separate issues for.
