### ISSUE TITLE
"Add Schedule" button disabled for some RUPs (agreement holder logged in)

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#358]
TEST
RAN099955 and RAN099951 

I'm not sure what they have in common but they are ones I was testing with when working through schedule oddness.

**Comment by calebissharp** [comment]
@LisaMoore1 I think I've determined the cause of this one. When a schedule has been added for each year of the plan, the "add" button is disabled. Can you confirm if the plans you were editing were in this state? If not, there is a bug somewhere. Otherwise, I think this is intended behaviour.

**Comment by LisaMoore1** [comment]
@calebissharp Your right.  All good.
