### ISSUE TITLE
"Save Draft" (staff-provide feedback) not working ("could not submit due to invalid fields)

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#359]
- Open RUP
- "Save Draft" --> "could not submit due to invalid fields"
- change plan end date --> "save draft" --> "could not submit due to invalid fields"

(Tested using RAN099954 in TEST)

**Comment by LisaMoore1** [comment]
@calebissharp Error not generated with RAN099955 which never had any schedules copied.

**Comment by calebissharp** [comment]
@LisaMoore1 There's a plant community action with a missing "details" value. Is this the cause?

**Comment by LisaMoore1** [comment]
@calebissharp Something going on though...

1. open RAN099954
2. add text to plant community Action [details] field
3. save = NO ERROR
4. use MyRA backarrow (by RAN at top left) to go to queue
5. reopen RAN099954
6. "Save Draft" -- error
7. text I entered in step 2 is not saved 
8. if I enter text in [details] AND change something like end date and do steps 3-5 the date stays changed but the text in [details] does not save. 

When there has been a successful save selecting "Plan Actions" triggers workflow for submitting back to AH. I can do that if you'd like but will wait until you tell me because I don't want to get out of this situation that is creating the error and then not be able to recreate it. Let me kow.

**Comment by LisaMoore1** [comment]
@calebissharp Also, when you return from queue to the RUP the heading for this card does not go red to indicate missing information there until you select in the card. I'm not sure if that is expected or not.

**Comment by LisaMoore1** [comment]
@calebissharp RAN099932 is doing the same thing except for the "Plant community description" field -- which was empty when I opened the RUP and I cannot seem to make edits "stick" even if it looks like save worked.

**Comment by calebissharp** [comment]
@LisaMoore1 The validation is a bit wonky in that it only shows invalid fields after you've modified them. The presumption is there shouldn't be any invalid data initially (ie. the data stored in the database should be valid).

The plant community description won't be modifiable until we get the versioning changes merged in, since there currently exists no endpoint to edit plant communities. Maybe ask @micheal-w-wells to fix it in the database for now.

**Comment by LisaMoore1** [comment]
@micheal-w-wells for RAN099954 and RAN099932 can you please add some text into the fields described above so we can confirm that is the issue? Thx.

**Comment by calebissharp** [comment]
@LisaMoore1 Has this been tested yet?

**Comment by LisaMoore1** [comment]
@calebissharp haven't gone back and worked through all the comments/issues. Got a couple of other things I need to do first today and then will do another pass through all these looking for things I can close.  Might be tomorrow when I get to it.

**Comment by calebissharp** [comment]
Alright. Let me know when you do.

**Comment by LisaMoore1** [comment]
Has been resolved through various other issues.
