### ISSUE TITLE
fix bad dates in schedule

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#366]
From a previous bug we have a number of grazing schedule entries that don't have the same year as the schedule.

WIP SQL

```sql
with messed_up_schedule_entries as (
	select 
		grazing_schedule_entry.id, 
		grazing_schedule.id, 
		grazing_schedule.year 
	from grazing_schedule_entry 
	join grazing_schedule on grazing_schedule_entry.id = grazing_schedule.id 
	where date_part('year', date_in) != grazing_schedule.year;
)
update grazing_schedule_entry a
set date_in = b.year + '-' + datepart('month') + '-' + datepart('day', date_in) + ' ' + datepart('time', date_in)
inner join messed_up_schedule_entries b on a.id = b.id
where id in messed_up_schedule_entries
```

**Comment by micheal-w-wells** [comment]
Tested this against one record:

`with messed_up_schedule_entries as (
        select 
                grazing_schedule_entry.id as entry_id,
                ref_zone.description,
                ref_district.description,
                grazing_schedule_entry.date_in, 
                grazing_schedule_entry.date_out, 
                grazing_schedule.id as schedule_id, 
                grazing_schedule.plan_id,
                grazing_schedule.year ,
                grazing_schedule_entry.updated_at
        from grazing_schedule_entry 
        join grazing_schedule on grazing_schedule_entry.grazing_schedule_id = grazing_schedule.id 
        join plan on grazing_schedule.plan_id = plan.id
        join agreement on plan.agreement_id = agreement.forest_file_id
        join ref_zone on agreement.zone_id = ref_zone.id
        join ref_district on ref_district.id = ref_zone.district_id
        where date_part('year', date_in) != grazing_schedule.year
)
update grazing_schedule_entry a 
set date_in  = 
cast(concat(            b.year,
                        substring(cast(a.date_in  as text), 5, length(cast(a.date_in as text))) 
                    ) as timestamp)
from messed_up_schedule_entries b
where id = 2686  and a.id = b.entry_id`



before: 2020-07-02 06:00:00+00 
after: 2019-07-02 06:00:00+00

Did dump of table and will run against all when @calebissharp gives query an eyeball.

**Comment by micheal-w-wells** [comment]
https://gist.github.com/micheal-w-wells/41e0db53092bbed2143295e7683c2770
easier on the eyes

**Comment by micheal-w-wells** [comment]
marking as ready to test but its more of a ready to review

**Comment by calebissharp** [comment]
@micheal-w-wells Looks good, but we don't want the `where id = 2686` part, right?
