### ISSUE TITLE
[Agreement Type] field in basic info on web is not correctly showing agreement type

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#367]
Code gets picked up from FTA [agreement_type_ID] (Agreement table)
Current MyRA only makes RUPs for agreements having code E01 or E02 (the grazing agreements)

If code = E01 then field displays "Grazing Licence"
If code = E02 then field displays "Grazing Permit"

**Comment by calebissharp** [comment]
@micheal-w-wells Are you working on this? Or can I steal it?
