### ISSUE TITLE
After an amendment is created but before it is approved/stands the "amend" button should no longer be visible on any versions

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#369]
This is to ensure that only one amendment can be in progress at any time.

**Comment by LisaMoore1** [comment]
“Current Legal Version” = the most recent approved or stands (and of the stands statuses) plan

Only the current legal version should show an amend option, AND 
If there is an amendment in progress (i.e. there is an approved plan and a draft plan) even the current legal should not have an amend option.

**Comment by micheal-w-wells** [comment]
Note for myself and @ZoeSimon : you need to be AH as these are minor amendments.

**Comment by LisaMoore1** [comment]
Can’t test this one until versioning is fixed so that I can look at previous versions.

**Comment by LisaMoore1** [comment]
This seems good. I’m closing.
