### ISSUE TITLE
In Staff Draft (6-"SD") in TEST staff need to have "submit" option so staff can submit draft to AH

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#375]
PROD is currently good.
- add "submit" option in toolbar for this status

**Comment by calebissharp** [comment]
@LisaMoore1 I assume range officers shouldn't be able to submit when the status is "recommended for submission", correct? Only the agreement holder should see a submit button?

**Comment by LisaMoore1** [comment]
@calebissharp Staff should only have the submit button when they are in staff draft.  All the rest of the time they use Plan Actions.

**Comment by calebissharp** [comment]
@LisaMoore1 Thanks, good to know. I assume the same goes for agreement holders (only show for statuses 1 and 5)? Or should they also see it for 13 (ready for final decision)?

**Comment by LisaMoore1** [comment]
@calebissharp missed the second part of your question.  I see there is some intersection with who can edit in that status. 
- AH needs "Submit" for all statuses they can edit (see #326 for list).
- staff need "plan actions" and no submit for all statuses they can edit EXCEPT 6 in which they need the submit button instead
- for statuses no one can edit there should be neither submit nor plan actions for anyone.

**Comment by calebissharp** [comment]
@LisaMoore1 Ok, I've got it now. Thanks for the help.
