### ISSUE TITLE
Staff person can submit to AH or request changes for an agreement that is missing required info or doesn't have toggles set to true

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#378]
All required content (that staff owns) must be complete and all toggle(s) in a RUP (Minister's Issue and Plant communities) need to be set to on (no errors in those sections) before a RUP can be handed over to an AH (submit, change requested, or recommend for submission). 

See issue #526 for something perhaps related??

**Comment by calebissharp** [comment]
Related to #413 (validation before submit/status change)

**Comment by LisaMoore1** [comment]
@micheal-w-wells If this one also covers the plant community description field then we might be good for validation part related to solution for #514

**Comment by LisaMoore1** [comment]
@micheal-w-wells This one doesn't seem to pick up if there is content missing from Plant Community Description.  
@calebissharp Is this validating for content in **all** required fields? (those identified with star on web)?

**Comment by calebissharp** [comment]
@LisaMoore1 No, but we can do the field validation at submit as well. See https://github.com/bcgov/range-web/issues/514#issuecomment-578993043

**Comment by LisaMoore1** [comment]
Save any time is the actual pressing issue right now (or if that is too big clearly identify what is needed) -- basically what  #514 was trying to capture. If we can do that and still make sure that we don't submit plans missing critical info I'd be happy. 

I know there is interplay between this (#378) and (#514). Can @micheal-w-wells and @calebissharp brainstorm the simplest way to meet the need (as described above) and adjust issues appropriately? Pull me in if there are specific priorities/options I can help settle on?

**Comment by micheal-w-wells** [comment]
@LisaMoore1  to dig in to

**Comment by LisaMoore1** [comment]
Issue and really should be resolved.  Nearest I can figure out validations are running correctly with selecting “save” but if changes are made and “submit” is made before a save function the changes aren’t lost (it is saving) but the validations don’t seem to be running.

**Comment by calebissharp** [comment]
@LisaMoore1 I've added validation before submission. This should be good to look at again.

**Comment by LisaMoore1** [comment]
RAN099962 (Provide Feedback)
- I deselected Minister’s Issue (Riparian) toggle
- I deleted the required “details” field

I was unable to save — expected
I was able to request changes without seeing any validation — unexpected

**Comment by calebissharp** [comment]
@LisaMoore1 This is ready to look at again when you get the chance.

**Comment by LisaMoore1** [comment]
@calebissharp 
- Now validating for missing fields and preventing submission where any missing (expected behaviour).  
- Still allowed submission when Minister’s Issue or plant community toggles set to off (this is not expected behaviour).

**Comment by calebissharp** [comment]
@LisaMoore1 Ready to test.

**Comment by LisaMoore1** [comment]
@calebissharp 
I’m getting a message (something like “There are one or more plant communities that have note been approved by the DM”) if I try to submit without selecting the plant community toggle — expected
I’m not getting any such message for the Minister’s Issue toggle and am being moved straight through into the he submit to AH popup screens (and can submit to AH) — not expected

**Comment by calebissharp** [comment]
@LisaMoore1 Sorry, didn't know about the minister issue toggles. Should be good to go.

**Comment by calebissharp** [comment]
@LisaMoore1 Why was this one moved back into "In Progress"?

**Comment by LisaMoore1** [comment]
Somehow managed not to post my comment. Sorry @calebissharp.  Getting a message that the toggle hasn’t been set to identified (true) even when it clearly has. 
![51614621-9094-46AE-AD80-ACD2D8C2D60C.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/cc58674e-064f-4a3c-a965-fb3741be0c53)

**Comment by calebissharp** [comment]
@LisaMoore1 There was a bug in the validation logic, but it should be fixed now.
