### ISSUE TITLE
Placeholder text for Pasture Notes needed

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#379]
Placeholder test: "Pasture specific information (i.e. not schedule, plant community or Minister's Issue specific). Ex. relevant history or topographical considerations."

**Comment by LisaMoore1** [comment]
@mccullochk @calebissharp "This is on my think it's a quick win -- pull from it if you're looking for something" list.

**Comment by calebissharp** [comment]
@LisaMoore1 Well that's a coincidence; it's already done! 😄 (https://github.com/bcgov/range-web/pull/372)

**Comment by LisaMoore1** [comment]
@calebissharp Just looked and this particular field doesn't seem to display anything.

**Comment by LisaMoore1** [comment]
@calebissharp except maybe Jenkins isn't done with it yet...

**Comment by LisaMoore1** [comment]
@calebissharp Just tested all placeholders to confirm that they save the text that is entered (to replace the placeholder) when a save is made (I tested in status 6 (SD)). 
[Pasture Notes], [Plant community description], and [community URL] are returning to blank with placeholder text showing. In addition see #382 as an unexpected behaviour that just appeared.

**Comment by LisaMoore1** [comment]
@calebissharp Just tried one in status 13 and it seemed to be OK there.

**Comment by LisaMoore1** [comment]
@calebissharp Some general weirdness as I played with it a bunch of times and now [Pasture Notes] entry has saved but Pasture description and URL keep clearing and #382 issue persists. I'll clear cache, create a clean RUP and test again.

**Comment by LisaMoore1** [comment]
Placeholders working -- plant community/save a separate issue captured elsewhere.
