### ISSUE TITLE
After save (message it saved correctly) defaulting to pre-save entries

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#382]
Noticed after placeholder update 
Testing in status 6 (SD) and 13 (SR)

- updates made to an existing field entries not being saved (reset to original text/toggle etc)

**Comment by LisaMoore1** [comment]
@calebissharp I reworded this to what I think is actually the issue.

**Comment by LisaMoore1** [comment]
@calebissharp Related to #359 that you mentioned earlier I think. I have confirmed that this is NOT tied exclusively to RUPs with missing required fields (although we should prevent this behaviour #378). There are a few fields that seem to update OK (ex. range name and plan dates) but most of plant community info is not saving. I wish I could be more specific but I keep thinking I've figured it out then I'll get a glitch in a save and what was saving before now seems not to.  Super irritating.

**Comment by calebissharp** [comment]
@LisaMoore1 This is due to the missing plant community update endpoint.

**Comment by LisaMoore1** [comment]
@calebissharp So can we do anything about this now or does it also need to wait until we get to versioning stuff where endpoints have been updated?

**Comment by calebissharp** [comment]
@LisaMoore1 Unfortunately, that's correct. Out of curiosity, what's the behaviour on the iPad when you try to update a saved plant community?

**Comment by LisaMoore1** [comment]
@calebissharp I make it look how I want, save, sync and when I get back to the web it looks the same as the updated iPad.

**Comment by LisaMoore1** [comment]
@calebissharp Size for this? I'll close once that is updated.

**Comment by calebissharp** [comment]
@LisaMoore1 Since the effort to add versioning (which is what resolved this issue) was captured in other issues, is it alright if we leave this without a size? This issue was never really worked on explicitly.

**Comment by LisaMoore1** [comment]
@calebissharp Works for me.
