### ISSUE TITLE
Make plant communities readonly after being saved

### ISSUE THREAD

**Issue by calebissharp** [bcgov/range-web#383]
This is a temporary solution until we merge #368 and https://github.com/bcgov/range-api/pull/77, which lets us edit plant communities

There should also be a message to range officers that provides some more information, to minimize confusion.

**Comment by LisaMoore1** [comment]
@calebissharp As discovered on Friday, iPad updates work for staff draft status (6) but not submitted for review (13).  Maybe message should be something like. 

Message: Don't worry, this is only temporary. If this is a staff draft you can make and save updates on the iPad. If it is not a staff draft contact myrangebc@gov.bc.ca for a manual fix.

Other than that, seems to be working as expected. Thanks for keeping at this one.

**Comment by LisaMoore1** [comment]
@calebissharp This looks good. I haven't done a whole slew of tests on any related workflows...but the  text looks good and I think we're good to go @micheal-w-wells
