### ISSUE TITLE
Unable to load RUPS in dev and test for any range officer user

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#393]

**Comment by micheal-w-wells** [comment]
`insert into plan_version (version, canonical_id, plan_id)
select -1, canonical_id, id from plan`

Need to run this for plans created prior to versioning code changes.

flagging as medium based on time to resolve.

**Comment by LisaMoore1** [comment]
@micheal-w-wells Did this actually take medium effort or was it closed because it was dealt with elsewhere? If it actually was medium effort can you update the estimate to 5? Thx
