### ISSUE TITLE
Create file upload UI

### ISSUE THREAD

**Issue by mccullochk** [bcgov/range-web#403]
- [x] Add another section below `Management Considerations`
- [x] In the main page it will look similar to other sections with a title, an `Add attachment` button and then below the header there will just be a list of the current attachments with `name`,  `upload date`, and `uploaded by`
- [x] When the `Add attachment` button is clicked a file modal appears and allows the user to navigate to the desired attachment, when they click okay it appears in the list.
- [x] Beside the item there will be the ellipsis symbol which gives the option to delete the attachment.

\* Requires https://github.com/bcgov/range-api/issues/102

**Comment by mccullochk** [comment]
@LisaMoore1, are there specific RUP statuses that will restrict the attachment functionality. Eg. if it's submitted a user can no longer attach or remove PDFs?

**Comment by LisaMoore1** [comment]
@mccullochk I think the best starting point would be that an attachment is identified as either (a) staff added or (b) AH added. Staff can only delete ones in category (a) and agreement holder in category (b). 

Adding/deleting attachments should only be in the statuses that currently allow editing. Attached image shows (in orange) who is able to edit in each status. ![800BED18-F2EC-4221-8E2A-9C57BDF70B9E.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/a47e1b38-3a37-4f1a-86ba-968c61cdb321)

**Comment by mccullochk** [comment]
Great. Thanks for the feedback!

**Comment by mccullochk** [comment]
We need the backend to be hooked up before we can fully test this.
