### ISSUE TITLE
Total AUMs in schedule is calculating ALL AUMs rather than only Crown AUMs 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#404]
Crown AUMs = AUM calculation minus the PLD %![76D8B3B5-A913-4D2B-A8BA-D70AD2C46DAD.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/a6d3a60d-978f-4012-8143-9c27a778f9ab)

**Comment by LisaMoore1** [comment]
@micheal-w-wells Can you check with Caleb and Kaileen and see which can take a look at this.

**Comment by LisaMoore1** [comment]
@calebissharp Has Jenkins done it's thing related to this issue so I can test?

**Comment by calebissharp** [comment]
@LisaMoore1 Not yet, give it another 20 minutes.
