### ISSUE TITLE
[PDF] Pasture name in grazing schedule row not wrapping

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#411]

**Comment by calebissharp** [comment]
@micheal-w-wells Can I have an example please?

**Comment by micheal-w-wells** [comment]
Sorry @calebissharp missed this notification.  We'll dig up one for ya.

**Comment by micheal-w-wells** [comment]
Here's a long one for ya 'Tatelkuz Mountain and Grizzly Valley grass-shrub meadows'

**Comment by calebissharp** [comment]
@micheal-w-wells What does it look like in the PDF?

**Comment by micheal-w-wells** [comment]
@LisaMoore1 can you give example of one with issue?  I tried RAN075154 with the long pasture name above and it looks pretty good.

**Comment by LisaMoore1** [comment]
@micheal-w-wells here is one without a hyphen but overlaps.  ![IMG_7382.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/d32417d2-98f3-4a43-a53e-bee098cca851)

**Comment by calebissharp** [comment]
@LisaMoore1 Oh, so the problem is pasture names in the schedule rows, not in the pasture section?

**Comment by LisaMoore1** [comment]
@calebissharp In this case yes.  There are other places where the issue is more about wrapping (see #491)

**Comment by calebissharp** [comment]
@LisaMoore1 That other issue doesn't relate to the PDF rendering at all though, correct?

**Comment by LisaMoore1** [comment]
@LisaMoore1 Correct -- it is plan not PDF
