### ISSUE TITLE
Staff should be prevented from submitting a RUP to AH if there are no pastures included in the plan. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#413]
Staff should be prevented from submitting a RUP to AH (either to 1-C, to 5-R, 19-RFS or to 10-NF) if there are no pastures included in the plan.

I generated a fun set of errors by deleting all of the pastures out of a RUP that had schedule entries and then submitting it back to the AH. Took me awhile to figure out how to get out of the error loop.

**Comment by calebissharp** [comment]
@LisaMoore1 I'm wondering if this will really help solve the problem. If a range officer deletes a pasture, it will also delete the schedule entries for that pasture. And if all of the entries are deleted, the RUP won't be able to be saved. This won't be fixable, as range officers can't add grazing schedule entries.

**Comment by micheal-w-wells** [comment]
@jleach it looks like repo-mountie thinks you are bored

**Comment by micheal-w-wells** [comment]
My vote is to let RO CRUD schedule entries, which would make it ok to block submitting the ones without entries and not put RO in a situation that they can't fix.

**Comment by LisaMoore1** [comment]
There are some legal considerations of having staff fully able to change schedules.  I think we are good as long as we block them from doing it in certain statuses (basically anything that is after the confirmation process has begun) so CRUD schedule OK in 6, 13 and possibly 10 (I need to know if 10 persists after AH starts work on the draft. That's an unusual circumstance so lets leave that for now). If we also had a "recall" option that lets staff move it back to 6 (staff draft) if status is 1 (created but AH hasn't started work yet) it would reduce a lot of pain. 

Everyone OK with staff CRUD schedule in 6 and 13? Recall option from 1 to 6 would be a separate enhancement. 
@micheal-w-wells @calebissharp

**Comment by calebissharp** [comment]
@LisaMoore1 Is this resolved by #432 then?
