### ISSUE TITLE
"Save draft" is periodically adding another cop of a schedule for the year being worked on -- a copy for every time you select "save draft"

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#415]
Seems to do it when there is a save error message being generated 
There should never be more than one schedule for any given year

**Comment by LisaMoore1** [comment]
@calebissharp I remember typing something about this but don't think it ever got its own issue so made one now. If it is a duplicate or already addressed feel free to close it.

**Comment by calebissharp** [comment]
@LisaMoore1 Fairly certain this has already been fixed. Closing for now. Will reopen if the bug is reproduced.
