### ISSUE TITLE
PDF title page should include "Plan Term" above the dates and dates should reference plan term rather than agreement term

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#416]

**Comment by LisaMoore1** [comment]
@micheal-w-wells This is the one we talked about today -- thought I'd make the issue. Put it in backlog with the idea that it could be a pull into an upcoming sprint as a quick win. If you've already created an issue and my December brain just wasn't finding it please feel free to identify it as a duplicate and delete/close this one.

**Comment by LisaMoore1** [comment]
@micheal.w.wells Not seeing this on PDF in test (ex. RAN099953). Am I missing something?

**Comment by calebissharp** [comment]
@LisaMoore1 I'm able to see it in the header. Perhaps you have to clear the cache? (or were maybe looking at an older PDF you had downloaded).

This is what I see: [Range Use Plan - RAN099953.pdf](https://github.com/bcgov/range-web/files/4066885/Range.Use.Plan.-.RAN099953.pdf)

**Comment by micheal-w-wells** [comment]
@LisaMoore1 It seems I only changed it in the actual header on pages besides the front page, I think what you're saying here is you don't see it on the front page.  My bad.  Should be a quick fix from here - stand by.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 tested this one myself in TEST and unfortunately it requires fresh cookies.
