### ISSUE TITLE
"Authorized AUMs" at bottom of schedule should be displaying "total Annual" (from usage) and relabeled "Annual Auth AUMs"

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#417]

**Comment by micheal-w-wells** [comment]
help

**Comment by LisaMoore1** [comment]
@Micheal.w.wells Is there a RAN I can look at where you know there is either a non-use of temp increase entry for usage so I can check that the right thing is displaying?

**Comment by LisaMoore1** [comment]
@micheal.w.wells In metabase I’m not seeing any 09 RANs with temporary increase or non-use. Would you update the usage for a RAN09 assigned to me and then let me know so I can test this one? Label looks good. Thx

**Comment by LisaMoore1** [comment]
@Micheal-w-wells I see that my previous mention didn’t work (iPad doesn’t help out with these).  Any RAN suggestions for testing this?

**Comment by micheal-w-wells** [comment]
I'll look right now.

**Comment by micheal-w-wells** [comment]
@LisaMoore1  RAN099912

**Comment by LisaMoore1** [comment]
@micheal-w-wells in order to completely test this one I need a RAN that has either non-use or temporary increase such that annual AUMs is different than authorized AUMs (so I can confirm that is what is displaying.  Ideas for a RAN like that?

**Comment by LisaMoore1** [comment]
@micheal-w-wells I can’t finish testing on this until I can add a schedule to RAN073465 See issue #482 added this morning.

**Comment by LisaMoore1** [comment]
@micheal-w-wells Not picking up the value from usage. See image. [Uploading... IMG_7359.jpeg ]

**Comment by micheal-w-wells** [comment]
Hey @LisaMoore1 , unfortunately the image didn't upload.  I'll tell ya what I did though, I looked at the usage that comes over from FTA which is as so:
"
            "forest_file_id": "RAN073465",
            "calendar_year": 2020,
            "authorized_use": 1608,
            "non_use_nonbillable": 500,
            "non_use_billable": 250,
            "temp_increase": 0,
--
            "forest_file_id": "RAN073465",
            "calendar_year": 2021,
            "authorized_use": 1608,
            "non_use_nonbillable": 500,
            "non_use_billable": 0,
            "temp_increase": 0,
"

But i can't see the anything in the schedule as it wasn't saved.  Can you save this one?  I'll go on to try and replicate it myself.

**Comment by micheal-w-wells** [comment]
its there now i can see it

**Comment by LisaMoore1** [comment]
@micheal-w-wells Fixed the image. That work or do you still want me to make a schedule and save? I’m on RANs in test conservation mode so I keep several to run end to end.

**Comment by micheal-w-wells** [comment]
Fixed & deploying, give it 15-20.
