### ISSUE TITLE
Change manage clients to use new active_client_accounts table

### ISSUE THREAD

**Issue by calebissharp** [bcgov/range-web#418]
Client entries with the same client number but different location codes should be merged into 1 entry in the dropdown, since the database only references the client number and the location code is ignored.

**Comment by LisaMoore1** [comment]
@calebissharp We should talk about this one.  I don’t think this moving forward with this would put us in a place we want to be. Perhaps it is because I don’t know the background of what you and @micheal-w-wells discussed re. clients but this feels like a potential wrong turn we should check before proceeding.

**Comment by calebissharp** [comment]
@LisaMoore1 The way I understand it is that while each client number/location code combination is a separate *client*, with its own RANs, a single user_account (ie. real person) would be representing all these combinations. For that reason, it makes sense to show in the UI linking a user account to a client number, which implicitly will link that user to all location codes as well.

**Comment by LisaMoore1** [comment]
@calebissharp So a person logs in with their BCeID which links them to their client# (no location) which then allows them to see all of their RUPs (which themselves are related to the location codes so that the right people get displayed) (I need to play in metabase to get my head around this a bit). 
I think it makes sense but there was some reason why staff wanted to CLIENT#+locn to be linked to the BCeID not just the CLIENT#.  I’m thinking maybe this is something I run past our new SME group to see if they can come up with a scenario where you need the BCeID to be tied to the locn as well.

**Comment by micheal-w-wells** [comment]
The issue right now is that each client + loc is has a unique id in ref_client, which is good, but only of those ids can on user_account, which is bad.  

I think the right thing for us to do here is allow for an arbitrary number of client and or location codes for each user.  If staff/clients want things more segregated they can get another BCEID.  There's already a few staff who are concerned that their clients, who have multiple locations and even multiple client numbers, won't be able to see all their RUPs.

What we need is a user_account_client_links table.  user_id, and client_id as columns.   Linking populates this table, and RAN fetching will piggy back off this relationship and everybody can see what they want.  The manage clients drop down should display unique client numbers, (not locations) and it should show bcied usernames in addition to names.  Maybe we change it to be check boxes for when we want to link a few client records to one user to be a bit more user friendly.

@LisaMoore1 @calebissharp you guys see any holes in this game plan?

**Comment by LisaMoore1** [comment]
@micheal-w-wells I don’t see any well defined holes. I think if we consider the various agency agreement options we will arrive at a solution that works.  Bottom line: 

- we need the right people to see the right agreements
- the three factors that come into play identifying who sees what are client number, location code and agent
- agent could be for a client number, #+locn, a RAN or multiples of any of those 
- agents may or may not have a client# (most ranch managers do not)
- we need to differentiate between who is an agreement holder and who is an agent
- agency agreement information details (term etc) is related 

I know we haven’t really tackled agency agreements full on but I think (although I could be wrong) that we need to consider agency before we decide how to move forward here. It feels to me like are at a point where we can either make it easier or harder for ourselves moving forward.

**Comment by calebissharp** [comment]
Can we just add a `user_id` column to `ref_client`? This allows multiple client records to be attached to the same user account.

**Comment by micheal-w-wells** [comment]
That's a bright idea, but if we're hacking this stuff let's make it work for agency agreements too.  I'm assuming we want the RUP viewable for both the signee and the main person (what do you call them?).  

I think we want a table with:
user_id, client_id, type, where type is 'owner' or 'agent'

**Comment by calebissharp** [comment]
@micheal-w-wells You're right, having a separate table will (hopefully) help decouple these two concepts. Maybe `active_client_accounts` for the table name?

**Comment by LisaMoore1** [comment]
In an agency situation both the AH and the person they authorize as agent to sign should have full access/signing options so long as that agency agreement is in place. 

It is like adding access for another AH that doesn’t have their own “signature row” but if they do sign they are signing on behalf of an AH that does require a signature. If an agent signs we need to be able to identify that it was the agent that signed not the AH.

**Comment by micheal-w-wells** [comment]
Changing name of issue as there is no PR against it and this is the new goal.

**Comment by LisaMoore1** [comment]
@calebissharp I like this new layout a lot! I couldn’t create any issues with it. I was slightly confused by the message I get if I try to connect another Client that is already linked to a user. 

“Error linking client: User “Leslie Knope” is already linked to the selected client.” 
- to me that means that if I try to connect her to Andy Dwyer and get this message she is already connected to Andy Dwyer — which would make sense when I try to add Andy Dwyer again
- I think this message appears when you select someone from the list that is already connected to someone (either the current first dropdown selection or someone else)
- can the language be changed to “...is already linked to a client.” ?

Re. Persistence of the message
- the error message stays visible below the field after you’ve cleared the field and selected a new person —> all the way until you select “add link” (was confusing)
- ideally the error message disappear as soon as the content of the second drop down is cleared or changed

Changing this back to In Progress for the update to the text on the message (and if not too huge persistence). If the persistence is big please create another issue for it. Thanks.

**Comment by calebissharp** [comment]
@LisaMoore1 That's the error that appears when you try to link a client (second dropdown) to a user (first dropdown), but that client has already been linked to another user than the one you are managing client links for. Maybe it makes more sense to flip the error around, eg. "Cannot link client to this user because it is already linked to another user (Leslie Knope)".

I'll create another issue for the error persistence.

**Comment by calebissharp** [comment]
See #742

**Comment by LisaMoore1** [comment]
@calebissharp Sounds like a good plan. Thx.

**Comment by micheal-w-wells** [comment]
I gotta check that the fta synch still works here

**Comment by LisaMoore1** [comment]
I’m happy with the new error message. @micheal-w-wells when you are happy with the FTA synch can you please either close or let me know and I’ll do it? Thanks.
