### ISSUE TITLE
Delete option for readiness/stubble height indicator plants disappears after save/exit plan to work queue and return to plan

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#444]
Readiness/stubble height indicator plants entered —> plan saved —> go to work queue —> return to RUP —> delete indicator plant option no longer available

**Comment by calebissharp** [comment]
This is leftover from when we didn't have an endpoint to edit indicator plants.

**Comment by LisaMoore1** [comment]
@calebissharp I think this is fixed but I’d like to wait until the new issue re. Indicator plants saving is fixed to be sure (#457)
