### ISSUE TITLE
Schedule description needs “Schedule description is optional but if included is legal content”

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#445]
See message from iPad — I couldn’t get in but I think it is something like what’s above.
Message could go either by the label or under the field.

**Comment by calebissharp** [comment]
Sorry @LisaMoore1, I don't have access to the iPad. Can you upload a screenshot please?

**Comment by LisaMoore1** [comment]
@Calebissharp Text is "Schedule description is not required but if completed is legal content."

**Comment by calebissharp** [comment]
Alright, thanks.

**Comment by LisaMoore1** [comment]
@calebissharp Good in plan — needed in the PDF as well.  Do I need to make a separate issue for that?

**Comment by calebissharp** [comment]
@LisaMoore1 Is it not already in the PDF?

**Comment by LisaMoore1** [comment]
@calebissharp I thought so but nope. ![IMG_7363.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/67572770-cd0e-4421-94d0-d6ace8136981)

**Comment by calebissharp** [comment]
@LisaMoore1 Should be in the pdf now.
