### ISSUE TITLE
Staff adding Management Consideration can add, select concern/opportunity (thus creating an entry) but then unable to add “details”

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#447]
Make details field editable by staff.

**Comment by calebissharp** [comment]
@LisaMoore1 Does that mean this editable field document is inaccurate?

![image](https://user-images.githubusercontent.com/8854811/72270837-a116f380-35da-11ea-88c9-0f9ffc60c54b.png)

**Comment by LisaMoore1** [comment]
@calebissharp If we are making all content editable on web (like it is on iPad for staff to help AH) then it needs to be editable by staff (like all sorts of other things that show AH on the table you reference but are available for staff CRUD). AHs ONLY get what says Agreement Holder.

**Comment by calebissharp** [comment]
@LisaMoore1 So staff should be able to edit everything?

**Comment by LisaMoore1** [comment]
@calebissharp Yes -- definitely in staff draft status.  I couldn't test what those were looking like as I couldn't submit as an agreement holder. We're basically there.

**Comment by calebissharp** [comment]
@LisaMoore1 Ok, that's good to know.
