### ISSUE TITLE
If grace day of 1 removed resulting in no entry, the schedule rows should show “0”

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#448]
0 displays on schedule rows any time there isn’t a value for the field or a 0 was entered

**Comment by LisaMoore1** [comment]
@calebissharp Grace Days in schedule rows is not populating a default from the grace days entry for that pasture.

**Comment by LisaMoore1** [comment]
@calebissharp Default value coming over but when I delete whatever value is there I'm left with a blank field. Blank field should render as 0 (plan and PDF).

**Comment by LisaMoore1** [comment]
@calebissharp Working in plan. PDF schedule is not updating to show the overwritten value from the schedule row.  PDF should match exactly what is entered in plan.

**Comment by LisaMoore1** [comment]
@calebissharp This still shows unresolved but I see there is merge yesterday. Is something I can test now?

**Comment by calebissharp** [comment]
@LisaMoore1 Yes, sorry. This labelling system can be hard to keep track of sometimes.
