### ISSUE TITLE
Indicator plants for range readiness - stubble height added in staff draft not saving after save draft

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#457]
RAN09993 (staff draft) — indicator plants for both range readiness and stubble height can be added but not saving when “Save draft” selected (disappearing from the plan after save)

**Comment by LisaMoore1** [comment]
@calebissharp — didn’t notice this happening before the fix to the delete option problems related to indicator plants (could be something I missed but entirely possible)

**Comment by calebissharp** [comment]
@LisaMoore1 I can't reproduce this locally or in test.

**Comment by LisaMoore1** [comment]
@calebissharp — still happening consistently for me. Looks good post save until I scroll the screen at all —> opens different pastures —> I reopen where I made changes —> changes gone.

**Comment by calebissharp** [comment]
@LisaMoore1 Can you try again, now that we've fixed some deploy problems?

**Comment by LisaMoore1** [comment]
@calebissharp Still not saving.

**Comment by calebissharp** [comment]
@LisaMoore1 Are those plans with the funky amendment duplication versioning?

**Comment by LisaMoore1** [comment]
@calebissharp — they are new staff drafts. I tried RAN099956 (created since the the versioning merge) and it does the same thing.

**Comment by LisaMoore1** [comment]
@calebissharp Just realized it isn’t deleting either.  Looks good until I hit save draft and then as soon as I navigate at all on page it reverts to pre_edited version.  This feels familiar.

**Comment by calebissharp** [comment]
I made a screen recording of what I see: https://send.twostoryrobot.com/download/6cd570b79f735654/#0iOeO7TL48A9jyX9Vlw8Jg

Let me know what you may be doing differently that is causing the indicator plants to save improperly.

**Comment by micheal-w-wells** [comment]
Bad 🍪?

**Comment by calebissharp** [comment]
I think it's an internet connection issue, where the plan is being re-fetched before the delete requests go through. I've created #480 to address this.

**Comment by LisaMoore1** [comment]
@calebissharp I’ll be in the office tomorrow with faster speed.  I’ll test it there in the morning.  Pretty sure it isn’t the cookies since I’ve cleared the cache twice thinking that might be what it is.

**Comment by LisaMoore1** [comment]
@calebissharp Just did this on my desktop computer with same result as in video I posted on slack — both adding and removing indicator species not sticking after Save Draft

**Comment by calebissharp** [comment]
@LisaMoore1 May I ask which browser you're using?

**Comment by micheal-w-wells** [comment]
Mine save ok when i update stubble height but delete isn't sticking on chrome

**Comment by LisaMoore1** [comment]
@calebissharp 
Chrome (desktop): save is working on chrome but delete is not
Safari (iPad): neither save nor delete are working (even waiting awhile on fast connection to  allow update)

I’m going to clear cache on chrome on my iPad and see what happens there.

**Comment by LisaMoore1** [comment]
@calebissharp @micheal-w-wells. Make my last comment regarding getting navigated away a sometimes because I just tried it again on both chrome and safari to record it but I didn’t get punted to a different pasture. So yay! Or not if it happens again and it is just an I can’t reproduce it problem.

**Comment by LisaMoore1** [comment]
@calebissharp Testing this morning: 
RAN099913 and RAN099914 (plans started in iPad) --> both desktop and iPad = unexpected behaviour on save/delete indicator plants
RAN076831, 3465 and 3636 (plans started from web) --> save and delete of indicator plans working as expected

Perhaps that will help troubleshoot a bit...

**Comment by micheal-w-wells** [comment]
@LisaMoore1 mind if i steal one of RAN099913 or RAN099914 and try to reproduce (but not save) ?

**Comment by LisaMoore1** [comment]
@micheal-w-wells Go ahead.  All good.

**Comment by calebissharp** [comment]
@LisaMoore1 Can you give this another try?
