### ISSUE TITLE
Current legal version is not easily identifiable in work queue when there are approved/stands amendments

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#464]
“Current Legal Version” = the most recent approved or stands (and kind of stands) plan

Old methods was to have a star by the current legal (that is not happening)
New method (I think) involves only showing the current legal version in the work queue and others accessible for view only from the versions option in the 3 dot menu

**Comment by calebissharp** [comment]
Related to https://github.com/bcgov/range-api/issues/108

**Comment by micheal-w-wells** [comment]
@okanji very related to what you are doing with the homescreen preview

remember that we want to see:

The work in progress  or last not approved plan
The current and past legal versions

**Comment by LisaMoore1** [comment]
See #800.  Not sure if they are separate or the same. Will move this to In progress as well.  Feel free to close one of them if both aren’t needed.  

See comments at lower right on this image. 
![IMG_8047.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/72c01134-c04c-41de-80f9-e75e3d7693f0)
