### ISSUE TITLE
Initial view staff work queue is not showing the most recent “status” therefore would be easy to miss that action is required

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#465]
Where there is an approved version and an amendment requiring action (say mandatory requiring feedback) the unexpanded work queue row is showing the status from the top of the list (I think — not sure where it is pulling from) rather than the most recent status (ex. “Feedback required”) 

Fix by showing the most recent status on the unexpanded work queue row.

**Comment by calebissharp** [comment]
Related to https://github.com/bcgov/range-api/issues/108

**Comment by calebissharp** [comment]
Should be fixed implicitly by JSON snapshots.

**Comment by LisaMoore1** [comment]
Based on the agreements I have to test with this seems to be resolved. Am closing.
