### ISSUE TITLE
When staff successfully change status of a plan they should be returned to work queue immediately

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#466]
Changing the status is the end of that workflow so should move you off of the plan
Would reduce the desire to try to update the plan status again (looks like you should be able to do something as the version you see hasn’t been refreshed to show the status has been updated)

**Comment by calebissharp** [comment]
@LisaMoore1 I'm going to push back on this one. I think the preferable UX is to have a spinner displayed while the status is being updated, and not remove it until the plan has been refreshed and is showing the correct status. It would be jarring to send the user back to the work queue, as that would give them no indication the status successfully updated, especially if they had a lot of agreements.

**Comment by LisaMoore1** [comment]
@calebissharp I agree with the jarring part. I’d be happy with a spinner provided that once the spinner is done I’m left looking at a plan where the header information indicates the correct status (assuming that is what you mean but plan is refreshed) and I’ve got appropriate plan actions. Same likely applies to #469)

**Comment by LisaMoore1** [comment]
@calebissharp This looks good. Can you also please size then close this one? Thanks.
