### ISSUE TITLE
Unable to tell that an amendment is in progress of being created (it takes some time) so tempting to click buttons to try to do something

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#468]
Grey the screen (like when save in progress) or provide a popup that amendment creation is in progress — anything to indicate that it is in progress

**Comment by LisaMoore1** [comment]
@calebissharp — What should I be seeing here? When my connection is good no problem but when it is a little slow I still get the urge to click again as I’m not seeing anything indicating a function is in progress.  Do I need to install more patience or should I actually be seeing something?

**Comment by calebissharp** [comment]
@LisaMoore1 You're right, there is no loading indicator. This may be regressed behaviour.

**Comment by LisaMoore1** [comment]
@calebissharp Precursor that I’m struggling with connection speed today but remembering that that might be a common thing for our users. 
 I had an interesting thing happen today. I started a new amendment on a plan that already had an original and amendment made sincand the spinning wheel went around and around so I used browser back button to get out e versioning implemented. I tried again and kept spinning for over two minutes so back buttoned again.  Two new versions were created. Also not sure what to make of those two new version immediately having a status of stands-wrongly made (the status of the amended plan I built them off of) rather than a draft status indicating they were incomplete.  As is they looks like they’ve been through the whole process.  I’ll create an issue for that bit when I do all of the amendment related issue refinements. 


  ![IMG_7820.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/f0ccf553-6740-4d80-8651-a8a8e2777bfa)

**Comment by LisaMoore1** [comment]
@calebissharp So I guess the bottom line is I don’t know if the button was working or not working and if what I experienced was unexpected because of connection or if there is another issue — so I’m leaving it open for now.

**Comment by calebissharp** [comment]
@LisaMoore1 I think the problem that was creating duplicate versions was unrelated. Do you think this is alright to close?

**Comment by LisaMoore1** [comment]
@calebissharp I’ll close and if it who’s up again as a problem we can either reopen or create another one.
