### ISSUE TITLE
Need to address statuses/workflow for “stands - not reviewed” vs. “stands-reviewed” statuses

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#472]
Need to have a conversation on this one to describe the details — see the workflows and previously provided amendment information

**Comment by micheal-w-wells** [comment]
@LisaMoore1 or @calebissharp if I were to test what am I looking for?

**Comment by LisaMoore1** [comment]
@calebissharp I’m not sure if this is same issue or should be added as a separate one (feel free to do that if that makes more sense to you)

I like this process although the options visible staff need to be:
   - stands
   - stands-wrongly made
   - wrongly made - without effect (add this one — selecting it reverts the plan back to the previous legal version...which needs to be CLEARLY identified)

Eventually the workflow will go:
Staff have options 
   - review not required —> stands status remains
   - review required —> gets pushed to DM (with recommendation from staff) 

DM makes decision between
   - stands
   - stands-wrongly made
   - wrongly made - without effect
Remember that every decision the DM makes will need to include the option to include conditions.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 should there be another option for staff to fire it back to AH to fix an obvious typo/error?  I feel like DM will be going through a lot of mistakes staff could have caught?

Just so @ZoeSimon and I know what we are supposed to test, can we spell out:

1. Description of problem/solution
2. What are steps to test 
3. Expected result

**Comment by LisaMoore1** [comment]
@micheal-w-wells In this case there should not be an option to send back to AH.  With minor amendments they make them, they become legal, staff look to see if DM should review, if so staff make a recommendation based on the three options.  There is a fourth one that is “submit as a mandatory amendment” — not sure exactly the best spot to fit that one in. Will try to figure out today if staff can do that or if legally it has to come from DM — I’m thinking DM but I’ll confirm.  I really have no idea how to describe what to test on this. I only know when I try it and something feels weird or missing. Therein lies my problem. I have to do it to know what to test/expect — and by doing that I’ve just tested. When I was less swamped I was recording the workflows in an excel worksheet — which takes twice as long as doing the testing and as soon as there is a change (like the versioning thing) I have to rewrite a big chunk of all of them. It’s a problem for me. 
If we could get the test agreements for the fake BCeIDs set up for the list of testers I provided that would be really helpful. Several of them have enough experience to know what options they should be expecting and to ask good questions.

**Comment by LisaMoore1** [comment]
@calebissharp I’m unable to test. See #770

**Comment by LisaMoore1** [comment]
@calebissharp the workflow/statuses seem to be working but there are still some trickies in version (see $704). I’m closing this one.
