### ISSUE TITLE
Staff unable to Add schedule in newly created plan

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#482]
Option is greyed out. Essential staff can add schedules here. I think function works just not accessible here for some reason. For now staff should be able to edit schedule for any status they can enter anything (6 and 13 I think)

**Comment by LisaMoore1** [comment]
@calebissharp “Add Schedule” appears if I exit the plan to work queue and then return

**Comment by calebissharp** [comment]
Yep, I've figured it out. Fix should be deployed soon.
