### ISSUE TITLE
Need to identify that red schedule error when single decimal schedule total = annual authorized is because of a fractional AUM

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#487]
Total schedule AUMs must not exceed annual allowable by even a fractional AUM
AUMs are displayed in field with one decimal point (10th)
Because of rounding the numbers may look like the total schedule AUM = annual authorized but it may be over by an "invisible" 100th so generating a confusing red field
There is no way for user to KNOW that schedule actually DOES exceed annual authorized

Need way to clarify that. Possibilities:
- messaging?
- more decimal points on hover?

**Comment by LisaMoore1** [comment]
Lisa to ask SMEs about this. Perhaps more accurate solution is to have total schedule AUMs show with one decimal point (preferably only if schedule AUMs exceed annual authorized) so that it doesn’t show the same number as the annual authorized but create a validation error.

**Comment by calebissharp** [comment]
@LisaMoore1 I'm not sure I understand this one. 

Are you saying that the total AUMs value should be rounded? (So it should show 300 instead of 300.2 in this screenshot). And validation would be run against the rounded value?
![image](https://user-images.githubusercontent.com/8854811/73096587-018b1800-3e9a-11ea-896d-1e3c178890f7.png)

**Comment by LisaMoore1** [comment]
As noted in my comment yesterday I need to check with SMEs on this one so leave for now.  I’ll move it down priority list. There are legal implications regardless of what staff want. Not something that is going to come up in majority of schedules so we’re OK leaving for now.
