### ISSUE TITLE
Staff are prevented from saving or submitting a plan that has content in schedule description for one or more years but no rows in the schedule(s)

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#488]
Messaging regarding rows being required is important
This work flow was not previously considered 

Recommend: 
- leave messaging on screen
- allow submission

Possibility:
- require confirmation that staff DO want to submit a schedule that does not have any rows (would need exact language — ex. This plan includes schedules that do not have associated rows. Do you wish to submit to AH? Cancel/Yes)

**Comment by calebissharp** [comment]
@LisaMoore1 Are there any scenarios where there *must* be rows in the schedule before submitting, even with a schedule description? As well, do we want to let users save drafts with rowless schedules? Or is this strictly for submit/status change?

**Comment by LisaMoore1** [comment]
@calebissharp In all cases, we should  allow drafts with no schedule rows to be saved. 
Regarding validations relating to rows:
Staff: ability to save and submit schedules to agreement holders that may or may not have schedule rows (but a warning/notice with option to cancel out when a submit to AH action initiated would be helpful)
Agreement Holders: ability to _save_ a draft of a plan having schedules without rows but plans _submitted_ by agreement holders to staff MUST have at least one row.

**Comment by calebissharp** [comment]
@LisaMoore1 Ok, thanks. So to reiterate, to make sure I've got everything:
- Staff
  - **Can** submit without schedule rows, but get a warning
- Agreement holders
  - **Cannot** submit without schedule rows
- Both
  - **Can** save draft without schedule rows

**Comment by LisaMoore1** [comment]
@calebissharp You've got it.

**Comment by calebissharp** [comment]
@LisaMoore1 Adding that confirmation will add another 0.5 to the estimate. Is that something you'd want to go ahead with?

**Comment by LisaMoore1** [comment]
@calebissharp Yes you can go ahead on this

**Comment by LisaMoore1** [comment]
@calebissharp 
AH: expected behaviour (can save but not submit)
Staff expected -- can save
Staff unexpected -- no warning that one more schedule may not have rows, do you still wish to submit.

**Comment by calebissharp** [comment]
@LisaMoore1 Sorry, missed your message to add the confirm dialog.

**Comment by calebissharp** [comment]
Going to wait though until we figure out #514.

**Comment by micheal-w-wells** [comment]
@calebissharp can we have a 'isblank. schedule' var that we look at in the yup schema rule and not error if that's the case?

**Comment by calebissharp** [comment]
@micheal-w-wells I'm not sure I follow. The validation logic is alright here, it's the confirm dialog that we're missing. 

@LisaMoore1 Coming back to this issue though, I've realized a couple of things. First, we have many different ways of presenting errors to the user, through field errors, a toast notification, scrolling to some errors, showing errors for entire blocks of fields, and displaying a special toast notification for some errors. The way in which an error will manifest itself is IMO quite unpredictable. I think there should be some discussion about the UI here.

**Comment by micheal-w-wells** [comment]
Do we have any short term plans to address how error messages happen other than this one or should we move forward with this one? @calebissharp @LisaMoore1

**Comment by LisaMoore1** [comment]
@micheal-w-wells I don’t think we’ve got an immediate plan in terms of handling errors. 
@calebissharp As for the ability to submit the schedule with no rows but with a narrative — I just ran the workflow between staff and AH. I think it’s workable without the confirmation (could be an enhancement) but not essential) since the AH can immediately see that schedule rows are required.

**Comment by calebissharp** [comment]
@LisaMoore1 I agree, I think the confirmation is fairly non-critical. Maybe we can open another issue so we can close this one? I just don't want to miss that we were able to resolve most of this issue.

**Comment by LisaMoore1** [comment]
I’m closing this one without creating a confirmation screen. If it comes up from a user then we can add an issue then.
