### ISSUE TITLE
Unable to sort the rows in the schedule in web (and want the selected order to carry through into PDF)

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#489]
Sort order can make a big difference for readability of a schedule.  Depending on the schedule different sort orders are preferable. 
Staff have requested that sort options (first this then that) exist for the schedule on web and the PDF display the sort options as identified 
I suggest dealing with sort order in the plan first (should stay to what you’ve set it next time you open it) and deal with the PDF as a secondary (lower priority) thing

**Comment by LisaMoore1** [comment]
Sort options: 

- [ ] by pasture
- [ ] by livestock type
- [ ] by number
- [ ] by date in

**Comment by calebissharp** [comment]
@LisaMoore1 Is the sort by livestock type and pasture, alphabetical? (based on the name)

**Comment by LisaMoore1** [comment]
@calebissharp  Yes

**Comment by LisaMoore1** [comment]
@calebissharp Love this! Two things:
- pasture sort doesn’t seem to be working
- there is no indicator that this function is available —> message? An arrow beside the title before you do a sort (one appears after indicating you can sort it the other direction but maybe a down arrow to start?)

**Comment by LisaMoore1** [comment]
@calebissharp Actually, it might be how you intended but I’m not sure. I see in a schedule with a bunch of rows that something does happen when I select pasture it does do something but I’m not sure what it is doing. Order they were entered into the scheduled? Order the pastures were entered into the plan? 

Should be pastures alphabetically here. Ideally with a “reset order” button that takes it back to how the rows were originally entered.

**Comment by calebissharp** [comment]
@LisaMoore1 It should sort it alphabetically, and then by order created (otherwise if there's only a few pastures but many rows the sort would be strange.)

**Comment by LisaMoore1** [comment]
@calebissharp If I scramble up the rows I can get it to return to order entered but I can’t get it to do alphabetical. Selecting it again doesn’t produce any change.
