### ISSUE TITLE
Difficulty reading text in plans that have returned to staff from AHs (ex. 13) as text is single line or cut off

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#491]
**Noted in following areas**
- [ ] schedule  (pastures and description)
- [ ] pasture notes(no image)
- [ ]  schedule description
- [ ]  plant community description
- [ ]  Invasive plant “other”
- [ ] management considerations "Details"

Images to demonstrate here:

Schedule pasture and Description
![image009.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/acb1fb50-95ec-4805-b32f-ceddd9885fc9)

Plant Community
![image010.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/c673fe26-65bd-4643-ba4c-67f967cf280d)

Invasive Plants
![image011.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/6d3e09c4-1b0f-4b84-b903-befcef5af100)

**Comment by LisaMoore1** [comment]
@Calebissharp I found some more while testing the heck out of other stuff and thinking about this one. 
Minister's Issue: Objective
Additional Requirements: Details
Management Considerations: Details
Plant Community Actions: Detail 

Pasture Notes is a little different. It looks good in "view" statuses but in "edit" statuses it is a long string of text rather than a multi-row box you can scroll through (like schedule description)

**Comment by LisaMoore1** [comment]
@calebissharp Monitoring Area Location seems to be the only one that doesn’t have a multparagraph look.  All the rest look great.

**Comment by calebissharp** [comment]
@LisaMoore1 I wasn't aware that monitoring area location is usually long. Is it not just a few words usually?

**Comment by LisaMoore1** [comment]
@calebissharp. It isn’t usually super long but it could be (See Jan 29 comment listing all the related ones I could find). Long location descriptions are displaying well in PDF.

**Comment by calebissharp** [comment]
@LisaMoore1 Do you want the monitoring area location to appear as a multiparagraph input (like the invasive plants "other" or range readiness notes) when it is editable as well?

**Comment by LisaMoore1** [comment]
@calebissharp Yes please.
