### ISSUE TITLE
Some collapsable boxes (like the pasture ones) are small and unwieldy.

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#495]
When working on things like indicator plants it can become hard to see what you are doing, the box is pretty small for the amount of content that needs to be scrolled through depending on the plan.

**Comment by calebissharp** [comment]
@LisaMoore1 How would you prefer this to work. Just make the boxes bigger? Should they not be scrollable at all and always take up as much height as they need?

**Comment by LisaMoore1** [comment]
@calebissharp I lean towards as much space as they need since the collapse arrow is always visible. @micheal-w-wells do you know if there was some discussion about why to use scrollable spaces rather than full open?

**Comment by LisaMoore1** [comment]
@calebissharp This is better as I can see now but still having problems when adding a row. Not sure if it is a box size thing or a drop down behaviour problem. Let me know if should be separate issue. 

The selection menus drop down below the visible box on the bottom row. Every now and then I’ve seen them open upwards (above the field) which is preferred. 

![IMG_7445.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/77956e58-97d3-4e73-bcaa-47be418656ac)![IMG_7446.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/03ae0603-a848-4e1b-9d5b-e90236845ad6)

**Comment by calebissharp** [comment]
@LisaMoore1 As far as I'm aware, that dropdown bug was probably introduced in an unrelated PR. I think we should close this issue and create a new one.
