### ISSUE TITLE
Staff are not able to add actions for issues which they may need to do if assisting an agreement holder with initial entry. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#500]
Add the ability for staff to add, delete, edit , save actions for minister’s issues while in staff draft or providing feedback (status 6 and 13).

**Comment by LisaMoore1** [comment]
Checking through user stories and noticed this aspect of one of the stories had not been covered.  Miss on my part when reviewing that issues captured entire stories. High priority compared to other things in the backlog pipeline.

**Comment by LisaMoore1** [comment]
@calebissharp Is this a fairly quick fix or longer? No idea how I missed it in my everything should be CRUD for staff in status 6 and 13.

**Comment by calebissharp** [comment]
@LisaMoore1 This is just about staff not being able to add and edit minister issue actions, correct?

**Comment by LisaMoore1** [comment]
@calebissharp Yes. They **should** be able to do add/edit actions for issues in statuses 6 and 13.
