### ISSUE TITLE
Agreement holders unable to edit in Status 10 -- should be equivalent to 1 (I think), 4, 5 and 19

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#507]
@calebissharp See the reference table (the one with orange boxes for who gets to edit what). Not holding up leaving the deploy in place but needs a quick fix.

**Comment by LisaMoore1** [comment]
@calebissharp Estimate for this one then it can be closed.

**Comment by LisaMoore1** [comment]
@calebissharp This one is ready to move to closed but it still needs your estimate.

**Comment by calebissharp** [comment]
@LisaMoore1 Whoops, missed this. Sorry!
