### ISSUE TITLE
Elevation missing unit indicator in web but PDF shows as feet.

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#516]
![image](https://user-images.githubusercontent.com/955467/73204106-4362cb00-40f3-11ea-848d-207592aa623e.png)
![image](https://user-images.githubusercontent.com/955467/73204148-52e21400-40f3-11ea-880e-b7c7f239630c.png)

Comment from RO was that they had assumed meters until they saw FT on pdf.

**Comment by calebissharp** [comment]
@LisaMoore1 What unit should elevation be?

**Comment by LisaMoore1** [comment]
@calebissharp  Elevation is metres in both cases.

**Comment by LisaMoore1** [comment]
@calebissharp 
Not showing metres in plan or PDF.
