### ISSUE TITLE
Error generated when creating a schedule if a "save draft" action did not happen after adding pastures. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#524]
The recently added pasture shows up in the drop down list in the schedule row but if you select it an error is generated. Nearest I can tell if you do a "save draft" action before starting into adding schedule the error is not generated. 

Because they show in the list it looks like everything is good to go. Either don't show in list and somehow show message to save draft after adding pastures OR ??

**Comment by calebissharp** [comment]
Resolved by #511
