### ISSUE TITLE
For plant community action (anywhere else this dropdown type is used?) the drop down behaviour is confusing. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#525]
If you select "Other" you **MUST** type something or you get a "could not save due to invalid fields error" but it looks like leaving it just as "other" should be OK

- add some sort of messaging that you must enter text and if blank you get an error message under the field

When you type something in for "other" (ex. "thing") then when you look at the dropdown it now shows what you typed at the bottom of the list. It is unclear that if you want to change what you entered for "other" you need to select your text (ex. "thing") and then type over it in the field

- add clarity here by perhaps leaving it saying "other" in the drop down and then provide the same messaging/error that you use for the first part of this (or however else it is solved)

Solution for the two parts probably all part of one solution. 

For this (and all dropdowns) it is confusing to have **anything** appear in the field before a selection is made. If you've activated the dropdown the field should remain **blank** until you pick something otherwise it looks like you've made a selection and you actually haven't.

**Comment by calebissharp** [comment]
@LisaMoore1 
> For this (and all dropdowns) it is confusing to have anything appear in the field before a selection is made. If you've activated the dropdown the field should remain blank until you pick something otherwise it looks like you've made a selection and you actually haven't.

This has been discussed previously in https://github.com/bcgov/range-web/issues/164#issuecomment-558747586 and is caused by an upstream bug in semantic-ui.

The other parts of the issue I can fix by making the plant community action dropdown behaviour more like the indicator plant dropdown.

**Comment by LisaMoore1** [comment]
@calebissharp Forgot we'd already been there done that on that particular item. In that case can you make "Select" the first entry on the list so that that is what shows until you've made a selection?

**Comment by calebissharp** [comment]
@LisaMoore1 I'm not sure that would be possible. How important is this?

**Comment by LisaMoore1** [comment]
@calebissharp two calls in the last week where, when watching screen share, they've thought they'd selected something because the text they wanted was displayed but they hadn't. How big would it be?

See https://tools.usps.com/zip-code-lookup.htm?byaddress the state dropdown for an example.

**Comment by calebissharp** [comment]
@LisaMoore1 We'd have to replace the dropdowns with a component from another library. It won't look the same, but hopefully would have better behaviour. I'd put the estimate at 2.

**Comment by LisaMoore1** [comment]
@calebissharp Can you move that element to a separate issue and put it in backlog.  Fixing it so that it isn't opening below the working window and some sort of instruction re. how to deal with "other" are the primary wins for this one.
