### ISSUE TITLE
Back arrow by RAN is navigating back like browser rather than returning to work queue

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#528]
Small back arrow should return user to work queue. I have noticed this behavior when I have opened a PDF and then try to navigate back to the work queue.  I'm not 100% certain it occurs every time but definitely periodically. Ex. RAN099951, RAN099954, RAN099952

**Comment by calebissharp** [comment]
@LisaMoore1 Does it make sense to *always* go back to the work queue? There are a couple scenarios I can think of (like when getting to the rup page through a link) that it would be strange.

**Comment by LisaMoore1** [comment]
@calebissharp Hmm. I get the link thing (I've never sent one to someone else because they wouldn't be able to access it as it wouldn't be assigned to them so not one they could see if logged in under anything other than my IDIR) and that there may be other scenarios. 
My concern is that there has to be some way to get back to the work queue rather than being in an endless loop with the popup (or wherever you were before you arrived here). 
Perhaps the actual issue (problem statement) should be: unable to return to work queue if any other you have navigated away from plan (ex. PDF popup) and then return to plan. Should we reword it? Close this and make a different one?

Other ideas for solving the actual problem?

**Comment by calebissharp** [comment]
Actually, I take that back. I think it's fine to make the back button just always go to the work queue.

**Comment by LisaMoore1** [comment]
K. All good then.

**Comment by LisaMoore1** [comment]
@calebissharp Looks good. Can you add estimate? Thx
