### ISSUE TITLE
Dropdown boxes for schedule open below the field which consistently puts them outside of operating window = have to scroll/fuss every time

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#532]
@calebissharp The selection menus drop down below the visible box on the bottom row. Every now and then I’ve seen them open upwards (above the field) which is preferred. (Identified while trying to figure out what was actually driving #495)

![IMG_7445.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/77956e58-97d3-4e73-bcaa-47be418656ac)![IMG_7446.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/03ae0603-a848-4e1b-9d5b-e90236845ad6)

**Comment by calebissharp** [comment]
Related to #547
