### ISSUE TITLE
Need to force site to refresh what is cached when online.

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#537]
We have a lot of non-techy users, and in general needing to delete cache to get new features/fixes just isn't a good experience.  We need to make the site/pod/whatever smart enough to refresh what is cached when connected.

**Comment by micheal-w-wells** [comment]
@calebissharp see anything wrong with this approach, or other special considerations with the cache stuff you've done so far?  https://dev.to/flexdinesh/cache-busting-a-react-app-22lk

**Comment by calebissharp** [comment]
@micheal-w-wells Something we may want to try first is to just set the cache header for `service-worker.js` to `no-cache`. This is a Caddy issue, so I'm looking into the documentation for that.

**Comment by micheal-w-wells** [comment]
dragging in to sprint because this is likely going to be an ongoing trial and error issue, better start now rather than later.

**Comment by micheal-w-wells** [comment]
I think this is working???  Since I last refreshed cache (required to apply the change) there have been other deploys and i seem to be seeing changes.  

Please others keep an eye out to see if this resolves it for you @LisaMoore1 @calebissharp @okanji @ZoeSimon

**Comment by ZoeSimon** [comment]
Task: @calebissharp to disable the service worker

**Comment by micheal-w-wells** [comment]
@calebissharp ping me when there's something in test that normally would require a cache clear to see once deployed.  I'll hop in, look, and ideally close this issue.

**Comment by calebissharp** [comment]
@micheal-w-wells Manage clients page should be behaving a little bit different now, since it will link all location codes.

**Comment by micheal-w-wells** [comment]
@calebissharp  Blocked by this (also get in incognito once most of the page loads):
![image](https://user-images.githubusercontent.com/955467/86603601-0da2f780-bf59-11ea-8816-39b6ecb32b8e.png)

**Comment by calebissharp** [comment]
That's strange. Are you signed in as AH or staff?

**Comment by calebissharp** [comment]
@micheal-w-wells Could potentially be related to the zone select stuff.

**Comment by calebissharp** [comment]
@micheal-w-wells Are you still getting this error?

**Comment by micheal-w-wells** [comment]
![image](https://user-images.githubusercontent.com/955467/86624509-430b0d80-bf78-11ea-94f2-b17e7cd66b11.png)

**Comment by calebissharp** [comment]
@micheal-w-wells Can you upload the error in the console too please?

**Comment by micheal-w-wells** [comment]
![image](https://user-images.githubusercontent.com/955467/86626193-35a35280-bf7b-11ea-9eff-e3de28112152.png)

**Comment by calebissharp** [comment]
Are you an agreement holder perhaps?

**Comment by micheal-w-wells** [comment]
Sorry ran out of time to keep checking github yesterday.  No I'm definitely staff.

**Comment by calebissharp** [comment]
@micheal-w-wells It looks like you're actually getting 401 on every request. Try signing out again, maybe clearing local storage too.

**Comment by micheal-w-wells** [comment]
Is there an endpoint I can hit to sign out easily without wiping storage?  Was really trying to avoid that so we could get this issue closed.

**Comment by calebissharp** [comment]
This feels more like an issue with the role switching that you do. The user object is kept in localstorage, so you can end up with outdated info since it doesn't refetch every time. That isn't really related to this issue though.

**Comment by calebissharp** [comment]
Incognito should work too though, assuming you've closed out of all previous incognito windows.

**Comment by calebissharp** [comment]
@LisaMoore1 Are you seeing new changes in test without having to clear cache now? If so, I think we can close this.

**Comment by micheal-w-wells** [comment]
@ZoeSimon saw new changes I'm closing
