### ISSUE TITLE
Staff providing comments when submitting a staff draft to the AH is not in current workflow 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#544]
It is important for staff to provide the AH with instructions when the initial submission is made to them. Several staff thought they had been able to do it but aren’t now. I’m not sure if that is a implemented in iPad but not web thing, was in web but isn’t now, or never did exist and we are delusional. In any case, staff do need to provide instructions when initially submitting.

**Comment by micheal-w-wells** [comment]
can wait until after #668 release
