### ISSUE TITLE
PDF - Invasives - Other option looks weird the way it is displayed.  See description. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#561]
On screen RUP "other" is at the bottom of a big list
It could be the only thing selected (no check boxes)
When that scenario displays in PDF the word "other" seems weird (other to what?)
The word "other:" can be removed from the beginning of the entry.  Just the text of the entry will be fine.

**Comment by calebissharp** [comment]
@LisaMoore1 Do you want to remove the "other: " text just when none of the other checkboxes are selected, or remove it completely?

**Comment by LisaMoore1** [comment]
@calebissharp I think it can be removed completely and appear as text under the Invasive Plants heading.

**Comment by calebissharp** [comment]
@LisaMoore1 Ok, sounds good.
