### ISSUE TITLE
Work queue is sorted in an apparently random manner, cannot be resorted and for those with long lists it is difficult to find the RANs that need attention

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#562]
Sort function on all columns
Filter on Status (ex. see only those with "Feedback Required")

**Comment by micheal-w-wells** [comment]
Got the data on the new table but handed over to @calebissharp for his styling expertise and to get it from prototype to prod worthy.

**Comment by LisaMoore1** [comment]
@calebissharp 
Staff Contact column does not populate a value until after a draft has been created 
AH should always see who the staff contact is (even before drafts created) and when logged in as a staff person I should appear as staff contact for all of those I am contact for (right now everything I see)

Up arrow makes me think that is ascending — but that seems to be showing descending.
WIth many records in staff descending should show things with status at the top but it isn’t doing so reliably. When looking for the ones that have drafts I can’t get them to rise to the top of the list (unless I filter by an AH first to get a smaller list). — not sure if the problem is list length or something else but it’s what I observe.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 Does the staff contact need to populated be regardless of the plan getting started?  The staff will know because they can only see their own RUP's, and the AH can't see it and aren't affected.  I could see it being annoying for admins maybe.

**Comment by micheal-w-wells** [comment]
sorting was fixed in #666

**Comment by LisaMoore1** [comment]
@micheal-w-wells re. Staff contact.  I think it should populate staff contact for all RUPs — if not now in future as there is an enhancement listed on our board to allow view of all RANs in the district. Perhaps that could be changed to all RUPs in the district and if they haven’t been prepared they just wouldn’t show up on the list unless they belong to you.  There are maybe some options there but it does feel to me like if we have a field, and we have the data on hand to populate it, it should be populated.  If not we get weird things like me worrying that I had been lost as contact for all those RANs. :)

**Comment by micheal-w-wells** [comment]
@LisaMoore1 works for me!

**Comment by micheal-w-wells** [comment]
@LisaMoore1 i made #674 so there's a bit less reading to see what's outstanding.  If everything else for this one is good can we close it?
