### ISSUE TITLE
Staff need to be able to view RUPs for all RANs in their district -- view only their own

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#563]
Right now staff can only view/edit their own plans.  Being able to view all RUPs in their district is important thing during field season (beginning approx May1)

**Comment by calebissharp** [comment]
@LisaMoore1 Should they just be able to *view* (not edit) plans in their district that aren't their own?

**Comment by LisaMoore1** [comment]
@calebissharp Yes, view only for all of district, edit only for those assigned to them.  I think this could get very messy in the work queue until there is a way to filter it (see #562)

**Comment by calebissharp** [comment]
@LisaMoore1 Gotcha. May be a bit tricky to implement then, since the editable/non-editable stuff is just based around roles and statuses, but doesn't take into consideration ownership.

**Comment by LisaMoore1** [comment]
@calebissharp Does it make it any simpler if we only make this option available for approved plans (which aren’t editable to anyone)?

**Comment by calebissharp** [comment]
@LisaMoore1 Maybe. I would recommend putting this feature pretty low priority for now though.

**Comment by micheal-w-wells** [comment]
Throwing this one to @okanji as it's been requested a bunch by staff, @LisaMoore1 's date above makes it pretty relevant for right now, and also it's a pretty concrete ask - we have a lot of discussion to do around what the UI for DM workflow will look like as a group yet.

**Comment by okanji** [comment]
### To implement:
- Range officers should be able to see range plans in the district but only be able to edit the ones in their zone
- Be able to filter zones
- Officers should at least be able to filter for the range plans in their own zone

To determine:
 - [ ] Identify if agreement and plan endpoints only let you see information about a range officers own zone or information for a whole district

**Comment by okanji** [comment]
This is a concept for the UI for filtering by Zones. The behaviour would be that the Range users assigned zones are selected by default. Other zones can be checked/unchecked and hitting the refresh button clears the selections and applies the default.

Do comment on impressions/ changes. Thanks!

![image](https://user-images.githubusercontent.com/30703259/83819176-149ac980-a67e-11ea-9b92-3cf5f8608f33.png)
![image](https://user-images.githubusercontent.com/30703259/83819296-54fa4780-a67e-11ea-861a-d38600339f1a.png)
![image](https://user-images.githubusercontent.com/30703259/83819489-d94cca80-a67e-11ea-9de8-f6f5807bbcad.png)
![image](https://user-images.githubusercontent.com/30703259/83819580-1749ee80-a67f-11ea-8616-f3b14f57c324.png)

**Comment by LisaMoore1** [comment]
@okanji I like this. One thing that might be helpful is some sort of select all option that would allow the user to select all for their district as I think that is the most likely thing a staff person would do — the use case being “I want to search for an RUP that isn’t in my zone but I’m not sure which zone it is in”.  This would require the ability to both see the full list and then search within that list (or a subset of the agreements if only some zones are selected).

**Comment by okanji** [comment]
@LisaMoore1 thanks for your feedback, I agree that would be useful. I will integrate that feature in and post the updated design here

**Comment by okanji** [comment]
_Additional feedback:_ Would be nice to show the applicable range officers name next to the assigned zones

**Comment by ZoeSimon** [comment]
@okanji is all the the UI done for this one? Are we still working on back-end changes?

**Comment by okanji** [comment]
Still working on backend but hoping to resolve this today

**Comment by calebissharp** [comment]
@LisaMoore1 This feature's been merged in, so should be ready for you to take a look when you have time.

**Comment by LisaMoore1** [comment]
- I should not have option to Edit or start a new plan for a RAN not assigned to me — which I can at present (should be view only for anything not assigned to me)

- Some sort of “Error:” message showing up in work queue directly under every file that has a RUP and not assigned to me

Conceptually good although it is a little irritating to have to individually click the zones rather than a single click to select/clear all. 

![EF52FD07-F20E-4CF6-97C3-C9ADDA02DABD.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/8b3a82a5-99f4-41b9-a042-173cceb6076b)

**Comment by okanji** [comment]
@LisaMoore1 thanks for taking a look at that. I will address the 'error' and being able to edit plans that are not assigned to the logged in user. 

I struggled to implement the ability to select/clear all. The component library Material UI does not allow multiple actions on a dropdown list and I was not able to override this. It is something that I can look into further or perhaps just have a button beside the dropdown list to select/ deselect all.

**Comment by LisaMoore1** [comment]
@okanji @calebissharp It seems like I can view plan OK when I first log in but After I’ve deselected some of my zones and selected others I start to get these errors. Am going to explore more and will add any other discoveries here. 

![E7A58362-9D81-40DF-98D7-E803AD2B879D.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/19dd7b5b-88c2-46d8-a670-f702e3ea56ff)

**Comment by calebissharp** [comment]
@LisaMoore1 Are you still getting this error?

**Comment by LisaMoore1** [comment]
@calebissharp I was this morning. Should I clear cache again and start over to see?

**Comment by calebissharp** [comment]
Yes please (although try it first without clearing cache)

**Comment by LisaMoore1** [comment]
@calebissharp I am still getting this problem viewing any plans that are not assigned to me. As noted above there is also an “Error:” line under each RAN not assigned to me in the work queue.

I’m not sure if it is expected behaviour but if I select specific zones to view (say I add your, Oamar and Zoe’s zones) then I view a plan (in this case one of mine since that doesn’t punt me to retry screen) when I return to the work queue it has defaulted back to just those zones assigned to me. It is a little irritating if you are hunting around for a certain plan and have to keep checking all those boxes every time you want to see all again.

**Comment by calebissharp** [comment]
@LisaMoore1 Try again (just to see if the error is fixed)?

**Comment by LisaMoore1** [comment]
@calebissharp was still getting it just now until I cleared cache and now WQ no longer has error rows and I’m not getting Retry screen. Yay! :)

**Comment by okanji** [comment]
Nice one @calebissharp!

**Comment by calebissharp** [comment]
@LisaMoore1 Just merged another PR that should hopefully fix the permission issues you saw. Let me know if that works.

**Comment by LisaMoore1** [comment]
@calebissharp. 
- Persistence of selections seems good.
- Wondering if there is some sort of funky duplication in the zone list (fifth test zone) or if there are just two zones with the same name and I didn’t notice it yesterday. 
- Is there a way of disabling the “New Plan” button or changing text to “No plan” for those I’m not the contact for? As is, I can select it but then when I can’t edit fields or save it feels like an error.  Is that a biggish thing or small? If biggish we might just need to leave it. 

![58894710-4D2C-481E-8211-97D8EB89C00F.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/f8b47bdf-459b-4ff6-b2b3-34d15e135a5f)

**Comment by calebissharp** [comment]
@LisaMoore1 I have a duplicate "Fifth test zone locally". I think this is just an artifact in the test data we seed the DB with.
![image](https://user-images.githubusercontent.com/8854811/87094764-50343080-c1f4-11ea-8e1f-5ad82abe0be7.png)

Good catch with the hiding of the "New plan" button. It had crossed my mind yesterday, but didn't make it into the pull request. Shouldn't be too difficult.
