### ISSUE TITLE
Issues with Minister’s Issues Timing Action related to Online label and PDF dates

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#566]
Online labelling should be same as PDF (and plant community timing action) in that this is a “No Graze period” not a grazing period (emphasis here on NO graze)

On the PDF the start month for the No Graze period (which is correctly labelled there) is adding a month (ex. Online says June 1 but PDF is displaying Jul 1)![IMG_7490.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/5859037f-5224-4f1a-9eab-93af7ff5b452)

**Comment by micheal-w-wells** [comment]
give it 20 and its ready to test
