### ISSUE TITLE
Replicate an entire RUP to a different RAN

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#582]
There are many areas where there are multiple overlapping agreements for exactly the same area = same pastures, plant communities, monitoring areas, additional requirements and issues. Often the only thing different in these agreements is the client information, usage and schedule (i.e. info pulled from FTA and entered by AH). It would be considerable time savings to staff to be able to export the info they have entered into a RUP to a different RAN. The luxury edition would be being able to select which content they want to copy over. The base model would be just export/import everything currently available and they can delete/add as needed.

**Comment by calebissharp** [comment]
@LisaMoore1 What about statuses and status histories? I assume you wouldn't want to copy that over. And what if there's already an RUP in progress, would the copy overwrite it?

**Comment by LisaMoore1** [comment]
@calebissharp only the data (this is basically a glorified cut and paste). I'll ask my SME group what they think is best re. overwrite.  Should have something for you by Tues if that works for you.
