### ISSUE TITLE
Plant community notes label and Other notes

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#587]
Plant community notes was labled 'Pasture notes', now reads 'Plant community notes'
Other notes was incorrectly repeating Plant Community notes, now shows the correct data if populated.

**Comment by LisaMoore1** [comment]
@micheal-w-wells The label here should be "Plant Community Description".

**Comment by micheal-w-wells** [comment]
give it 20-30 min and a clean cache
