### ISSUE TITLE
long pasture name in schedule overlaps text in pdf

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#591]
![image](https://user-images.githubusercontent.com/955467/74385373-42df5b00-4da8-11ea-8670-606d2e63d214.png)

**Comment by LisaMoore1** [comment]
@micheal-wells Here’s an image of the one I was using to test it for #411.  Just saw it this morning in the PDF I was working through. Do we know what RAN she had the overlap in? If so we could check using Admin. 

![IMG_7516.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/5442187d-6ca6-4b04-93ea-00edf9de8a4c)

**Comment by micheal-w-wells** [comment]
She says RAN077514, RAN077506, RAN077531.

Original issue (in case it helps troubleshooting) was #411

**Comment by LisaMoore1** [comment]
@micheal-w-wells Seems to be a problem with having a / in the name at certain positions (later I think). No problem with hyphens Compare these two images. 

![IMG_7544.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/91c84f57-1e33-4c35-a345-3d71323c7d62)
![IMG_7545.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/4cfe8ed9-add4-4f77-9edf-a00d5afdd4e7)
