### ISSUE TITLE
Autosave plans before generating PDF

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#592]
Not saving and hitting print pdf means it is out of order.  Maybe a 'there are unsaved changes that wont be reflected on the pdf' would be helpful.

**Comment by calebissharp** [comment]
@micheal-w-wells I think a better solution would be to automatically save the plan before showing the PDF dialog.

**Comment by micheal-w-wells** [comment]
@calebissharp SGTM
