### ISSUE TITLE
Logging out and back in causes a white screen

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#603]
Seems inconsistent but has happened to me more than once (even shortly after clearing cache) on both chrome and Safari.

**Comment by LisaMoore1** [comment]
@micheal-w-wells.  This is me too. Just a weird thing where if occasionally when I log in I’ll get a white screen (I think it’s totally white not just missing RUPs) but if I refresh then everything is good.  I’ll pay better attention next time it happens to the exact look. Might be related to the accompanying occasional “error/retry” message that also just needs a refresh and you’re good.

**Comment by calebissharp** [comment]
@LisaMoore1 By "submit" do you just mean when you log in in? Or do you get a white screen when you submit an RUP?

**Comment by LisaMoore1** [comment]
@calebissharp Sorry. Just when I go through the login process before I ever view a RUP. I haven't been able to nail down exactly what conditions cause this but it happens periodically.

**Comment by calebissharp** [comment]
Potentially related to #570

**Comment by LisaMoore1** [comment]
Agree there is potential relationship but with the white screen mentioned here I've waited for ages and it just stays white with no indication there is an error or it is processing.

**Comment by calebissharp** [comment]
@LisaMoore1 Ok, sounds like it's probably a little different then.

**Comment by calebissharp** [comment]
Has this issue appeared recently? I think it may have been related to #719

**Comment by micheal-w-wells** [comment]
haven't seen it I think it can be closed if @LisaMoore1 hasn't seen it.
