### ISSUE TITLE
Clients with gov.bc.ca email addresses not showing in drop down list to connect client

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#612]
@micheal-w-wells One of Chris’s — Entries immediately before and after her are displaying in the list properly. Hoping this isn’t somehow a leap year gift.

**Comment by calebissharp** [comment]
The get client request seems to be excluding emails that end in `@gov.bc.ca`. Do you know why it's like this @LisaMoore1?

**Comment by micheal-w-wells** [comment]
its probably to exclude staff from showing up in the list

**Comment by LisaMoore1** [comment]
@calebissharp @micheal-w-wells Yup. It was so the top drop down list was more relevant (and mistakes couldn't be made accidentally selecting staff). There are very few AH that are also government employees and did not expect govt employees to work email for items related to their business...

**Comment by calebissharp** [comment]
@LisaMoore1 Ok, what should the plan be here then? I assume you still want to prevent staff from showing in the list.

**Comment by LisaMoore1** [comment]
@calebissharp Can we filter for usernames that start with "bceid\" and aren't "myrangebc" rather than emails ending in gov.bc.ca? That would get us to the same spot I think of excluding staff from the list.

**Comment by calebissharp** [comment]
@micheal-w-wells What do you think? I don't know enough the data in prod to determine if a filter like that would be comprehensive.

**Comment by LisaMoore1** [comment]
It appears that all entries are either idir\ or bceid\  so excluding all those beginning with idir definitely gets rid of just staff.  "myrangebc" (what we use for administration in prod) does not seem to have a user account so doesn't have to be excluded.  @micheal-w-wells Seem right?

**Comment by micheal-w-wells** [comment]
I think removing the filter on .gov.bc.ca, but also filtering out the bceid\myrangebc user and IDIRs should do the trick for now.  Staff are not to login as staff with BCEID (other than as bceid\myrangebc admin) and not as AH with IDIR.

**Comment by LisaMoore1** [comment]
@calebissharp The list in test now seems really short but I’m not sure if that is because those are the only entries in the test environment. Can you confirm with @micheal-w-wells that what is appearing there is complete for test given the filters?

**Comment by micheal-w-wells** [comment]
Looking now

**Comment by micheal-w-wells** [comment]
```
myra=# select count(distinct(client_number)) from ref_client;
 count 
-------
  3490
(1 row)

myra=# select count(*) from user_account where username like 'bceid%';
 count 
-------
    14
(1 row)
```

**Comment by LisaMoore1** [comment]
@micheal-w-wells I’m still not exactly sure what is happening with the list as there are 18 ( I think) rows in the drop down. Does that mean there are 4 in the list that have non-BCeID user accounts?

**Comment by micheal-w-wells** [comment]
You're logic is sound yep, having a look at the list myself I'd say those are dev accounts to login as AH.  @LisaMoore1

**Comment by LisaMoore1** [comment]
@micheal-w-wells So in your estimation is what we’re seeing the right list? If so we can close this one.
