### ISSUE TITLE
Work Queue displaying (or perhaps there actually are) many copies (versions?) of things in some cases.  

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#613]
Samples here:

![928CE194-E21D-4453-A1A7-3D774B6EFC9A.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/a68d76e4-3293-4e45-a53f-470e5afab1b3)

![D4927954-9908-44F4-A3D6-FDFE774DAE85.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/fd5b1f77-d669-4319-9deb-12ccb502bc55)

![92AC1F78-4DB0-456D-A9BB-0ED57AD76A73.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/efbd0971-1140-4e16-8a44-79dc437ce425)

**Comment by calebissharp** [comment]
@micheal-w-wells Can you run check this in the db?

**Comment by micheal-w-wells** [comment]
@calebissharp is this one i sent you results on in slack or are you still stuck?

**Comment by calebissharp** [comment]
@micheal-w-wells Ya, what I sent you about removing that diverging snapshot. Just need to clean it up so the migration will run.

**Comment by micheal-w-wells** [comment]
This train of thought has been derailed - @calebissharp can you paste the SQL I need to identify the records I need staff to review?

**Comment by calebissharp** [comment]
@micheal-w-wells 

> It looks like there are diverging snapshot records for plans 43 and 177, which reference the same agreement (RAN099954). It looks like 43 is newer, so I think we can just manually set the plan_snapshot records with plan_id=177 to a plan_id of 43 instead. This shouldn’t show up in prod, since there’s no snapshots yet.

I think I also may have had to delete the `plan_version` records where plan_id=177.

**Comment by calebissharp** [comment]
The migration's been run, so most of these duplicates should be either removed, or reduced, in which case they can be deleted on a case-by-case basic because we couldn't determine the most recent version.

**Comment by micheal-w-wells** [comment]
It's also the case that the test db has some wonkyness in terms of duplicates.  We should, either before or after this deploy do a wipe of plans and agreements in here and do a synch with test FTA to clean things up.   In meantime we'll verify your duplicates manually.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 I verified that none of your RAN09's should have an extra (old) primary so that dupe scenario is ruled out.

**Comment by LisaMoore1** [comment]
I haven’t seen any existing duplicates nor generated any as I’ve worked today. If no one else has either this can be closed.  @Micheal-w-wells if everyone else is good with this can you close it? Thanks.
