### ISSUE TITLE
A plant community was still visible after delete, delete option yielded "null" name in the popup, on completion two plant communities were deleted. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#619]
Couldn't replicate. Maybe a slow connection issue?

**Comment by calebissharp** [comment]
@LisaMoore1 Can't seem to replicate the delete issues. The name appearing as "null" is a separate issue though.

**Comment by LisaMoore1** [comment]
@calebissharp I thought maybe the name as null happened because it actually had deleted so when it went looking for a field to display there wasn’t one. I’ve had that happen in FileMaker before. The not being replicable part was why I handed the comment about slow connection.  Wondered if it was still “processing” the delete when I though it hadn’t happened yet and did it again. I think we had something else (maybe the create amendment) where we needed to add an indicator that the process was still happening so I didn’t keep trying while it was in process.  The battle with connections is real — especially in rural areas.
