### ISSUE TITLE
Versions are hard to differentiate from each other and may have a weird date update thing happening. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#622]
Moved a version (180) that was in decision required to recommend and then approved. 
Several entries exist for this RAN
![image.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/2875ece5-5d1e-4ab2-b060-d0e54f9e0358)

There are three versions listed:
![image.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/735b2e5b-3efa-45c3-ac78-699f548f2ab1)

![image.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/ccd3a977-82b2-44fc-99f5-80bfa6ff566d)

![image.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/b050117a-cee6-4cc4-97d5-215bbd264bf5)

![image.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/6d1c43d3-b1bb-4987-a15a-88ac99b74ff8)

I'm trying to reconcile these versions with what I see on the work queue (they all have today's date) and I can't easily tell which is which.

**Comment by micheal-w-wells** [comment]
@LisaMoore1  this home screen thing doesn't exist and I think all duplicate issues are resolved so I'm closing, but if you think it should be reopened fly at it.
