### ISSUE TITLE
Plan confirmation should be linked to user account instead of client_id

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#633]
This saves us in the situation where we relink a user to another client number and/or location code, otherwise they get stuck wondering why they can't sign (no submit button will appear).

**Comment by micheal-w-wells** [comment]
I think we can save staff a lot of grief if we tackle this next sprint @LisaMoore1 @ZoeSimon  and also add logic to the import job to make sure that if the person doesn't change (but client number does) then not require a new signature.

**Comment by micheal-w-wells** [comment]
I've got a bit of time to look at this I'll at least see if i can flush out what needs to be done this afternoon.

**Comment by micheal-w-wells** [comment]
Things we want to factor in when reworking this, anyone else feel free to pipe in with suggestions here:

- We want to link a `user_id` to all `client_id`'s matching the client number.  Don't need to rework `user_client_link` to do that, but need to address the front end code and perhaps the endpoint to handle that.
- We want the import job to keep that in synch.  We don't want dispositions to unlink people.
- We don't want a disposition* to wipe a signature, unless it's a primary becoming a secondary.
- We want to factor in that later we should be notifying staff and agreement holders of what they need to sign and why.  It might be we need a whole new table or perhaps column that keeps a history of signatures for each plan, and a reason for each.

* A disposition is a change of `client_id` : `agreement_id`, or in MyRange the `client_agreement` records.  Just because someone's `location_code` is changing, doesn't necessarily mean they are a different person and we need to handle that.  Conversely if it is a new person we need to require a new signature.

**Comment by LisaMoore1** [comment]
Looks pretty good. “Renewal” isn’t really a thing. Here is life of RUP:
- initial RUP created/signed
- amendments created/signed
- RUP is extended (marked as extended and end date extended by up to 5 years) — DM signature only but AH must “request” it (no set “extension request” process in place)
- RUP doesn’t get completed/signed in time so “exemption” is offered (exemption is in the form of either “follow the previous RUP until X date or Y condition met” OR “follow this incomplete (most often consultation incomplete) until X date or Y condition met”)
- RUP expires so a new RUP is created/signed (if amendments were kept up to date the “new” RUP is just a newly signed copy of the most recent version)

___

- Extension is most like an amendment changing end date but must be identified as extension and a RUP can only be extended once — both AH and DM signature required
- Exemption is most like an “interim” plan where DM agrees to an old/incomplete RUP for a limit period of time — no defined process re. signing (DM for sure, possibly AH...often AH has signed but there is something outstanding preventing DM signature)

Side note: any decision made by DM needs option for them to provide conditions

**Policy on Extension/Exemption**
[https://app.zenhub.com/files/120951690/fd3b104a-e9a5-4731-bd69-65867ec3c145/download](https://app.zenhub.com/files/120951690/fd3b104a-e9a5-4731-bd69-65867ec3c145/download)

**Comment by micheal-w-wells** [comment]
Note for self - look at expanding plan confirmation object to include bceid + client num + location code so all the meta data is visible under versions list

**Comment by micheal-w-wells** [comment]
and thanks @LisaMoore1 !

**Comment by micheal-w-wells** [comment]
@LisaMoore1 @ZoeSimon 

Given I have another short week and a bunch of time to spend on invasives stuff, I'm going to make this "my one myra task" to move on.  We made some steps forward in the last change to client linking and I think also a step backward, and this part of the app (along with signatures) needs to be bullet proof.  

I'm going to start with this ticket to look at linking and plan signatures as a whole first, rather than independently (as that has led to some issues).  I'll then break this down once I have the solution ironed out.

We made good progress on cypress tests but getting them to work on my interim workstation is a losing battle and probably not where my effort needs to be given I have another workstation on the way with its own set up work.

**Comment by micheal-w-wells** [comment]
I think part of the winning strategy will be to keep a log of signature records and associate them to particular snapshots, and when we move to a new 'need to act/sign eventually' status we create a fresh batch for each RUP.  I think a lot of the client linking pain can be resolved by changing the page to link all `client_id`'s for a given client number, and amend the sync job to 'keep that user id subscribed' to new `client_id`s and prune off extras as it does now, however I think after some digging I think what the problem is we have been wiping signatures when a disposition happens because we aren't looking at the plan's status in the sync job (or really the trigger).

**Comment by micheal-w-wells** [comment]
The 'new' plan confirmation table will look like

`id` `plan_id` `user_id` `plan_version` `confirmed` `date` and maybe `reason`.

The client linking table we can keep the same, but change either the endpoint or the UI to handle linking the client ID's as a group.

The sync job and the trigger that cleans up old client agreements will need to look at  the plans status.

The sync job and the trigger that cleans up old client agreements will need to update a given users client links should a new one be created, this should stop staff from needing to go and relink.

**Comment by micheal-w-wells** [comment]
The big operational problem with this one is caused by how FTA and Myra handle dispositions which I fixed in a PR.  I think we'll still want to move to user_id  instead of client ID in this table but I think the fix just mentioned is worth getting out prior to that.

**Comment by micheal-w-wells** [comment]
Let's test this against a prod backup and run the import against it and see if it stops signatures from getting wiped.  Keep the issue open for now anyway as there's other work to be done on it.

**Comment by calebissharp** [comment]
I'm going to move this out of QA because we haven't actually implemented the `user_account` link yet, on either the backend or frontend.

**Comment by micheal-w-wells** [comment]
All good,  I'll see if I can find time to test the interim solution so we can push it out this week, ideally i run it against a prod backup.

**Comment by calebissharp** [comment]
> Just because someone's location_code is changing, doesn't necessarily mean they are a different person and we need to handle that. Conversely if it is a new person we need to require a new signature.

I think this is the trickiest thing to handle. How do we determine if a different `location_code` _is_ a different person?

**Comment by LisaMoore1** [comment]
@calebissharp I think we identify if it is a different person by if the staff person links that location code to a different BCeID (hence my concern about what looked like an automatic link one user to all locations in a different #843

**Comment by LisaMoore1** [comment]
@calebissharp @micheal-w-wells. Also note that when entries in FTA/CLIENT are correct, for individuals: 
- -00 location is the individual alone
- -01-anything else is the individual as a joint venture partner with someone else
- in both of these cases they are the same individual (but they could have different agents)

For businesses
- -00 location is the original business entry
- - 01-anything else is the business in either a JV or a separate “office” of same business
- they may have different managers (i.e. person who signs) for the different locations

The bulk of our agreements are held by individuals in JV relationships — over the 80:20 individuals:businesses ratio I think.  Not sure if that helps any. Let me now if we need a conversation on this.

**Comment by calebissharp** [comment]
How are we able to determine the type of relationship? Is that actually explicitly recorded, or just something that people know?
