### ISSUE TITLE
staff request: warning about deleting a whole year on the schedule

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#637]

**Comment by calebissharp** [comment]
@micheal-w-wells It looks like this already exists. When I choose the "Delete" menu option for a year's grazing schedule, I get a confirmation dialog. Is there any more information you could provide? Perhaps this is actually a bug that a staff person saw. Or is is just the messaging that needs to be updated?

<img width="974" alt="image" src="https://user-images.githubusercontent.com/8854811/76799922-c0273280-678f-11ea-94e3-8a00f11d9424.png">

**Comment by micheal-w-wells** [comment]
@calebissharp yeah lets change it to "Are you sure you want to delete the entire year from the schedule?  This cannot be undone".

**Comment by micheal-w-wells** [comment]
@calebissharp at a loss for why the test fails, can I get a second set of eyeballs on it?  https://github.com/bcgov/range-web/pull/661/commits/9ee7263aee4f137d84df758f9a9a1b59724b1ea9

**Comment by calebissharp** [comment]
@micheal-w-wells If you change it to a regex, it should pass:

```js
expect(
  getByText(
    /Are you sure you want delete the entire year from the schedule\?/g
  )
).toBeInTheDocument()
```

**Comment by micheal-w-wells** [comment]
thanks man

**Comment by micheal-w-wells** [comment]
/remind me to put this in a pr this afternoon

**Comment by micheal-w-wells** [comment]
#661
