### ISSUE TITLE
Action for Minister’s Issue: Action Description is required but does not have asterisk and does not show pink/required field until you enter the field to start typing

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#653]
Add asterisk to identify as required (match look/behaviour to other required fields)

**Comment by micheal-w-wells** [comment]
There are a bunch of these, i think I created issues for some of these as well.  Once i see how its done I might find/crush some of the others.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 changing how/when the fields decide to go red is non-trivial depending on what we want to do.  That said, a really easy change that we just tested is this:

Only have it display the fields as red once you try to save.   They will however stay red until the next save.

Getting them individually re-evaluate as the person is typing, without making all the other blank required fields being red while you type.

Ideal (and what we don't quite have nailed yet):  Load the page, fields are red, as you type they become not red.

**Comment by calebissharp** [comment]
https://github.com/calebissharp/range-web/tree/validate-only-on-save for reference.

**Comment by LisaMoore1** [comment]
Has this been merged? Not seeing any difference when testing just now.

**Comment by micheal-w-wells** [comment]
I just logged in to test to see myself, erased range name and clicked out - still turned red on me. To rule out caching this is what I did and @LisaMoore1 I'm not sure how you do it but I think this might save you grief of getting logged out of things:

1. Right click anywhere on the page (in chrome).
2. Open inspector.  You'll see a panel with a bunch of stuff that doesn't matter, ignore it.
3. Now you have the ability to right click the refresh button at top left of chrome toolbar, immediately to left of address bar (it doesn't work until you opened that inspect/dev console).
4. Hit hard cache and reload.

I did this and it worked.

**Comment by micheal-w-wells** [comment]
All that said I still get the old behaviour for plant community description

**Comment by LisaMoore1** [comment]
I like that I’d doesn’t show “pink” until save is attempted and then there is message — but I do miss the asterisk marks. Having those definitely helps get the right entry the first time.

**Comment by micheal-w-wells** [comment]
I think we can address the asterisks, might be an easy one for @calebissharp or @okanji but I'll take a peek if i have time today.  Glad its more predictable and working for you otherwise.
