### ISSUE TITLE
“Go back” and “retry” screen “retry” doesn’t seem to do anything

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#654]
I’m getting that screen frequently (and unexpectedly — like just navigating on a screen and it appears) but I also have very slow connection speed this morning.

**Comment by micheal-w-wells** [comment]
There's likely some fetches with optimistic defaults for timeouts that we could bump out, bit of an exercise to identify them all.  @calebissharp for the libraries you are using for fetches now, is this a global config?  Anything else that could be causing this?

**Comment by calebissharp** [comment]
@micheal-w-wells It's possible the "Retry" button was just never hooked up with the changed API around fetching plans. I'm not entirely sure it's a timeout issue either. It may be the connection dropping out entirely. I'll have to take a look.

**Comment by LisaMoore1** [comment]
@calebissharp I wasn’t able to get the error message today (success in and of itself!!) so wasn’t a blue to test the “retry” button. Anything I can do that will trigger this screen or is it something we’ll have to just let go until it happens to pop up again? If there isn’t anything else that can be done to test can you please either close or let me know and I’ll do it? Thx.

**Comment by calebissharp** [comment]
@LisaMoore1 If you try to navigate to a plan that you know doesn't exist, you can get the page, eg. https://web-range-myra-test.pathfinder.gov.bc.ca/range-use-plan/1000000
