### ISSUE TITLE
AH requesting feedback workflow has status problems  (ex. RAN099951) 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#657]
- Staff prepared draft and submitted to AH (as expected)
- AH updated and requested feedback from staff (as expected)
- Staff still seeing “submitted to AH for input” header (should be provide feedback header) (unexpected)
- Staff seeing “Request changes” as only option (I think this is the list associated with something other than feedback) (unexpected)
- If staff request changes the workflow popup references signatures — I think this is the one for when AH has requested decision (unexpected)
- After staff have requested changes (see above) AH still sees “Awaiting feedback from range staff” and the comment provided by staff not showing in history (unexpected)

This hangs workflow up because neither staff nor AH can take action — they are both waiting for the other. 
@micheal-w-wells and/or @calebissharp can one of you look at this soon so that I can continue with testing? Thx.

**Comment by micheal-w-wells** [comment]
Note for myself to put RAN099951 back in zone 40.

**Comment by micheal-w-wells** [comment]
Ran this in test, not using my local install so it was same code as you:

I tried as Andy to submit for feedback again, all good.  Then as staff I get "Provide Initial Range Use Plan Feedback" and there are 'Request Changes' and 'Recommend for Decision' which I think is what should be there.  Not sure why it didn't work for you the first time around.  Thinking we should delete this one and try from scratch and see if it consistently reproducible.

**Comment by LisaMoore1** [comment]
I was trying to work entirely within the feedback workflow but I think got diverted somehow.

**Comment by LisaMoore1** [comment]
I agree that the two options you see are what was expected.  Also not sure why the staff comment re. the changes got stuck somewhere in the ether — never came into AH view/control for updates.

**Comment by micheal-w-wells** [comment]
Deleted the plan.
Made a new one as me.
Submitted to Andy.
Andy changed the schedule, submitted for feedback
As Andy I saw that it was submitted for feedback.  As myself I saw that it had been sent to AH still.
I hit refresh a couple times.
Then as staff I saw what I should.

It seems like for some reason the site caching is super janky, similar to the agreement table/list.  @calebissharp what's your take?

**Comment by micheal-w-wells** [comment]
The one thing not super life-like in our test, not that this justifies it or anything, but maybe mitigates some of the risk of the issue, is that in real like the back and forth isn't this fast.

**Comment by LisaMoore1** [comment]
Unless they’re sitting together in the office and realize they want to fix something.

**Comment by calebissharp** [comment]
@LisaMoore1 / @micheal-w-wells, are you making sure to refresh the page when after it's been updated by the other user? I just want to make sure that's not the problem. We don't implement any kind of polling or realtime communication, so you have to refresh the page to get the most up-to-date information.

**Comment by micheal-w-wells** [comment]
Note to self put RAN099911 back in zone 40

**Comment by micheal-w-wells** [comment]
Lisa doesn't have a mutli session solution so I think she is logging right out.  Unless my memory is mistaken i nav'd away from the RUP and back as staff and it didn't update till I refreshed, about to do a few more tests to nail it down.

**Comment by micheal-w-wells** [comment]
Yeah I tried again with a multiple AH RAN and same deal.   Nav'ing away and back it looks like the RUP hasn't changed states until you hit refresh.

**Comment by calebissharp** [comment]
@micheal-w-wells Can we confirm everything works after you refresh though?

**Comment by micheal-w-wells** [comment]
Sending it back to AH for extra changes, they are in same boat where if they nav away and back, it looks how they left it.  Refresh fixes it.  I then submit for final decision, go back to staff tab.  Looks good from list view, but open the link and old data cached again.   Refresh again fixes it.  Sign in from other AH (the primary, all else was done as secondary).  Had to hit refresh 3 times to get the view plan button in list.  Sign it.  Back to staff tab.  Again old data after nav'ing away and back.  Refresh, all good.  Recommended ready.

Is the secondary supposed to be able to submit and start signatures?  Seems odd.

**Comment by LisaMoore1** [comment]
Switching between browsers and then refreshing.  @micheal-w-wells All agreement holders are created equal. The primary is the one who gets the snail mail — that is the only thing that makes them special. Any of the agreement holders can start something...but there should ever only be one “something” on the go for a RAN at any given time.

**Comment by micheal-w-wells** [comment]
To whoever tests this:  if you still see duplicates let me know a few of the RANS and I'll see if we have anomalies in test that explain them, and clean them up.
