### ISSUE TITLE
error loading plan

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#659]
![image](https://user-images.githubusercontent.com/955467/77122203-447cee00-69fa-11ea-8df0-9d5527cb9eef.png)

@calebissharp

**Comment by calebissharp** [comment]
@micheal-w-wells Any more context here? Do you always get this error? Or does it only happen after doing a certain action?

**Comment by micheal-w-wells** [comment]
haven't had it in a couple days @calebissharp

**Comment by micheal-w-wells** [comment]
@ZoeSimon test # 2

**Comment by micheal-w-wells** [comment]
/remind me to close next week if this doesn't happen again
