### ISSUE TITLE
Versioning problems (multiple copies of current version all I can view)

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#662]
@calebissharp — it is hard for me to accurately test amendments until this is fixed
Ex. RAN099952
- original version created March 23rd —> approved
   - schedule description said something like “Schedule description 2020)
- amendment started and discarded March 23
- amendment started and draft saved on March 24th

Note that all the versions visible for this RAN are exactly the same (date, status, content) — apparently the most recent version. 

I was surprised that there appears to be a version for the discarded amendment (no other way for there to be three versions)
I’m pretty sure the approved RUP had a schedule with about 6 rows but I can’t get at that one anywhere (there seemed to be something strange happen when I started an amendment that deleted the schedule rows but I can’t verify)

**Comment by calebissharp** [comment]
Just to clarify, what do you mean by "multiple copies of current version all I can view"? Are there multiple plans appearing in the work queue?

**Comment by LisaMoore1** [comment]
One version in the work queue but if I go to version page there are multiple versions...but while they are called (for example v1, v2 and v3) they are all showing the most recent version (V3 in this case). 
I cannot easily tell what the current approved version is nor can I view it (if I could find it) since all versions available are the same. This is the case even if the most recent version is an in-progress amendment.

**Comment by calebissharp** [comment]
@LisaMoore1 So if I'm understanding this correctly, this issue is a couple of things:
1. There is a missing version for the original RUP you had on March 23rd before creating an amendment. It should be v1, but instead v1 is the current version of the plan
2. The amendment you created and then discarded on March 23rd appears to have a version associated with it, although that version is also just a snapshot of the current plan.

Does that seem right?

**Comment by LisaMoore1** [comment]
@calebissharp That seems right. 
@micheal-w-wells If I had access to the data  I’d check to see if those other versions actually exist (it makes me uneasy when I can’t see the previous versions). I’d also look to see if the approved version had rows in the schedule because I need to trouble shoot if the schedule rows are getting dropped when an amendment is started or if that was a one time weird-o glitch.

**Comment by calebissharp** [comment]
@LisaMoore1 I can reproduce. From what I gather, the correct snapshots are all in the database, but the endpoint to actually retrieve the version isn't retrieving the right one. I'm going to do a bit more digging.

**Comment by calebissharp** [comment]
@LisaMoore1 Ok, should be ready for testing.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 we need to set up metabase for test I'll make an issue so we can sort it.   Will be handy for @calebissharp and @ZoeSimon too.

**Comment by micheal-w-wells** [comment]
I can check for you after lunch myself in meantime,

**Comment by micheal-w-wells** [comment]
There was 1 plan record and 3 snapshots for this RAN, which now belongs to @ZoeSimon .

**Comment by LisaMoore1** [comment]
@calebissharp and @micheal-w-wells. Ex. RAN099912

Worked a plan through to approved (approved at 11:28 today)
Started an amendment — not yet signed so still in progress (amendment was started sometime right before noon)

Here are the images I see (just the top of the screen) when I select those versions.  
![F3BFBB0F-3EA1-4BB5-9633-CD6EEF3D8012.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/6c2362c4-3cf0-42b0-9eaf-e2dc1c5768b9)

![732F69B9-0281-4995-85DB-8A6C3140F4B6.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/98b23d3b-722b-4598-b5ab-0a38562823e7)

Additionally, when I am to select a version it would be helpful if I could see something about the version when I’m making a selection. Once there are many versions V1, V2 etc. won’t mean much to me. Perhaps a date showing with the V#?

![6084127D-4E80-48AD-A35F-554F597699BD.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/44850823-2a3f-40e5-b0d8-9ed5a4306738)

**Comment by micheal-w-wells** [comment]
Thanks @LisaMoore1 so at very least plan status isn't getting versioned properly, or that preview is only pulling the current one.  I'll dig.

**Comment by micheal-w-wells** [comment]
@calebissharp what's the psql CLI safe way to query `plan_snapshot` without it screwing up my terminal?

**Comment by micheal-w-wells** [comment]
i'm ok with a big blob of json to copy paste an format somewhere, but it doesn't even display that I just get a blank screen.

**Comment by calebissharp** [comment]
@micheal-w-wells Not sure.

**Comment by calebissharp** [comment]
@micheal-w-wells Can you also verify API changes are making it to test?

**Comment by micheal-w-wells** [comment]
@calebissharp im ok to remove the unresolved label here now right?

**Comment by calebissharp** [comment]
@micheal-w-wells Yep, thanks.

**Comment by LisaMoore1** [comment]
@micheal-w-wells can you please look at the two versions of the RUP for RAN099912 to see if there are differences.  I thought when I made V2 the amendment was in the IP-other field (or maybe schedule description) but I’m not seeing any obvious differences between the two versions I can get at from versions.  Thanks.

**Comment by micheal-w-wells** [comment]
on it

**Comment by micheal-w-wells** [comment]
They are the same.  @calebissharp I think there's some digging to do around when a version gets created, the theory here (that I will test after next meeting) is it made a version when it was approved, and made another (as if it hadn't made the first one on approving) right when you said you wanted to start an amendment.

**Comment by LisaMoore1** [comment]
@micheal-w-wells I think this one is fixed (for example I noticed that RAN099953 there is a difference between V1-2 and V3-4) although I am unable to test this in real time until amendment option is back in place. If things look good can you please either close or let me know and I will? Thx.
