### ISSUE TITLE
History flow (top of RUP) isn’t generating an entry when an amendment is started

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#665]
Somehow we need to be able to tell that the RUP we are looking at/working on is an amendment.
Allowing the history to be built on for the version that is a result of an amendment (with the history remaining the same for the pre-amendment versions) would be one useful way of doing that.

**Comment by calebissharp** [comment]
This may require us adding an amendment column to the `plan_status_history` table, as well as changing some of the status endpoints.

**Comment by LisaMoore1** [comment]
Would be OK to have an amended version with a history that:
- starts with an entry that amendment was generated
- prompts whoever starts the amendment to provide a comment on what the amendment is about 
- that comment is displayed in the history

Maybe something to consider at the same time since the workflows are so interconnected:
- when submitting a new RUP to AH we’ve had several requests that the staff person be able to enter a comment (like when requesting/responding to feedback) to provide info on what needs to be done (I think we had/have an issue for that as an enhancement)
- mandatory amendments and new RUPs are essentially the same except one is started from a blank RUP and another is started from a “copy” of the most recent legal

**Comment by calebissharp** [comment]
@LisaMoore1 I think this is worth revisiting based on the new amendment statuses. Let me know if that fits the requirements here. I've also reduced the estimate to 0 here since that effort was capture elsewhere.
