### ISSUE TITLE
signing out auto signs back in 

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#667]
Trying to click sign out doesn't work, it logs me right back in.

@LisaMoore1 @calebissharp anyone notice this one?

**Comment by calebissharp** [comment]
Not so far, no.

Hard to tell if this is on our side or SSO's, especially if it can't be repro'd.

**Comment by micheal-w-wells** [comment]
gonna close unless you get it, i muck with my role in sso lots so could have been me ruining my cookies.

**Comment by calebissharp** [comment]
Sounds good.
