### ISSUE TITLE
Identify issues to do needed for next release

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#668]
Creating this for @ZoeSimon to learn what's up and going to get deployed soon.

**Comment by ZoeSimon** [comment]
- [ ] this one
- [ ] #657

**Comment by micheal-w-wells** [comment]
@ZoeSimon I gave you RAN099911, RAN099951 and RAN099952 to test.  You and @LisaMoore1 might want to make some more dummy RANS in test FTA prior to our data refresh in test so there's an abundance to go around.  In meantime ping me to delete plans or move them between you.

**Comment by micheal-w-wells** [comment]
Couple more:
- [ ] test #662 
- [ ] test #637

**Comment by micheal-w-wells** [comment]
- [ ] #674 - side effect of work on #562 .  @LisaMoore1 is this one a 'fix before next release' or should we chip away at above list first?  If it can wait we'll strike it from this list.

**Comment by micheal-w-wells** [comment]
@ZoeSimon can. update 638 to be 'need to test'

**Comment by LisaMoore1** [comment]
@zoesimon @micheal-w-wells 
It might be worth saving  this issue into an epic and then adding the issues to the epic so that as they get closed you don’t have to also check the box.  See #471 for an example (older when I was experimenting with this).

**Comment by ZoeSimon** [comment]
Closing this issue because we have all items captured in #688
