### ISSUE TITLE
Statuses related to workflow need to follow amendment related principles

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#684]
When AH has started an amendment the status in staff WQ is displaying “submitted to AH” — not accurate 

Staff shouldn’t see anything different than approved until the AH actually submits an amendment.  

AH is seeing “add content to RUP” which is OK but not ideal since it doesn’t indicate that there is an amendment in progress

- [ ] until an amendment is submitted the “other” (not amending) party is not aware of the amendment
- [ ] until an amendment is submitted the “other” party is not able to view any draft content
- [ ] users should always be able to tell that the plan they are working on/viewing is related to an amendment (versus a draft that has not yet reached approval)
- [ ] once a plan has been approved every version thereafter is an amendment until expiry date of approved plan is reached

**Comment by micheal-w-wells** [comment]
The viewing of other persons drafts relates to #683

**Comment by micheal-w-wells** [comment]
I think the content part of it is covered (can't see changes people are making), but the statuses might give it away because at this point the current plan still dictates that.  I'll address that with this issue.

**Comment by micheal-w-wells** [comment]
"until an amendment is submitted the “other” (not amending) party is not aware of the amendment"

We can't do this unless we hide the amendment button for the other party.  How do we tell people why the button isn't there if they aren't allowed to know why?

**Comment by micheal-w-wells** [comment]
I think what we agreed to the last time we spoke @LisaMoore1 was to hide in progress work but not the statuses, and let the button behavior stay as is and see how it plays out.
