### ISSUE TITLE
Versioning and Client Linking Release

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#688]

**Comment by calebissharp** [comment]
@micheal-w-wells I think we'd want to add https://github.com/bcgov/range-api/issues/157 to this, since #418 (which is already here) depends on it.

**Comment by micheal-w-wells** [comment]
@calebissharp if you need a break from manage clients or something to do right after, I think #709 needs to get addressed prior to deploying.

**Comment by micheal-w-wells** [comment]
This is deployed and I'd call what Oamar is working on extra features.  I'm good to close this @LisaMoore1 if you are so it kind of lines up with release day.
