### ISSUE TITLE
"Something went wrong" when clicking on plan as AH and Staff

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#689]
Both @ZoeSimon and I got this logging in as AH and clicking a RAN to edit.

Fixes it after a refresh or navigating away and back.

FYI. @LisaMoore1 @calebissharp

**Comment by micheal-w-wells** [comment]
![image](https://user-images.githubusercontent.com/955467/77932928-0c2fa800-7263-11ea-909f-a91742980241.png)

**Comment by micheal-w-wells** [comment]
@calebissharp 
![image](https://user-images.githubusercontent.com/955467/77933065-3da87380-7263-11ea-9935-cbc438be8035.png)

**Comment by micheal-w-wells** [comment]
Can you help me nail down what's going on with these? @ZoeSimon  and I were both getting it on friday and I'm getting it today, would be good if we don't push out an update that causes staff to get this page all the time.

**Comment by LisaMoore1** [comment]
I got this on Friday as well — first plan I tried to create. After refreshing I didn’t get it again for any plans I created — I tried.  Figured it was a connectivity thing but maybe not...

**Comment by LisaMoore1** [comment]
And I just got it immediately after signing in with my IDIR but before seeing any of my WQ

**Comment by calebissharp** [comment]
I think it's an issue with it trying to use data before it's been fetched and stored in local storage. When you refresh it's because it's now in local storage and can access it. I bet this happens every time after you clear the cache?

**Comment by LisaMoore1** [comment]
This morning after clearing cache and I got it immediately after signing in with my IDIR but before seeing any of my WQ as well as when signing in as AH using BCeID. Friday was the first time I noticed it logging in post cache clear so not sure there.

**Comment by micheal-w-wells** [comment]
@calebissharp if that's the case how big of a task is it to check if there's no cache and wait for the first fetch?

**Comment by calebissharp** [comment]
@micheal-w-wells It's not really possible to _wait_ for the request to go through (React doesn't like render-blocking) but it is possible to add some more resiliency to the components that consume that data. They should be more explicitly checking the data is wants is defined, instead of assuming it is and throwing errors when it isn't.

**Comment by calebissharp** [comment]
@micheal-w-wells I may have this resolved, but let me know if it shows up again.

**Comment by micheal-w-wells** [comment]
So far so good for me.   Had to clear cache to get it to take effect.  @LisaMoore1 @ZoeSimon until we do #537 it might be helpful to know you can just clear cache for myrange and not everything in your browser.  @calebissharp might know an even easier way but what I have been doing recently is:

1) Right click page anywhere, hit inspect.  This opens the dev console
2) Now when i right click the regular page refresh button in the top right, there are new options.  One is hard refresh and reload.
