### ISSUE TITLE
Bring back homescreen RUP preview

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#700]
The home screen used to let people see a list of RUPs for a given RAN and some details about them.  Even though we are going to 1 RUP to 1 Agreement, it would be useful to use this preview for versions.   Most important is knowing the legal status (which one is legal) and if its a previous one what was the legal term (start and end date).

**Comment by LisaMoore1** [comment]
@micheal-w-wells Do you need me to provide any info here or do our discussions/other versioning work cover the need here to know which is legal etc?

**Comment by micheal-w-wells** [comment]
My understanding right now @calebissharp @okanji  is it should, besides the obvious stuff like what's displayed for them now (RAN, Range name, etc), show:

- status: Approved, Amended etc 
- who did it
- the legal term (start and end)*

*Note for devs: Perhaps not necessarily how long this version existed until the next, you need to look ahead to next version in an  approved state.  We won't have just approved versions now because of #683.  I think we might need to make a view `snapshot_summary` that has `snapshot_id`, `plan_id`,  `is_staff_view`, `is_AH_view`, `status_from`, `status_to`, `made_by_user_id`, `isLegal`, `wasLegal`, `legal_start_date`, `legal_end_date`.  Some of this is just for me troubleshooting, but some of those would make this ticket easier.

@LisaMoore1 If you've got any others this is the place to dump em : ).

**Comment by LisaMoore1** [comment]
@micheal-w-wells This looks good to me. Just like I think it is important to easy to see the current legal I think it is important to see what is “in progress”. 

**Final Statuses**
- 11-Not_Approved
- 12-Approved
- 7-Wrongly_Made_Without_Effect
- 8-Stands_Wrongly_Made
- 9-stands
- NB: the minor amendment status “stands” should be identified as a final status but it could be deemed wrong by the DM at a later date

**In-progress Statuses**
- everything else

**Comment by micheal-w-wells** [comment]
@okanji this one isn't showing the legal ones as green for me, did the new var get incorporated to your changes?

I'd add the Reason column also, its the context for each record.

**Comment by micheal-w-wells** [comment]
Looks great to me - going to leave it open though I'd like @LisaMoore1 to have a place to stick feedback when she is well and able to check it out.

**Comment by micheal-w-wells** [comment]
Looked again and I think the next step with this one is to make them hyperlinks to the versions themselves, to save people from opening the plan, going to the versions page, and clicking the dropdown.  Appearance-wise it is awesome so far.

**Comment by LisaMoore1** [comment]
@micheal-w-wells I agree.  The appearance is great.  I do have a question about times. I know we’ve talked about them before and time zones and what not and I can’t keep it straight.  I noticed in the WQ version list that expiry date for current one shows 12:00 am. That looks a little weird as I think we normally go end of day (Like 23:59). Overall I’m not sure that the time adds anything here in this list and it could probably be hidden. Not even remotely a blocker though.  

I love being able to see what I want without all of the “clicks” to get to the version page. Would love to have a hyperlink to go straight to the version but would happily release as is with these things a s enhancements. Want me to close this?

**Comment by okanji** [comment]
> Looked again and I think the next step with this one is to make them hyperlinks to the versions themselves, to save people from opening the plan, going to the versions page, and clicking the dropdown. Appearance-wise it is awesome so far.

I have created a PR for this #830
