### ISSUE TITLE
Introduce new status for Mandatory Amendment In Progress

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#702]
relates to  #684

**Comment by calebissharp** [comment]
I think an existing solution to this and #701 is to look at the existing `amendment_type_id` column in `plan` to determine if the plan is an amendment.

**Comment by micheal-w-wells** [comment]
As long as from the users perspective it is as accessible as plan status, it should be on the home page list view and the user should know what stage in the process the amendment is at.  I think indicating the stage in the process is really important and wasn't really captured when I made these issues, but it needs to happen somehow.

How it gets implemented I'm flexible on, but in my opinion a new round of statuses means the home page would display everything they want and sort, and we would maintain our 2:1 ratio for header descriptions to statuses without complicating things there (beyond adding to the list).

Does this info help paint a picture of the need here?

**Comment by calebissharp** [comment]
Resolved by #771
