### ISSUE TITLE
Add some more information to version select options

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#704]
Not sure what date is in there (version created, plan approved) or if its working as the date has no label.

**Comment by calebissharp** [comment]
This issue will no encompass a couple other things:

* Display a label the current legal version 
* Show a date range the plan was legal for

**Comment by micheal-w-wells** [comment]
@calebissharp @okanji please also include the plan status at the time and who got it there, e.g., 'Approved - Lisa Moore'

**Comment by micheal-w-wells** [comment]
Stuff to display:

is current legal version <-- should just be an indicator on one.
effective legal start date
effective legal end date
created by user
status

other stuff from endpoint:
version/snapshot id
version #. 

endpoint /plan/?/versionsummary

**Comment by micheal-w-wells** [comment]
RAN01. - Legal period (1999 dec - 2004 jan)    -  Wrongly Made (STANDS).   -   Lisa Moore.  -View

**Comment by micheal-w-wells** [comment]
@okanji ping me when you have time to work on this (and the home screen preview thing).  I might try to get a poor man's version of the select list that is there working with legal start and end dates,  so we can slam a release out then let you carry on with the home screen thing and making this one better.

When 727 is done I can help you again learn to make test data to do this.

**Comment by LisaMoore1** [comment]
@okanji I like the update however there is a bit of an issue where there is a “stands” status (there are a couple of those) as they can be current legal but in current version their status isn’t showing so everything looks greyed out. I wonder if the status should be shown for these. @micheal-w-wells may have suggestions here. 
![IMG_7878.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/a5ff2779-b2a9-4384-bdf4-e9ea60297ffb)

**Comment by okanji** [comment]
@LisaMoore1 @micheal-w-wells how does this look? I decided to use same **status** component that has been used elsewhere in application. I have tried to make the current legal version stand out by colouring the avatar and the approved dot while greying out the other versions.

Does anyone have an RUP number that has multiple versions? I would like to take a look and see what the different statuses look like. As shown above, I could only find versions that had a status of approved. 

![image](https://user-images.githubusercontent.com/30703259/80265599-f1c3d100-864c-11ea-9c4b-01a3ba3dcefa.png)
![image](https://user-images.githubusercontent.com/30703259/80265646-13bd5380-864d-11ea-88fd-55d84a1cd8dd.png)

**Comment by okanji** [comment]
> @okanji I like the update however there is a bit of an issue where there is a “stands” status (there are a couple of those) as they can be current legal but in current version their status isn’t showing so everything looks greyed out. I wonder if the status should be shown for these. @micheal-w-wells may have suggestions here.
> ![IMG_7878.jpeg](https://camo.githubusercontent.com/0569d816ec985caba37c2ef4bad56da99ae8622f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564393337313631633865346438303030313232373838312f61356666323737392d623261392d343338342d626466342d653965613630323937666662)

@LisaMoore1 thanks for the detailed feedback, the version above that I have shown a screen shot of seeks to address your suggestions

**Comment by micheal-w-wells** [comment]
LGTM.  Best way to get @LisaMoore1 is to go ahead and PR to dev, get either @calebissharp or myself to review and then mark the issue (not the PR) as ready to test and put in the QA column.

**Comment by LisaMoore1** [comment]
@okanji See #760 for some comments/screenshots on this. Might be something to talk to @calebissharp and @micheal-w-wells about as I think this is touching on a few things about how we identify/categorize different statuses so it is clear to users what they are looking at.

**Comment by micheal-w-wells** [comment]
I think our recent api changes should have fixed this one.  I don't think there's any change for Oamar here.

**Comment by LisaMoore1** [comment]
@micheal-w-wells Noticed a couple of funky things here.  Not sure if they are related to this issue or not. Can you take a look? 
![IMG_7955.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/94780c3e-8a8f-49a8-981f-136280721d32)

- [ ] legal start/end don’t need time (might help avoid the overlap) although it is useful during all of this testing
- [ ] once an amended plan hits “stands” as far as users are concerned it “stands” whether it is reviewed or not. 
   - if changed to wrongly made it is still THE SAME amendment
   - the legal start and end date remain the same
   - no changes have been made between stands and 
   - displaying the various versions (especially with different start/end dates/times make it seems like there are multiple amendments
   - [ ] can we somehow just show the most recent version of an amendment? If we had history capturing all status changes looking at that version would give us the whole picture

**Comment by calebissharp** [comment]
@micheal-w-wells I think because the plan can't be edited in any "stands" statuses, we can ignore every status when finding legal versions, **except** "Stands - Not Reviewed", because it's always the first one.

> can we somehow just show the most recent version of an amendment? If we had history capturing all status changes looking at that version would give us the whole picture

@LisaMoore1 Maybe I'm misunderstanding, but isn't this the same as looking at the plan from the main plan page, at least while there is an amendment in progress? Then once the amendment is completed, it will appear in the versions list as "Stands" or just "Approved".

**Comment by LisaMoore1** [comment]
@calebissharp Yes I think that is right — main page shows the most recent. The thing that confuses me is when I look at the version list and I see all of the versions associated with that single amendment when really the most recent one (provided all the status changes are showing up in history) tells me everything I need to know — and is more clear that it is all associated with a single amendment.

**Comment by micheal-w-wells** [comment]
i'm gonna make my afternoon goal find a way to make amendments less confusing in the version list, i think i have an idea of how to go about it
