### ISSUE TITLE
Can't get past "Confirm submission" screen when trying to submit RUP to AH in test environment

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/range-web#711]
Not able to submit a RUP in staff draft to the AH as I can get past the "Confirm Submission" screen. Showing the loading circle, but not moving forward from there. 

![Capture.PNG](https://images.zenhubusercontent.com/5e78e949a7e29c75200dbef5/fa4376fe-f0ce-475a-a42e-bb2976254488)

![image.png](https://images.zenhubusercontent.com/5e78e949a7e29c75200dbef5/679dcee1-be24-4e4c-8a88-f424b179f06f)

**Comment by micheal-w-wells** [comment]
its been fixed
