### ISSUE TITLE
Pasture no longer linked to schedule row

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#712]
At least that's how it appears on the page, on the PDF it's fine.  

![image](https://user-images.githubusercontent.com/955467/78275256-359c3e00-74c6-11ea-92f5-85b6be32e123.png)

**Comment by micheal-w-wells** [comment]
Also other plan actions are blocked

**Comment by calebissharp** [comment]
I think this is a duplicate of #611, which was resolved.

**Comment by micheal-w-wells** [comment]
thanks
