### ISSUE TITLE
Schedule rows re-ordering after save

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#714]
AH-add content
- enter schedule by adding rows manually then save = row order maintained after save
- enter schedule by duplicating a row then save = rows reordered
- reorder rows using the reorder feature then save = rows stay in order

**Comment by micheal-w-wells** [comment]
I'm hoping we can drag this one in to next sprint @ZoeSimon @LisaMoore1

**Comment by ZoeSimon** [comment]
Schedule rows are still re-ordering after entering manually and hitting save:
![image](https://user-images.githubusercontent.com/62561887/88595024-1b5b1280-d017-11ea-8d39-8c3950f46174.png)

But after using the toggle feature (for either the pasture or date) and hitting save they stay in the correct order.
