### ISSUE TITLE
As AH open plan for first time and get error 

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#715]
![image](https://user-images.githubusercontent.com/955467/78819541-43046d00-798b-11ea-997c-b2d814f2eb7a.png)

**Comment by micheal-w-wells** [comment]
Not currently in prod.

**Comment by micheal-w-wells** [comment]
@LisaMoore1 i got this locally but if you have time to test today can you see if you get this in Test?  Make a new plan as staff - try to open as AH.

**Comment by LisaMoore1** [comment]
@micheal-w-wells Just did RAN099955 from staff to AH and didn’t generate an error.

**Comment by micheal-w-wells** [comment]
maybe was just me then.  weird.

**Comment by LisaMoore1** [comment]
@micheal-w-wells I tested this today and wasn’t able to generate error. You happy closing?
