### ISSUE TITLE
Error on first attempt to sign as AH and Recommend Ready as Staff

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#719]
In both cases going back to the plan and trying again works.

signature error:
![image](https://user-images.githubusercontent.com/955467/79367901-70a96300-7f03-11ea-9392-8bc85899366c.png)

recommend ready error:
![image](https://user-images.githubusercontent.com/955467/79367929-7bfc8e80-7f03-11ea-87b1-9514680b925a.png)

@calebissharp

**Comment by LisaMoore1** [comment]
@calebissharp I got an error message logging in as Leslie.knope to sign originally but I think it was a connection speed thing (there was a super long delay). I logged her out, did another Draft plan and couldn’t replicate. Also moved plan through to approved using recommend ready and didn’t get an error. Closing this one.
