### ISSUE TITLE
saving a plan for very first time gives bad url and 'don't see a plan?' message 

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#723]
steps to reproduce:  create new plan > enter range name, start and end date, hit save:

![image](https://user-images.githubusercontent.com/955467/79708210-a63bac80-8273-11ea-82b0-e61b9e8c0c9f.png)

@calebissharp fyi

**Comment by calebissharp** [comment]
@micheal-w-wells Does this issue appear when you're using the latest changes in `dev` for `range-web`/`range-api`? I want to rule out this being an issue with your unmerged changes. Alternatively, are you using the `dev` endpoint or a locally running one? If you're using `dev`, we should make sure all migrations have been run there.
