### ISSUE TITLE
RUP signing doesn't work due to client linking changes

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#727]
![image](https://user-images.githubusercontent.com/955467/79905217-c29e2d00-83ca-11ea-863c-0caee1240b15.png)

Migrations are run, let me know if there's anything else of value from the db for ya @calebissharp

**Comment by calebissharp** [comment]
Looks like I forgot to update the signing code for multiple linked clients. We'll use this issue to track that.

**Comment by LisaMoore1** [comment]
@calebissharp This didn’t show up for me today in my various attempts to sign things. Anything I should now that running those flows wouldn’t test? If not, please either close this one or let me know and I’ll do it. Thx.

**Comment by calebissharp** [comment]
@LisaMoore1 Nope, I think this one is ok to close.
