### ISSUE TITLE
Staff can initiate Mandatory Amendment

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#730]
- [x] mandatory is the only type of amendment a staff person can initiate
- [ ] requires a button for staff to initiate a new version (amendment)
- [ ] amendment can only by built off of current legal versions (not old or amendment in progress version)
- [ ] staff may choose not to change any content but their message to the AH may indicate what the required changes are
- [ ] all workflows beyond initiation follow same workflow as for original RUP (but it should be clear it is an amendment in progress)
- [ ] submit for feedback and submit for decision workflows/options apply
- [ ] recording recommendation to DM and DM decision apply (interim to DM workflow)
- [ ] headers need to reflect amendment language 
   -  ??Does that mean they should all be made more generic or review all and make more specific for amendments? 
- [ ] Staff can discard an amendment they start any time BEFORE they send to AH

**Note**
- other situation a staff person may need to create a new version are: (a) at time of RUP expiry or (b) when all (or a portion of information) is copied to a different RAN (usage and schedules can only be copied if both RANs have same usage info)
- (b) is a separate fairly infrequent scenario for down the road...maybe

**Comment by calebissharp** [comment]
@LisaMoore1 Just to clarify one thing, when staff presses the button to create an amendment, should it then move to a status like "Staff draft", where they have editing control? Or should it be sent directly to the agreement holder? I'm assuming the former option, since you state that staff should have the ability to discard the amendment before sending it to the AH.

**Comment by LisaMoore1** [comment]
@calebissharp After pressing button to start mandatory amendment:
- staff should have ability to make changes to RUP (CRUD)
- add a comment describing what the amendment is about/what AH needs to do (like when providing feedback)
- submit to AH
