### ISSUE TITLE
Versions list should only show approved versions

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#735]
Version list will only show versions that were or are legal.

**Comment by LisaMoore1** [comment]
@micheal-w-wells Warning: amendment related comment to follow. If they aren’t relevant at this point in time then this issue can be closed. Let me know?

Question 1: amendment in-progress related
If we are only showing approved (I’m assuming this includes the “stands” statuses), what will happen when an amendment is in progress? How will the user be able to access both their previous versions and their in progress amendment?

Question 2: not-approved amendments
As part of the history it will be important for staff/AHs to see (when that is what they want to do) things that were not approved/allowed to stand.

**Comment by LisaMoore1** [comment]
@micheal-w-wells I see your comment on #738 so think you are probably all over this and it can be moved to closed. If so you can either just close it or let me know and I’ll do it.
