### ISSUE TITLE
Error generating a PDF 

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#739]
**Describe the bug**
Log in as either AH or staff (for sure while it's in Submitted to AH, perhaps other statuses) and generate PDF.

**Expected Behaviour**
It should work.

**Actual Behaviour**
![image](https://user-images.githubusercontent.com/955467/80136377-74b63000-8556-11ea-9cb3-2aac89555878.png)

**To Reproduce**
Create a plan as staff
Submit to AH
Try generating PDF as staff
Log in as AH
Try generating plan.

**Screenshots**
![image](https://user-images.githubusercontent.com/955467/80136432-8a2b5a00-8556-11ea-9899-124be54d01bc.png)

**Additional context**
It seems to work for approved ones.   Not 100% sure on which statuses are broken other than 'Submitted to AH'

@calebissharp probably a release blocker

**Comment by LisaMoore1** [comment]
@micheal-w-wells @calebissharp I moved RAN099914 (the one I originally noted the PDF error on) all the way through to approved and am still getting the PDF error. Just thought you might want to know.

**Comment by calebissharp** [comment]
@micheal-w-wells Do you have an errors in your console?

**Comment by micheal-w-wells** [comment]
@calebissharp 
![image](https://user-images.githubusercontent.com/955467/80153289-15feaf80-8572-11ea-8881-8ecc262e8687.png)

Be Leslie in test and open RAN099914.

**Comment by micheal-w-wells** [comment]
Looks like this one had issue once it was approved so it seems plan dependant not status dependant.

**Comment by calebissharp** [comment]
Yep, looks like at least one of the things causing it is when you have a monitoring area with rangeland health not set.

**Comment by LisaMoore1** [comment]
Rangeland Health used to be a required field but we’ve changed that.
