### ISSUE TITLE
Implement new headers for amendments

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#753]
As staff and AH i should get headers specific to where I am in the amendment process.

**Additional Context**
- see #752

**Comment by calebissharp** [comment]
@LisaMoore1 Can you provide some header text for the "Submitted as Mandatory" status?

**Comment by ZoeSimon** [comment]
@LisaMoore1 Please review this ticket

**Comment by LisaMoore1** [comment]
SUBMIT AS MANDATORY 
Staff have initiated this mandatory amendment based on a minor amendment that, while deemed wrongly made, could be considered for decision as a mandatory amendment.
