### ISSUE TITLE
Update status component to include amendment info

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#755]
**Describe the task**
Some of the amendment statuses are the same as regular in progress RUP ones, update this component to show what stage of the amendment (and what type it is) so that the app displays the right information in the home page and elsewhere.

**Acceptance Criteria**
- [ ] Home page shows amendments in progress vs RUPS that just look like they were just started and in progress.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by micheal-w-wells** [comment]
- List of statuses and their codes  https://github.com/bcgov/range-web/issues/683#issuecomment-619226197
- Status text and header text from iOS app:   https://github.com/bcgov/range-web/issues/752#issuecomment-623613609

**Comment by micheal-w-wells** [comment]
Do a GET on the status endpoint and the plan endpoint and eyeball what the status object (the components output) looks like for an idea where to start.

**Comment by calebissharp** [comment]
For reference:

https://twostoryrobot.slack.com/files/UJJ72U8AH/FQFF5EFFF/myrangebc_content_control__2_.xlsx

**Comment by micheal-w-wells** [comment]
@okanji Caleb made the new statuses, but whats outstanding is the header text and there's a handy spreadsheet he pasted above, don't worry about all those ios repo links.

**Comment by calebissharp** [comment]
I think adding a little indicator for the status component is still a good idea though.

Something like this:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/8854811/81189336-4f202200-8f6b-11ea-804b-9274380e30bf.png">

**Comment by micheal-w-wells** [comment]
good call

**Comment by micheal-w-wells** [comment]
ignore my comment then about the header text, i'll do that as part of #753 right now , make this one what @calebissharp mentioned above

**Comment by calebissharp** [comment]
@okanji Are you working on this right now? If not, can I take it from you?
