### ISSUE TITLE
Add button for Staff to create a mandatory amendment

### ISSUE THREAD

**Issue by calebissharp** [bcgov/range-web#756]
**As a** *staff person* **I want** *to be able to submit a mandatory amendment* **So That** *I can ensure required changes are made to an RUP*.

**Additional Context**
- Workflow exists for agreement holders, button needs to be visible for staff as well.
- Status should probably go directly to Staff draft when the button is clicked, since staff only have the option to create a mandatory amendment.

**Acceptance Criteria**
- [ ] Given the plan is in an approved state, When staff presses the "Amend" button, Then the plan goes into staff draft and is now an amendment.

**Comment by LisaMoore1** [comment]
Button looks good.
I selected it —> nothing changed on the screen to indicate I had selected it and nothing immediately happened on the screen so I felt like clicking it again.
Not sure what would have happened if I’d selected it again while it was still thinking. 
An “I’m thinking about it” something would help (I think we had this discussion on the AH side of things too but not 100% sure).

**Comment by calebissharp** [comment]
@LisaMoore1 Looks like I may have forgotten to add the loading indicator for the button for staff, good catch. I'll add that in.
