### ISSUE TITLE
Implement “Review Not Required” or “Review Required" for staff in Minor Amendments

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#757]
Not sure if we need it before DM workflow.  @LisaMoore1 let us know please : )

Give staff options to either set RUP in 'review not required' or 'review required' for minor amendments.

*Acceptance Criteria**
- [ ] as staff, with a RUP with an amendment in progress in status 'Stands Review' I should have option to click 'review not required' or 'review required' and the RUP should go to the appropriate status.

**Comment by LisaMoore1** [comment]
This should be a standard option for all minor amendments whether we are using digital DM or paper DM (so it is recorded). When we do DM workflow “Review Required” would be the trigger for the determination workflow.

**Comment by micheal-w-wells** [comment]
@calebissharp before we take a stab at estimating, what if we migrated away from the 3 dots to buttons?  We could leave what is there now for the time being, but make new stuff be buttons.   I think we have enough real estate for the buttons needed in any given state, and the staff seem to like them.  Throwing that out there because you had mentioned changes to plan actions component is a convoluted process.

**Comment by calebissharp** [comment]
I want to look into the dropdown implementation first, to gauge the amount of effort that would be required. It may not actually be that bad. I'll keep in mind using buttons instead though. Although, I wonder if that might be a little tricky since this issue requires us to provide 2 options to the user.

**Comment by calebissharp** [comment]
@LisaMoore1 What would be the next status if you click "Review Not Required", and likewise for "Review Required"? And what status would you see this option in?

**Comment by calebissharp** [comment]
Talked through it with @micheal-w-wells, decided we need another status after "Stands" (the status where this option would appear) that the plan goes to after selecting "Review Not Required". We would use status "Stands - Review (20)" for when staff selects "Review Required". Does this make sense to you @LisaMoore1?
