### ISSUE TITLE
Give staff ability to choose Wrongly Made without effect for Minor amendment

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#758]
As staff with RUP with minor amendment in progress in status of Review Required I should have option to choose 'Wrongly Made without effect' .

**Additional Context**

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by micheal-w-wells** [comment]
Do we want to leave the current plan in 'wrongly made without effect' for an indefinite or finite period of time?  the legal versions will still be listed under versions (and eventually on @okanji 's beefed up home page component.

**Comment by micheal-w-wells** [comment]
Question for Micheal:  Do we need SAM?

**Comment by calebissharp** [comment]
When an RUP has a status of "Wrongly made without effect":
1. Display "Wrongly made without effect" as the status on the current plan
2. Provide buttons to staff and AHs to "Create amendment from legal version".
3. When button is clicked, we 
    1. snapshot this current plan
    2. restore the previous legal version into the current plan
    3. call the same API endpoints to create an amendment as we normally do. 
4. Plan goes into the amendment workflow and continues as normal.

@micheal-w-wells Did I miss anything here?

**Comment by micheal-w-wells** [comment]
Which amendment types can land here?  all 3?

Need to mark the restored plan as 'isRestored' so i have some kind of indicator to know to look at the last legal one for dates and ignore in version list.

**Comment by micheal-w-wells** [comment]
actually i guess if you are going directly to another status other than approved then we don't need the isRestored here.

**Comment by calebissharp** [comment]
Wrongly made without effect is only for minor amendments.

**Comment by micheal-w-wells** [comment]
I think you've got it covered then

**Comment by calebissharp** [comment]
@micheal-w-wells I've noticed another nuance with this. If an amendment is reviewed and determined to be wrongly made - without effect, we cannot use the "Stands" version that came before that as a legal version. Do you thing your view would have the ability to handle this? Or do we have to add this logic elsewhere?

**Comment by micheal-w-wells** [comment]
We do want the Stands one to still show in the list as a past legal version.  That part is ok.  The issue is an older one comes back and that is where things get weird.

I gotta stew on it.  I am not sure how we want to display it but I'm assuming we would want to show the history that

version 1 was approved, and legal from Monday to Friday
version 2 came along as Stands and was legal from Saturday to Monday
version 1 again became legal and is legal from Tuesday to the plan end date

**Comment by micheal-w-wells** [comment]
if @LisaMoore1 is ok with it, this would be so much simpler:

version 1 was approved, and legal from Monday to Friday
version 2 came along as Stands and was legal from Saturday to Monday
version 3 looks just like version 1, and it became legal and is legal from Tuesday to the plan end date

**Comment by LisaMoore1** [comment]
@micheal-w-wells What status is version 3 in this example? No review required, review required, DM decision made.... Not sure how to provide you with useful info on this one.

**Comment by micheal-w-wells** [comment]
same as v1, all good i should have written it this way the first time:
version 1 was approved, and legal from Monday to Friday  (Status Approved 12)
version 2 came along as Stands and was legal from Saturday to Monday (Status Stands, not sure on number off hand)
version 3 looks just like version 1, and it became legal and is legal from Tuesday to the plan end  date (Status Approved 12)

**Comment by LisaMoore1** [comment]
@micheal-w-wells Still a little confused.
Versions 1 and 2 make sense to me however a minor amendment that had been in a “stands” status (minors are the only ones that have stands statuses) of any sort wouldn’t go to approved (12) status since “approved” applies only to original RUPs and mandatory amendments. 
A minor amendment, after being submitted by the AH (stands) would go to one of: stands-reviewed, wrongly made- stands, wrongly made-without effect or submit as mandatory amendment. If it either stands-reviewed or wrongly made-stands it continues as the current legal. 
Along with wrongly made-without effect the DM (when we do that workflow) may choose to indicate that a suspension of activities not authorized by the amendment is required.

**Comment by micheal-w-wells** [comment]
I admit its a bit tough without a visual aid. 

step 1.   Initial RUP approved, legal version created and is current.    You only see this record in the version list.  And it will say 'initial RUP approved' in that list.

step 2.   A minor amendment hit stands, legal version created and is current.  There are now two records in the legal version list, and this one is indicated with 'AH minor amendment' or similar


step 3.   Current plan went to wrongly made without effect, meaning the stands version isn't current legal version anymore.  The legal version should look just like the one from step one.  The version list will look like:

v1.  Initial RUP approved     (start date - end date)
v2.  Minor amend stands  (start date - end date)
v3   Minor amendment wrongly made, previous RUP restored  (start date - plan end date).   This one essentially is a copy of v1, but you get context here.


We copy the one from step one forward, nothing from the minor amendment comes along, but the context is there from the list.  

Hopefully that isn't more confusing

**Comment by LisaMoore1** [comment]
Yes this makes sense now with the addition of the “wrongly made without effect” explanation in v3. Thanks. Sorry for the sidetrack.

**Comment by micheal-w-wells** [comment]
all good glad we landed on something that will work : )

@calebissharp fyi

**Comment by calebissharp** [comment]
Just a heads up, this is blocked for me until #759 is resolved since I need the `is_legal` column (https://github.com/bcgov/range-api/issues/202).

**Comment by LisaMoore1** [comment]
This seems to work — I have some problems with versions info still. WIll cover my questions elsewhere (version issue somewhere) and close this one.
