### ISSUE TITLE
Give staff ability to submit as a mandatory amendment (when minor amendment is in Stands - Review)

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#759]
**Describe the task**
With a RUP with minor amendment in progress, and status of Stands - Review, I should have option to submit it as a mandatory amendment.

this kicks it back to staff to a staff initiated mandatory amendment process

**Acceptance Criteria**
- [ ] "Submit as Mandatory" button appears for staff in "Stands - Review"
- [ ] Plan is editable when status is "Submitted as Mandatory"

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by micheal-w-wells** [comment]
Need to know if we need to track that it was originated from a minor amendment (hoping no).

**Comment by calebissharp** [comment]
@LisaMoore1 Is staff choosing "submit as mandatory amendment" the exact same as starting a new mandatory amendment, ie. the status would be changed to "Staff Draft" and the amendment type would change to mandatory? Are there any other things we need to change or track?

**Comment by calebissharp** [comment]
@ZoeSimon Any thoughts?

**Comment by ZoeSimon** [comment]
@calebissharp @micheal-w-wells I'm not super sure on this one as I'm not familiar with the mandatory amendment workflow (i.e. I never did one as an agrologist and have only heard about them with a loose understanding of how they work)... I suggest we have @LisaMoore1 provide her input for this one. I'm just trying to re-read all the info tickets around Major Amendments and see if I can find anything in there.

**Comment by LisaMoore1** [comment]
Switching to “Submit as Mandatory” is an option when you get to the DM determination part of the workflow (has to go to DM first). In this case I see the flow (I think) as:
- staff record DMs determination as “submit as mandatory amendment) = status update
- take the version that was created by way of AH minor amendment and either change the status (or make a snapshot/new version) that is identified as a mandatory amendment = status update
- staff submit it to AH with explanation of what is going on (staff act as intermediate step between DM and AH to provide explanation/prep)

As far as the AH goes — they don’t see anything except “stands” until staff submit back to them with details of having to resubmit as mandatory.

**Comment by calebissharp** [comment]
I'm thinking for that first piece, "status update", we'll have to add a new status. This will probably be how we'd track the plan was a minor amendment before, and staff will submit it from this status back to the AH.

**Comment by ZoeSimon** [comment]
Hey @calebissharp I was testing this ticket and at no point as range staff was I able to submit it as a major amendment from the AH initiated minor amendment when it was in the "Stands - review" status. As range staff I tried selecting "Stands - wrongly made" (which obviously just allowed it to stand with no further actions available), and then I tried "Wrongly Made - without effect" and it ended up wiping my plan completely (I'll create a separate ticket for this one as it looks like a bug). Am I missing something or misunderstanding something on this one?

![image](https://user-images.githubusercontent.com/62561887/81593814-d3f8aa80-9374-11ea-9bb7-7102acb71201.png)

**Comment by calebissharp** [comment]
@micheal-w-wells Can you check the pipeline when you get the chance?

**Comment by micheal-w-wells** [comment]
on it

**Comment by micheal-w-wells** [comment]
LGTM

**Comment by LisaMoore1** [comment]
@calebissharp 
- Button is visible (expected)
- selecting it raises confirmation screen (expected)
- new version is not in editable form (unexpected as confirmation screen said it would be)
- history says “Review Amendment —> Submitted as Mandatory” (expected as per statuses but “submitted” usually refers to changing hands from one user to other so maybe something like “change to mandatory” would be more clear what happened)
- there is no header at the top of RUP when it reaches “submitted as Mandatory” status (unexpected — not sure if this is a miss or if we need to create language here...let me know)
- while staff has submitted to DM for review, changed to mandatory etc but not yet submitted to AH the AH is seeing all of the status changes (unexpected — AH should see the version they submitted “stands” all the way until there is actual a change in legal status or they need to take an action)
- when mandatory amendment submitted to AH the history no longer shows recent actions and the version list for both staff and AH is gigantic (unexpected but not sure what is happening...see images below)

**IMAGES**
Not Editable![IMG_7968.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/62070296-59a8-4c95-9467-85b36e80ebaa)

No header/“submitted as Mandatory” in history![IMG_7967.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/0747f7b6-f5a8-479d-aeba-6a60da621087)

AH seeing status changes related to staff actions ![IMG_7969.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/64babd04-22ac-4492-b18f-6fef963713a1)

Strange history status/dates/times (compare to image above — my writing is me trying to figure out what’s up) 
![IMG_7971.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/ad4b46f7-7c9e-4f50-bff7-6832e9d57929)

**Comment by calebissharp** [comment]
@LisaMoore1 Thanks for testing this! I've responded to your comments below:

> new version is not in editable form (unexpected as confirmation screen said it would be)

I've updated the acceptance criteria for this issue to include this.

> there is no header at the top of RUP when it reaches “submitted as Mandatory” status (unexpected — not sure if this is a miss or if we need to create language here...let me know)

Covered by #753

> while staff has submitted to DM for review, changed to mandatory etc but not yet submitted to AH the AH is seeing all of the status changes (unexpected — AH should see the version they submitted “stands” all the way until there is actual a change in legal status or they need to take an action)

I think this should be a separate issue. There's some cleanup we have to do with the status history in general, especially with the minor amendment statuses. I don't see it being a blocker to this issue. Let me know if you think otherwise.

> when mandatory amendment submitted to AH the history no longer shows recent actions and the version list for both staff and AH is gigantic (unexpected but not sure what is happening...see images below)

This sounds like two issues. I've created an issue for the first (#792), and the second already exists as #791.

**Comment by LisaMoore1** [comment]
@calebissharp All of the above makes sense. I agree that AH seeing status changes isn’t a blocker but I think it does need to be addressed at some point (@micheal-w-wells). Do you want me to create a separate issue for that one or do you want to?

**Comment by calebissharp** [comment]
@LisaMoore1 Ok, should be good to check again. I've made the plan editable for staff when in the "Submitted as Mandatory" status which should be enough to resolve this issue.
