### ISSUE TITLE
As staff I should be able to discard a mandatory amendment before i submit it

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#760]
As staff I should be able to discard a mandatory amendment before i submit it

**Additional Context**
#707

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by micheal-w-wells** [comment]
blocked by #756 


There is an action buttons component with a canDiscard var (this is currently only used in the AH page) that can be set to true if the status of the plan is staff draft and there is an amendment in progress.

**Comment by LisaMoore1** [comment]
@calebissharp 
Button is visible
Confirmation screen appears
After confirming the queue goes back to showing approved / approved version on screen
**Version still shows the discarded amendment as a version (and as approved)**

**Comment by LisaMoore1** [comment]
Overall I think the issue here is that for all RUPs to identify whether they are Initial, Amendment In progress, or discarded. This would apply on screen when viewing and on any list (including version list) where they may be visible). I’m confused about whether the version list is only showing previous plans or not because I can’t tell by the top of the list if there is a version in progress (or discarded).

**Comment by calebissharp** [comment]
I'm seeing two issues here.

* We should be removing any versions that were created after we started an amendment when the amendment is discarded
* Something weird with the amendment creation process, or at the very least the displaying of amendments. Not as sure the cause of this, maybe related to the privacy versions?

The history not identifying amendments should be covered by #665.

@micheal-w-wells Can you check if this plan (RAN099914) is *actually* in status "C", or if it's just displaying that way? We want it to be "Approved", so if you see that, that's good.

**Comment by micheal-w-wells** [comment]
I'll check

**Comment by micheal-w-wells** [comment]
Awaiting conf - 18 @calebissharp

**Comment by micheal-w-wells** [comment]
Can a discard happen once it's reached a legally standing state?

**Comment by calebissharp** [comment]
Discard should only be able to happen in "staff craft" or "created"

https://github.com/bcgov/range-web/blob/372e00567c7e00cdb8c131321e02b9b5b9b7b035/src/utils/helper/plan.js#L194-L208

There might be an inconsistency in what the client considers legal versions though, leading it to rollback to a wrong version:
https://github.com/bcgov/range-web/blob/372e00567c7e00cdb8c131321e02b9b5b9b7b035/src/api/plan.js#L254-L281

**Comment by micheal-w-wells** [comment]
Do we need to track that an amendment was started and discarded @LisaMoore1 ?

If yes, I think we copy forward the legal version from before and leave the history hidden from the user unless/until there's a requirement to show that.  If no then we can delete all the WIP amendment versions in the db going back to the last legally standing one.

**Comment by LisaMoore1** [comment]
I think there is value iN being able to look at amendments that were discarded but I wouldn’t say that is a common task requiring a built in workflow right now for people to be able to view them. More that if we keep the records we could take a look if we run into a legal or ombudsman type tricky thing (there have been times I’ve found it useful seeing what people thought about doing when I’m reviewing a tricky file).

**Comment by micheal-w-wells** [comment]
I agree there's value in not wiping history here.  I think copying forward the last legal version to be the most recent one, and making sure the legal start and end dates don't change is the best option long term.
