### ISSUE TITLE
AH should not have “Discard Amendment” option if staff started it (and vice versa)

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#768]
Only the category of user that started the amendment (AH/Staff) should be able to discard the amendment. 

I thought I had discarded this amendment (RAN099914) started by staff but apparently not. At any rate I didn’t expect to see this amend option. 

![IMG_7931.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/d2557711-805f-4399-9360-782322922502)

@micheal-w-wells @calebissharp Not sure who this should be assigned to or if it should be on the discard amendment button but just thought I’d make a new issue to be sure it got captured.

**Comment by calebissharp** [comment]
I didn't realize the status went back to staff draft after staff submits it. We're showing the button just based on status and the type of amendment right now, but we may have to add a column that explicitly tracks if the amendment is staff initiated or not. I don't see a clever way out of this one. @micheal-w-wells, thoughts?

**Comment by micheal-w-wells** [comment]
I still kind of feel like we are making things hairy not introducing dedicated statuses for amendment drafts/works in progress but i could be out to lunch.  If it were up to me we'd have new statuses for staff created amendments and AH ones and it would make troubleshooting and looking at history easier and save us from reworking the plan status history component and adding extra logic to the status / header code.  

If we are sticking with recycling statuses, I think we could at the very least double the amendment types to include staff and AH ones.  That might be our happy medium.  

Other option (I'm less a fan of) add another column to plan_status_history and plan_snapshot_summary to say what role put it in that status, it could be a computed one.  In that scenario though now the status component (or someone troubleshooting a plans history and current state) has to take into account:

1. the current plans status
2. the role of the user
3. whether or not its an amendment
4. what kind of amendment
5. whether or not the role of the user matches the role of the person who made the amendment

**Comment by calebissharp** [comment]
I'm not even sure we'd have to double the amendment types. If we just add a couple of statuses for "Mandatory Amendment in Progress - Staff" and "Mandatory Amendment in Progress - AH", we can use those before the amendment is submitted instead of "Staff Draft" and "Created". That would fix the discard button showing up for the wrong user at least. The new statuses would have the same submission options as their non-amendment counterparts.

**Comment by micheal-w-wells** [comment]
now you're speakin' my language.

**Comment by calebissharp** [comment]
I did try adding a new column to `plan`, just for use in determining if the user is able to discard the amendment, but I agree that's less flexible than the statuses.

**Comment by calebissharp** [comment]
I have to say, I like where this is going.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/8854811/81101554-2d6b6000-8ec3-11ea-94eb-331afb9fe2c4.png">
