### ISSUE TITLE
AH submitted mandatory amendment for decision —> staff see a “provide input” orange banner

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#769]
I’m not sure why this banner (see image) is appearing here. I also noticed it yesterday when creating an initial plan (see second image). Staff aren’t providing input here they are either making a recommendation to the DM or requesting the AH make changes. 

![IMG_7940.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/456929d3-1894-4986-b876-86bb82f973e6)

![IMG_7919.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/486a0e1d-b187-43b1-8f4f-853f1be95b01)

It also appears when feedback requested (see mandatory amendment example below) which makes more sense. 
![IMG_7933.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/8df8f5a1-1b6b-420b-bb2e-510ced2d165a)

**Comment by LisaMoore1** [comment]
Yes I think so. I think this orange banner is just for status 13.
Also, the language should be “...Review the Range use Plan and provide feedback.”
Is it possible for you to give me a list of the orange boxes and which statuses/user they are associated with?
I’ll take a look at the document Micheal posted awhile back with the blue headers for the other statuses. I think we now have statuses not on that list as well. Is it complicated to get a list of everything we’ve got implemented now?

**Comment by calebissharp** [comment]
I'll go and track them down.

**Comment by calebissharp** [comment]
It looks like these banners only appear for staff, and only in statuses 13 and 14. 

* **Initial RUP** - Status 13 (Submitted for Review) 
![image](https://user-images.githubusercontent.com/8854811/82357819-7c80bd00-99ba-11ea-85fe-cbd0345c2eea.png)

* **Initial RUP** - Status 14 (Submitted for Final Decision)
![image](https://user-images.githubusercontent.com/8854811/82357861-8dc9c980-99ba-11ea-9cc3-d3d0f5ae9d1a.png)

* **Mandatory Amendment** - Status 13
![image](https://user-images.githubusercontent.com/8854811/82358232-10eb1f80-99bb-11ea-9d5f-794fafb8627d.png)

* **Mandatory Amendment** - Status 14
![image](https://user-images.githubusercontent.com/8854811/82358266-1f393b80-99bb-11ea-879e-baeb5661c2ec.png)

**Comment by LisaMoore1** [comment]
Noticed this isn’t just an amendment thing. Happening for initial plans as well. Not sure if that helps at all? Separate issue needed? Not a stopper for release I don’t think.

**Comment by calebissharp** [comment]
@LisaMoore1 Yep, it appears for initial RUPs and amendments. What exactly is the action to take here? Should the banner be removed for status 14, and we keep it for 13?

**Comment by LisaMoore1** [comment]
@calebissharp Yup. Remove for 14 but keep for 13.  Thx
