### ISSUE TITLE
AH getting error when submitting minor amendment 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#770]
See image below.  Tried twice to same effect.  
Created amendment
Submitted amendment 
Got this message (whether I did a “save draft” action before submitting or not
![IMG_7943.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/7cb37a80-04db-45e8-bd44-931d26bd2bf0)

**Comment by calebissharp** [comment]
@micheal-w-wells, I didn't consider this, but somehow we have to reseed the database to include these new statuses. Maybe just `npx knex seed:run` will work.

**Comment by calebissharp** [comment]
@LisaMoore1 Should be working now; let me know if it's not.
