### ISSUE TITLE
Minor Amendment Bug - selecting "Wrongly Made without effect" deleted the RUP

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/range-web#787]
**Describe the bug**
This bug occurred when going through the workflow of submitting an AH initiated minor amendment. While selecting options as range staff during the "Review Amendment" status, I selected "Wrongly Made - without effect" and it completely deleted my RUP.

**Screenshots**
*Part 1*
![image.png](https://images.zenhubusercontent.com/5e78e949a7e29c75200dbef5/c797d6f0-da4f-4a33-a231-26f76b36c7b9)

*Part 2*
![image.png](https://images.zenhubusercontent.com/5e78e949a7e29c75200dbef5/5e41e5a9-38ac-4b61-8628-6a6ec3c4a086)

*Part 3 after refreshing*
![image.png](https://images.zenhubusercontent.com/5e78e949a7e29c75200dbef5/434872a3-6528-42c1-a598-018784681909)

**Comment by ZoeSimon** [comment]
@calebissharp Here's the bug I was talking about in my comments from #759

**Comment by calebissharp** [comment]
Can you see the plan when logged in as staff?

**Comment by ZoeSimon** [comment]
Negative - the last screenshot is when I was logged in as staff

**Comment by micheal-w-wells** [comment]
somebody else needs to reproduce this one to see if it was a one off anomaly

**Comment by micheal-w-wells** [comment]
@calebissharp is saying this wasn't ready to test

**Comment by ZoeSimon** [comment]
Roger - I think I just selected it when testing the switching to mandatory amendment ticket.
