### ISSUE TITLE
add 'Reason' to version list

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#789]
new field in the endpoint is `legal_reason`

UI issue to go along with https://github.com/bcgov/range-api/issues/203

**Comment by calebissharp** [comment]
@micheal-w-wells Could you please provide some examples of what `legal_reason` could be set to? Thanks.

**Comment by micheal-w-wells** [comment]
- `AH Mandatory`
- `Staff Mandatory`
- `AH Minor`
- `Initial RUP`

@calebissharp

**Comment by micheal-w-wells** [comment]
later we could add 'New AH - New RUP' or whatever we want to call that when we get there.

**Comment by calebissharp** [comment]
And those are just strings?

**Comment by micheal-w-wells** [comment]
yes sir

**Comment by micheal-w-wells** [comment]
@LisaMoore1 note that the 'Reason' column is a work in progress but this is where we will put context.

**Comment by LisaMoore1** [comment]
I like it — helps to keep track of what you’re looking at.
