### ISSUE TITLE
Range officer unable to enter PLD for one particular pasture

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#790]
**Describe the bug**
For whatever reason they are unable to save a pld value for one particular pasture.  It complains it isn't a whole number, despite it being one.

**Expected Behaviour**
She should be able to save.

**Actual Behaviour**
"PLD must be a whole number"

**To Reproduce**
Have yet to be able to do so.  Have asked for clearing cache, they did, I think we might need to steal the RAN in prod so we can debug.

**Screenshots**

**Additional context**

**Comment by micheal-w-wells** [comment]
PLD not displaying as a whole number when not in edit, wondering if that is part of the issue as the problem seems to come up when the plan is passed back to staff to make changes again.

**Comment by micheal-w-wells** [comment]
Was able to replicate it in test, had 27 for the first pasture and it didn't accept anything but 1 for the second.

The staff having the issue also are encountering the error on the last pasture in the list.

**Comment by calebissharp** [comment]
@micheal-w-wells I can't seem to reproduce this locally. I have a pasture with a PLD of 27%, and entering any percentage (that should be valid, ie. between 0 and 100) in another pasture works as expected and allows me to save.

**Comment by micheal-w-wells** [comment]
did you make a second pasture?

**Comment by micheal-w-wells** [comment]
oh my bad, friday brain missed the second half of your comment

**Comment by calebissharp** [comment]
Yep, I had two pastures.

**Comment by micheal-w-wells** [comment]
I think i had to do a save after the first one to get an error on the second, i'm going to try and get it to happen again right now

**Comment by micheal-w-wells** [comment]
![captured](https://user-images.githubusercontent.com/955467/82381470-1b1f1500-99df-11ea-9e25-3cf8cdac6fe6.gif)

**Comment by micheal-w-wells** [comment]
Long story short:  in javascript 0.57 * 100 = 56.

Fixed the handling of these numbers in both the field and also in the validation rule.
