### ISSUE TITLE
Versions screen opening with a little box in top left corner of “view version” tab —> view versions yields blank screen with “Error”

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#791]
RAN099953 — Recommend Ready status ![IMG_7961.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/d954fed3-619f-48d9-ad3a-ee59dbb372ef)

**Comment by LisaMoore1** [comment]
@calebissharp This one seems pretty weird. Once it has shown the versions screen, you select view versions and it goes to the screen mentioned above if you try again it goes straight to the error screen (no version screen between). Not sure if it is a just me thing or not. I cleared cache before I started today.

**Comment by LisaMoore1** [comment]
@calebissharp I got it to open in AH view (after saving draft for a minor amendment) and this is what I see. Guessing that these are all legitimate versions but a little alarming for the AH to see perhaps. 
![IMG_7963.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/0f8dd7d8-1668-4f54-a84c-a1f5e523ab78)

**Comment by micheal-w-wells** [comment]
i'm gonna take a peek at this one right now

**Comment by micheal-w-wells** [comment]
For some reason the plans i tested with recently didn't have this issue but I must have a problem in one of my joins in the `plan_snapshot_summary` table that is causing some duplicates for you.  I'll get it sorted today.  I'd not worry about testing the versions component/page until this is fixed and @okanji has his issues addressed also.

**Comment by micheal-w-wells** [comment]
Note for self i introduced dupes with `src/libs/db2/migrations/20200508082939_make_amendment_work_private.js`

**Comment by micheal-w-wells** [comment]
Just a note the current one isn't going to be green until #789  based on changes we made to have plan end date as the legal end for currently legal plan.
