### ISSUE TITLE
Plan status history not appearing after submitting staff-initiated mandatory amendment

### ISSUE THREAD

**Issue by calebissharp** [bcgov/range-web#792]
**Describe the bug**
Plan status history doesn't appear after a staff initiated amendment is submitted to AH.

**Expected Behaviour**
Plan status history should appear

**Actual Behaviour**
There was no plan status history.

**To Reproduce**
@LisaMoore1 I can't reproduce, can you provide some instructions here?

**Screenshots**

**Additional context**
Originally reported in https://github.com/bcgov/range-web/issues/759#issuecomment-627454557

**Comment by LisaMoore1** [comment]
Poorly worded on my part. Compare that history (statuses) is the two images below...!
This first one shows the history (statuses) while I’m switching a minor amendment to mandatory
[IMG_7967.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/4c0df2ed-c52a-4e47-8c33-fac82665de5b)


This image was immediately after submitting the mandatory amendment to the AH. Check out the weird times/statuses...it doesn’t build on (follow) what was happening before I submitted to AH. 

![IMG_7971.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/5b21a0dc-fe5a-4c9f-a590-68c40a96a016)

I can try to replicate again if you’d like.  ??

**Comment by micheal-w-wells** [comment]
privacy view returning two staffview records

**Comment by micheal-w-wells** [comment]
@calebissharp what do you make of the header part of this?  there were two privacyview records and i think that explains the plan status history weirdness, but i can't make heads or tails of the missing header.

**Comment by calebissharp** [comment]
@micheal-w-wells The header just hasn't been added yet. We don't have messaging to put there.

**Comment by LisaMoore1** [comment]
@calebissharp I think I got a message (I must have accidentally deleted it) re. an issue to provide header language but can’t remember which issue it was. Do you know?

**Comment by micheal-w-wells** [comment]
https://github.com/bcgov/range-web/issues/753#issuecomment-627534439 @LisaMoore1
