### ISSUE TITLE
update versions component to observe 'isCurrentlyLegalVersion' var

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#796]
EDIT: jump to bottom for testing instructions

The versions component was looking for a null effective legal end date to indicate what is current, this is now set to the plan end date so a isCurrentlyLegalVersion var was added.

The component needs to be updated to use it.

**Comment by micheal-w-wells** [comment]
Should only see one legal version and it should be the right color.

The plan end date should now the legal end of the current legal version.

**Comment by LisaMoore1** [comment]
Some funky happenings on the AH view of versions (strange date and not identifying the current legal):
![IMG_7986.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/54d5c23e-84ad-49e1-9403-4a4266cc72c8)

**Comment by LisaMoore1** [comment]
Another unexpected thing after staff made status Wrongly Made - without effect
This is staff view of versions. ![IMG_7991.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/0e153136-d9d7-4ddd-ab76-9d1f41025900)

**Comment by micheal-w-wells** [comment]
I made #800 to track the work around the missing legal version + context for WMWE

This issue and the thing to test here is:
Does it have the right dates for everybody
Does it show one as currently legal (green) and not the others.

**Comment by LisaMoore1** [comment]
@micheal-w-wells The end date is still strange![IMG_8003.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/bfc22158-6f85-4f69-bc7d-fd754a37a4cb)

**Comment by micheal-w-wells** [comment]
Fixed the back end part of it but i messed up the front end change and am pulling the start date for both fields, @okanji is going to address it in his PR.  Thanks @calebissharp for spotting that one.

**Comment by micheal-w-wells** [comment]
- The dates should be right
- Any Stands version should read as 'Stands' and there should only be one per amendment
- The WMWE stuff is still in progress via #800.

**Comment by micheal-w-wells** [comment]
playing tester today, feel free to create an issue if you find one @LisaMoore1
