### ISSUE TITLE
Agreement holder getting 'unexpected error' on attempting to sign

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#803]
**Describe the bug**

**Expected Behaviour**

**Actual Behaviour**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by calebissharp** [comment]
@micheal-w-wells Any more details for this one? ie. is this for amendments/initial RUPS? Or does it occur on all plans? Is this an issue you're seeing in test, locally, or in production? Steps to reproduce would be helpful, as I cannot seem to hit this issue locally.
