### ISSUE TITLE
One range officers agreement showing up in multiple other range officer work queues

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#815]
**Describe the bug**

**Expected Behaviour**

**Actual Behaviour**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by micheal-w-wells** [comment]
@LisaMoore1 if you could sniff out the mysterious one of Tanya's that shows up on Chris' page in FTA and see if you find anything particularly anomalous about it that would be super helpful.

**Comment by ZoeSimon** [comment]
Confirmed with Chris that he is no longer seeing other agrologist's agreement in his work que.
