### ISSUE TITLE
Set up Cypress 

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#819]
Preamble:

The complexity of the myrange app, its content control rules, and the number of different possible workflows for single and double agreement holders is making it a bear to work on without adequate tests.  They were not build by the people who made the main flows, so we've got to tack them on now.

**Describe the task**
Get cypress to be a part of the repo, part of the pipeline, and able to log in to our apps without it getting credentials logged for the world to see.

**Acceptance Criteria**
- [x] Part of repo
- [ ] Pipeline step
- [x] Can login

**Additional context**
- will still need to write tests

**Comment by micheal-w-wells** [comment]
Set up `githubrangeofficer` user with a zone https://github.com/bcgov/range-api/pull/220

**Comment by micheal-w-wells** [comment]
Add cypress to repo + login code (thank you @calebissharp) https://github.com/bcgov/range-web/pull/825

**Comment by micheal-w-wells** [comment]
@calebissharp if you could give me a hand with this it would be appreciated:  Can you make an endpoint, that only in a test environment, deletes a plan and its versions?  It's a temp solution.

If it's easier/less work, could use a hand getting Cypress to run this stuff in containers in an action.

**Comment by micheal-w-wells** [comment]
Going to make the pipeline step a separate task.  The hurdle of getting it rolling, getting it logged in, and figuring out whats needed to do to a workstation to get it to work is what took the time here.

**Comment by calebissharp** [comment]
@micheal-w-wells Would be less work for sure to just spin up a local test environment when we run the cypress tests.
