### ISSUE TITLE
If most recent version is not-approved the AH WQ should show “view” not “edit”

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#824]
Related to #823 re. AH not being able to take any action on a “not-approved” version
![IMG_8036.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/236d45c7-5c2c-49d6-913d-162c11352d10)

**Comment by LisaMoore1** [comment]
@micheal-w-wells Another one related to #823

**Comment by calebissharp** [comment]
I think this one was actually resolved by #829.
