### ISSUE TITLE
DM Work Queue

### ISSUE THREAD

**Issue by ZoeSimon** [bcgov/range-web#847]
**As a** *Decision Maker (DM)* **I want** *to see/filter for and sort for actionable RUPs (those awaiting decision) * **So That** *it is easy to see what needs to be acted on (recommended ready) in addition to having the ability to view approved RUPs*

**Additional Context**
- Refer to ticket #846 

**Acceptance Criteria**
- [ ] The DM can see awaiting and approved RUPs in District (and any assigned that are out of District)
- [x] Add "District Column" to work queue so the DM can see districts
- [ ] Add "delegated from" to work queue, indicate range staff's district and role
- [ ] DM is able to sort and filter by status and district

**Comment by calebissharp** [comment]
Realized I missed the district column here, going to quickly add that in.

**Comment by LisaMoore1** [comment]
Very difficult for DM to quickly see what requires their attention (sorting doesn’t bring what they actually need to the top). 
Some sort of “To Action” toggle that filters down to what they need to action versus all needed or we will not get buy in from DMs
Statuses that DM may need to action are (I think) 15 and 16 as well as the minor amendment one that is requesting the decision maker make a wrongly made determination (I don’t have the most recent status list right now).

**Comment by calebissharp** [comment]
@LisaMoore1 We don't have any filter functionality in the agreements endpoint, so this feature would be non-trivial to implement. Because of time limitations, I think we should focus on critical features and bugs instead.

**Comment by LisaMoore1** [comment]
@calebissharp was just working through the bullets at the top of this issue and filter was one of them so moved here. 
I get that if it is a big implementation task we might have to work around the DM not being able to filter for those they have to action — will be a bummer but we can handle with some process stuff with staff so they make sure they are telling DMs what RAN they need to search for to make/record their decisions. 

Where are we at with the “delegated” stuff for DMs? Is it something decided not to implement? Handle as one-offs?  Can’t remember.  Oh my brain...

**Comment by calebissharp** [comment]
@LisaMoore1 DMs should be able to tell which RANs need action based on the status dot colour, if that helps. Any yellow ones are plans that need attention.

Delegation is handled by changing which user is assigned to a district in the database. It's a manual task right now, but not a super difficult one. To create a UI for that would be a substantial amount of effort, so that's why we went with the simple solution.

**Comment by LisaMoore1** [comment]
@calebissharp Closing this one but again noting the filter thing.  Will just sit on that and work the staff angle. Enhancement at some future date perhaps.
