### ISSUE TITLE
Bare bones needs for file attachment functionality

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#854]
- [x] Need to toggle which attachments agreement holder can see
- [x] Ideally some way to group them (folders/naming)
- [x] file upload
- [x] file delete
- [x] file download
- [x] tab or similar simple UI (Oamar to help figure out) off a RUP
- [x] only staff can upload*  if its easy to allow AH too, then go for it
- [x] AH can see files marked that they can see

**Comment by calebissharp** [comment]
List of allowable statuses https://github.com/bcgov/range-web/blob/dev/src/utils/helper/plan.js#L247
