### ISSUE TITLE
Create agent linking page on RUPs

### ISSUE THREAD

**Issue by calebissharp** [bcgov/range-web#857]
**As a** *staff person* **I want** *a page where I can link clients on an RUP to a user account to act as their agent* **So That** *agreement holders can have other users act on their behalf*.

**Additional Context**
- Can access a 'Manage agents' page/tab when on an RUP
- This page shows a list of all clients for that agreement (from the `client_agreement` table)
- Beside each client there is a dropdown that lets staff pick any user to act as the agent for the client
- There is a button beside the dropdown the clear the agent selection
- Save button at the bottom

Relies on https://github.com/bcgov/range-api/issues/231, https://github.com/bcgov/range-api/issues/232, and https://github.com/bcgov/range-api/issues/233

**Comment by LisaMoore1** [comment]
@calebissharp I’ve attached image with notes:
- text looks like the agent will be for all agreements related to that CLIENT_loc (actually just for this RAN) so needs some explanation of that (or at the very least really highlight the RAN as it isn’t showing anywhere on this screen right now
- there is no navigate back button 
- after save the SAVE button still present and active = made me wonder if the save had actually worked. Maybe disable save after the action has happened or “Save complete” message, or navigate back to where we came from (the RUP or WQ)

**Comment by calebissharp** [comment]
@LisaMoore1 I can't see the image, but your notes make sense to me.

**Comment by LisaMoore1** [comment]
![DF2144B4-454D-4503-938F-C5D50854638A.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/a947af10-9210-4d67-8c90-f70dfe9cf365)

**Comment by calebissharp** [comment]
@LisaMoore1 Ready for another look-over once the deploy completes.

**Comment by LisaMoore1** [comment]
@calebissharp Looks great. How big would it be to add a link back to the RUP version from which we came?

**Comment by LisaMoore1** [comment]
Maybe like this but instead of “Back to RUP” just “Back”
![B72F4D7B-66A9-40FE-BA2B-40BE9035F7A2.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/bc21cd50-da23-4aa5-918b-d9203062a2be)

**Comment by calebissharp** [comment]
@LisaMoore1 Sure, I can change it to make it similar to the button on the versions page.

**Comment by LisaMoore1** [comment]
@calebissharp Great! I think once that is implemented this one can be closed. There is likely something I haven’t caught in testing yet (that seems to be a common thing for me)...but from what I’ve done I really like it!

**Comment by calebissharp** [comment]
Closed via #879
