### ISSUE TITLE
Staff no longer have options related to decisions (was record recommendation step) so cannot submit to DM 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#878]
See this image where I am signed in, am the contact and the decision is noted as ready for decision but I do not have any options to that effect in the drop down menu.  Thinking this is a bug unless is interim to having DM able to record decision on file? If so feel free to axe this issue and point me at the right ones for implementing DM digital decision making. 

![DF4B3D5E-7493-4082-84D1-228B5621CC4C.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/22087d0a-edd0-4520-beb1-bc5652bb671d)

**Comment by LisaMoore1** [comment]
Maybe related to ongoing work on #855. Sort of a middle ground at the moment where we’ve removed ability to record recommendation to DM but haven’t implemented the digital recommendation/DM signature. Maybe?

**Comment by calebissharp** [comment]
@LisaMoore1 I've pushed a fix for this.

**Comment by calebissharp** [comment]
Closing because the fix appears to work for me in test.

![image](https://user-images.githubusercontent.com/8854811/88816765-9b958b00-d171-11ea-8b48-ad2f7ebedca7.png)
