### ISSUE TITLE
As staff person, selecting recommend ready or recommend not ready is saving but not changing status such that decision maker can action (Attempted RAN099961 (amendment))

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#895]

**Comment by LisaMoore1** [comment]
![RAN099961 Recommend Ready.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/f395defc-41a4-46b8-abec-37aac053b424)

**Comment by calebissharp** [comment]
In your screenshot, is this after you selected "recommend (not) ready"?

**Comment by LisaMoore1** [comment]
Yes.

Lisa

**Comment by calebissharp** [comment]
Most likely a duplicate of #896
