### ISSUE TITLE
RAN096665 staff draft — submit button runs save but not submit

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#896]
Maybe same as #894 -- but staff side?  Probably but thought I'd better add it.

**Comment by LisaMoore1** [comment]
![RAN099965 Submit.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/0677ee17-61a6-45c4-9284-153f402a14c9)

**Comment by calebissharp** [comment]
@LisaMoore1 Does this just happen for new plans (ie. you create a plan with the "New Plan" button and immediately submit it, without saving at all)?

**Comment by LisaMoore1** [comment]
No. Attempted on plan that already existed.


Lisa

**Comment by LisaMoore1** [comment]
@calebissharp can’t test this one because it has a minister’s issue and I can’t submit any that have minister’s issues at the moment (see #378). Will test as soon as #378 resolved.
