### ISSUE TITLE
manage zones drop down doesn't list names in alphabetical

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#90]
![image](https://user-images.githubusercontent.com/955467/57796492-3769e100-76fd-11e9-858f-c4d4f26cb403.png)

**Comment by LisaMoore1** [comment]
Manage zones should be disabled (hidden/removed) from the web as this was a pre FTA-API necessity but no longer needed. It's presence could result in undesirable changes to zone assignments (granted they would get overwritten the next FTA sync but incorrect nonetheless).

**Comment by calebissharp** [comment]
@LisaMoore1 Is your comment still relevant? ie. Should we remove the manage zones page?

**Comment by LisaMoore1** [comment]
@calebissharp when FTA API is working predictably well then the manage zones option can be deleted.  An example of where we used it recently was for Ashley Tod who was not seeing the zones she should as pulled in from FTA. I'm not sure if that has been resolved...or how to figure that out.  Perhaps @micheal-w-wells knows.

**Comment by micheal-w-wells** [comment]
I am pretty sure we are good for that one, I think that was a synch issue that has since been resolved.  My vote would be to just hide it for now,  in the event we have an extended FTA synch outage it might be handy to unhide it locally and do some shuffling.  @LisaMoore1 @calebissharp

**Comment by LisaMoore1** [comment]
Hiding it sounds like a good solution to me. 
@calebissharp @micheal-w-wells
