### ISSUE TITLE
As staff, after the AH(s) have signed, I cannot make an attachment (most importantly decision materials) and then save (so I can wait until a later date to make the recommendation to the decision maker. 

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#903]
Not sure how big this is but it hung me up for awhile trying to figure out what was going on. @calebissharp Let’s look at size to address and then decide whether to do it or not. Personally I don’t see that we need to do a “save” function after adding a document.  You add the document — if you don’t want it you remove it. Common practice for staff to be working on something, get it all ready to go but have to wait for confirmation on some detail before actually giving it to the decision maker. 

![C04E0AE6-17C9-4E71-AF05-4A4EE4CB25E4.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/04d9dfb9-6b6a-4f45-8b5b-93fea311ce0b)

**Comment by LisaMoore1** [comment]
@calebissharp “Save Draft” button here works for me. Can see that being useful as this could also be the point where they add the conditions in and would need to be able to save those (see #904)

**Comment by calebissharp** [comment]
Ok, ready to look at again.

**Comment by LisaMoore1** [comment]
@calebissharp I’m still not finding a save button or other option to save changes (attachments Or other such As changes to conditions). Am I missing something?

**Comment by calebissharp** [comment]
@LisaMoore1 Are you signed in as a range officer? This is what I see locally:

![image](https://user-images.githubusercontent.com/8854811/91330574-7ac75200-e77e-11ea-88a3-b952f19dd47f.png)

**Comment by LisaMoore1** [comment]
@calebissharp definitely logged in as range staff and definitely not seeing save.
![2752F410-A49C-486B-B57A-E31BE5842FDD.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/ac40f315-fcb5-4487-93b2-0ff73349c1e3)

**Comment by calebissharp** [comment]
I'm going to rerun the deploy action because I think it might have failed.

**Comment by calebissharp** [comment]
@LisaMoore1 Try looking at this again. Might have been a deploy issue.
