### ISSUE TITLE
Staff unable to make entry into the recommended conditions field.  

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#904]
At some status staff should be able to enter recommended conditions (which DM can copy and past over if they wish). At present unable to edit this field. @calebissharp

![31995EFA-39D7-426F-A0D6-3EEA7C96FE39.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/8c92cbb2-c420-49c8-9090-f764a93880f0)

![F6F9385E-09C0-4B8C-8F30-83677166141A.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/93467807-bb16-40bb-9220-e3741a05a3d5)

**Comment by calebissharp** [comment]
Should be fixed by #901

**Comment by LisaMoore1** [comment]
@calebissharp I can now enter into the field. Not able to save if I’m in “decision required” though but think that will be fixed by whatever fixes #903 so closing this one.  Will reopen if necessary.
