### ISSUE TITLE
AH “Submit Amendment” is saving but not starting submit workflow

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#905]
Unable to continue with amendment flow testing until resolved. Ideas @calebissharp?

**Comment by calebissharp** [comment]
@LisaMoore1 Can't reproduce this one. Which RAN?

**Comment by LisaMoore1** [comment]
@calebissharp RAN099963
Submit is showing “Successfully saved draft” message then moving down to show this part of the screen (but I can’t find any error there). 

![2E4247F6-357D-4ED9-8CE0-2039E3D35754.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/2a23b173-f619-4472-aad8-67f478c03603)

**Comment by LisaMoore1** [comment]
@calebissharp Must be something with this RAN. Submit for RAN099941 working OK

**Comment by calebissharp** [comment]
I'm signing into test as both Andy Dwyer and Leslie Knope, and I'm able to hit submit on RAN099963. Maybe just reload the page and try again?

**Comment by LisaMoore1** [comment]
Working for me now as well — and I see that MInister’s Issue toggle is now set to “true”. Closing this one.
