### ISSUE TITLE
AH1 acting as agent for AH2 signs plan — signature for AH2 happens but signature for AH1 does not

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#909]
This is unexpected. Earlier today when doing this AH1 signing was signing for both. 
Says signatures pending but no options for AH1 to sign now

RAN099912
AH1 does not have option to sign
![IMG_8365.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/8e2a347a-931f-452c-804c-c08e619fb2ad)

Showing that the signature was applied to AH2 not AH1
![IMG_8364.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/d938d50f-b68f-4e36-9b3f-8edaa5e59f72)

AH2 has same screens as above — no option to sign and shows waiting for AH1 signature (Leslie.knope)

**Comment by calebissharp** [comment]
That's strange:

![image](https://user-images.githubusercontent.com/8854811/91343726-d0f1c080-e791-11ea-90f1-c65e68f318cf.png)

**Comment by calebissharp** [comment]
Also, it doesn't appear that Leslie is set to Ben's agent right now.

![image](https://user-images.githubusercontent.com/8854811/91343848-f54d9d00-e791-11ea-803a-f4d20159c3a6.png)

**Comment by LisaMoore1** [comment]
@calebissharp on my side it looks like Leslie is his agent but only for 99912

![IMG_8379.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/54474371-f151-4941-83bd-8a65f95e8e9f)

**Comment by calebissharp** [comment]
Yeah, I think it's just a display bug.

Did you see the screenshot above though were I'm signed in as Leslie Knope and can see the "Sign Submission" button?

**Comment by LisaMoore1** [comment]
I did. Going to close this guy for now as not a showstopper.  Will reopen if it proves to be problematic.
