### ISSUE TITLE
Conditions cannot be added for minor amendment determinations -

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#911]
@calebissharp  I think this was a previous miss on my part.  Not sure how much effort is involved here but it is lower priority. 

DM should not be able to add comments in the review minor amendment status (not sure which number that is but it is where they select either stands, wrongly made or WMWE)

**Comment by calebissharp** [comment]
@LisaMoore1 Not too bad if it's just the one status that DM can't add conditions in.

**Comment by LisaMoore1** [comment]
Just the one I think. After staff have identified it as requiring review (the status from which the DM can select Stands, WM or WMWE)
