### ISSUE TITLE
"Error linking client" when staff attempt to add link from "Manage Clients" tab

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#921]
No problem unlinking but when I tried to relink I got this error message. I tried other clients and still got it. Sorta critical. 

![IMG_8437.png](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/68f32a62-8909-4f0f-9330-0189a47799bc)

**Comment by micheal-w-wells** [comment]
yes it is, ok will have a look ASAP
